#!/bin/bash

export kp=32

cp ../scf/GaAs.$kp.a2Fsave .
cp ../scf/info-q .

cat > input_ef << EOF
&input
  fil_a2F     = 'GaAs.$kp.a2Fsave'
  fil_info    = 'info-q'
  T           = 300         ! in K
  vol         = 305.1201    ! in au^3
  vbm         = 7.6004      ! in eV
  cbm         = 8.1064      ! in eV 
  cbm_i       = 10          ! index of the first conduction band (to be shifted)
  shift       = 0.8839      ! in eV 
  lscissors   = .true.      ! shift conduction bands up to fix band-gap
  doping(1)   = 1e+18       ! in cm-3
  doping(2)   = 1e+19       ! in cm-3
  doping(3)   = 1e+20       ! in cm-3
  doping(4)   = 1e+21       ! in cm-3
  ndop        = 4           ! number of doping values
  nthreads    = 16          ! number of threads for OpenMP parallelization
&end
EOF

./ef.x < input_ef > out.$kp


