#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use pw.x to calculate the total energy and"
$ECHO "the band structure of four simple systems in the non-collinear case:"
$ECHO "Fe, Cu, Ni, O."

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x"
PSEUDO_LIST="Cu.pz-d-rrkjus.UPF Ni.pbe-nd-rrkjus.UPF Fe.pz-nd-rrkjus.UPF \
             O.pbe-rrkjus.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x as: $PW_COMMAND"
$ECHO

# self-consistent calculation
cat > fe.scf.in << EOF
Fe
Iron
 &control
    calculation='scf'
    restart_mode='from_scratch',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    prefix='fe'
 /
 &system
    ibrav = 3, celldm(1) =5.217, nat= 1, ntyp= 1,
    ecutwfc = 25.0,ecutrho = 200.0,
    report=1,
    occupations='smearing', smearing='marzari-vanderbilt', degauss=0.05
    noncolin = .true.
    starting_magnetization(1) = 0.5
    angle1(1) = 90.0
    angle2(1) =  0.0
 /
 &electrons
    conv_thr = 1.0e-8
    mixing_beta = 0.2
 /
ATOMIC_SPECIES
 Fe 55.847 Fe.pz-nd-rrkjus.UPF
ATOMIC_POSITIONS
 Fe 0.0 0.0 0.0
K_POINTS
 11
   0.0625000  0.0625000  0.0625000   1.00
   0.0625000  0.0625000  0.1875000   3.00
   0.0625000  0.0625000  0.3125000   3.00
   0.0625000  0.0625000  0.4375000   3.00
   0.0625000  0.0625000  0.5625000   3.00
   0.0625000  0.0625000  0.6875000   3.00
   0.0625000  0.0625000  0.8125000   3.00
   0.0625000  0.0625000  0.9375000   3.00
   0.0625000  0.1875000  0.1875000   3.00
   0.0625000  0.1875000  0.3125000   6.00
   0.0625000  0.1875000  0.4375000   6.00
EOF
$ECHO "  running the scf calculation for Fe...\c"
$PW_COMMAND < fe.scf.in > fe.scf.out
check_failure $?
$ECHO " done"

# band structure calculation
cat > fe.band.in << EOF
Fe
Iron
 &control
    calculation='bands'
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    prefix='fe'
 /
 &system
    ibrav = 3, celldm(1) =5.217, nat= 1, ntyp= 1,
    ecutwfc = 25.0,ecutrho = 200.0,
    report=1, nbnd = 16
    noncolin = .true.
    starting_magnetization(1) = 0.5
    angle1(1) = 90.0
    angle2(1) =  0.0
 /
 &electrons
    conv_thr = 1.0e-8
    mixing_beta = 0.2
 /
ATOMIC_SPECIES
 Fe 55.847 Fe.pz-nd-rrkjus.UPF
ATOMIC_POSITIONS
 Fe 0.0 0.0 0.0
K_POINTS
 28
   0.0 0.0 0.0 1.0
   0.0 0.0 0.1 1.0
   0.0 0.0 0.2 1.0
   0.0 0.0 0.3 1.0
   0.0 0.0 0.4 1.0
   0.0 0.0 0.5 1.0
   0.0 0.0 0.6 1.0
   0.0 0.0 0.7 1.0
   0.0 0.0 0.8 1.0
   0.0 0.0 0.9 1.0
   0.0 0.0 1.0 1.0
   0.0 0.0 0.0 1.0
   0.0 0.1 0.1 1.0
   0.0 0.2 0.2 1.0
   0.0 0.3 0.3 1.0
   0.0 0.4 0.4 1.0
   0.0 0.5 0.5 1.0
   0.0 0.6 0.6 1.0
   0.0 0.7 0.7 1.0
   0.0 0.8 0.8 1.0
   0.0 0.9 0.9 1.0
   0.0 1.0 1.0 1.0
   0.0 0.0 0.0 1.0
   0.1 0.1 0.1 1.0
   0.2 0.2 0.2 1.0
   0.3 0.3 0.3 1.0
   0.4 0.4 0.4 1.0
   0.5 0.5 0.5 1.0
EOF
$ECHO "  running band structure calculation for Fe...\c"
$PW_COMMAND < fe.band.in > fe.band.out
check_failure $?
$ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/fe*
$ECHO " done"

# self-consistent calculation with penalty functional
cat > fe.pen.in << EOF
 &control
    calculation='scf'
    restart_mode='from_scratch',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    prefix='fe'
 /
 &system
    ibrav = 3, celldm(1) =5.217, nat= 1, ntyp= 1,
    ecutwfc = 25.0,ecutrho = 200.0,
    report=1,
    occupations='smearing', smearing='marzari-vanderbilt', degauss=0.05
    noncolin = .true.
    starting_magnetization(1) = 0.5
    angle1(1) = 85.0
    angle2(1) =  0.0
    constrained_magnetization='atomic'
    lambda = 1
 /
 &electrons
    conv_thr = 1.0e-8
    mixing_beta = 0.2
 /
ATOMIC_SPECIES
 Fe 55.847 Fe.pz-nd-rrkjus.UPF
ATOMIC_POSITIONS
 Fe 0.0 0.0 0.0
K_POINTS
 11
   0.0625000  0.0625000  0.0625000   1.00
   0.0625000  0.0625000  0.1875000   3.00
   0.0625000  0.0625000  0.3125000   3.00
   0.0625000  0.0625000  0.4375000   3.00
   0.0625000  0.0625000  0.5625000   3.00
   0.0625000  0.0625000  0.6875000   3.00
   0.0625000  0.0625000  0.8125000   3.00
   0.0625000  0.0625000  0.9375000   3.00
   0.0625000  0.1875000  0.1875000   3.00
   0.0625000  0.1875000  0.3125000   6.00
   0.0625000  0.1875000  0.4375000   6.00
EOF
$ECHO "  running scf calculation for Fe with penalty functional...\c"
$PW_COMMAND < fe.pen.in > fe.pen.out
check_failure $?
$ECHO " done"

# scf calculation with penalty functional (angle with z-axis constrained)
cat > fe.angl.in << EOF
 &control
    calculation='scf'
    restart_mode='from_scratch',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    prefix='fe'
 /
 &system
    ibrav = 3, celldm(1) =5.217, nat= 1, ntyp= 1,
    ecutwfc = 25.0,ecutrho = 200.0,
    report=1,
    occupations='smearing', smearing='marzari-vanderbilt', degauss=0.05
    noncolin = .true.
    starting_magnetization(1) = 0.5
    angle1(1) = 90.0
    angle2(1) =  0.0
    constrained_magnetization='atomic direction'
    lambda = 1
 /
 &electrons
    conv_thr = 1.0e-8
    mixing_beta = 0.2
 /
ATOMIC_SPECIES
 Fe 55.847 Fe.pz-nd-rrkjus.UPF
ATOMIC_POSITIONS
 Fe 0.0 0.0 0.0
K_POINTS
 11
   0.0625000  0.0625000  0.0625000   1.00
   0.0625000  0.0625000  0.1875000   3.00
   0.0625000  0.0625000  0.3125000   3.00
   0.0625000  0.0625000  0.4375000   3.00
   0.0625000  0.0625000  0.5625000   3.00
   0.0625000  0.0625000  0.6875000   3.00
   0.0625000  0.0625000  0.8125000   3.00
   0.0625000  0.0625000  0.9375000   3.00
   0.0625000  0.1875000  0.1875000   3.00
   0.0625000  0.1875000  0.3125000   6.00
   0.0625000  0.1875000  0.4375000   6.00
EOF
$ECHO "  running the scf calculation for Fe with constrained angle...\c"
$PW_COMMAND < fe.angl.in > fe.angl.out
check_failure $?
$ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/fe*
$ECHO " done"

# scf calculation with penalty functional (total magnetization constrained)
cat > fe.total.in << EOF
 &control
    calculation='scf'
    restart_mode='from_scratch',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    prefix='fe'
 /
 &system
    ibrav = 3, celldm(1) =5.217, nat= 1, ntyp= 1,
    ecutwfc = 25.0,ecutrho = 200.0,
    report=1,
    occupations='smearing', smearing='marzari-vanderbilt', degauss=0.05
    noncolin = .true.
    starting_magnetization(1) = 0.5
    angle1(1) = 45.0
    angle2(1) = 53.0
    constrained_magnetization='total'
    fixed_magnetization(1)=0.3,
    fixed_magnetization(2)=0.4,
    fixed_magnetization(3)=0.5,
    lambda = 0.5
 /
 &electrons
    conv_thr = 1.0e-9
    mixing_beta = 0.3
 /
ATOMIC_SPECIES
 Fe 55.847 Fe.pz-nd-rrkjus.UPF
ATOMIC_POSITIONS
 Fe 0.0 0.0 0.0
K_POINTS AUTOMATIC
4 4 4 1 1 1
EOF
$ECHO "  running the scf calculation for Fe with constrained magnetization...\c"
$PW_COMMAND < fe.total.in > fe.total.out
check_failure $?
$ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/fe*
$ECHO " done"

# self-consistent calculation
cat > cu.scf.in << EOF
 &control
    calculation='scf'
    restart_mode='from_scratch',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
    prefix='cu'
 /
 &system
    ibrav = 2, celldm(1) =6.73, nat= 1, ntyp= 1,
    ecutwfc = 25.0, ecutrho = 300.0
    occupations='smearing', smearing='marzari-vanderbilt', degauss=0.02
    noncolin = .true.
    starting_magnetization(1) = 0.5
    angle1(1) = 90.0
    angle2(1) =  0.0
 /
 &electrons
    conv_thr = 1.0e-8
    mixing_beta = 0.7
 /
ATOMIC_SPECIES
 Cu 63.55 Cu.pz-d-rrkjus.UPF
ATOMIC_POSITIONS
 Cu 0.0 0.0 0.0
K_POINTS (automatic)
 8 8 8 0 0 0
EOF
$ECHO "  running the scf calculation for Cu...\c"
$PW_COMMAND < cu.scf.in > cu.scf.out
check_failure $?
$ECHO " done"

# band structure calculation along delta, sigma and lambda lines
cat > cu.band.in << EOF
 &control
    calculation='bands'
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    prefix='cu'
 /
 &system
    ibrav = 2, celldm(1) =6.73, nat= 1, ntyp= 1,
    ecutwfc = 25.0, ecutrho = 300.0, nbnd = 8
    noncolin = .true.
    starting_magnetization(1) = 0.5
    angle1(1) = 90.0
    angle2(1) =  0.0
 /
 &electrons
 /
ATOMIC_SPECIES
 Cu  63.55 Cu.pz-d-rrkjus.UPF
ATOMIC_POSITIONS
 Cu 0.0 0.0 0.0
K_POINTS
 28
   0.0 0.0 0.0 1.0
   0.0 0.0 0.1 1.0
   0.0 0.0 0.2 1.0
   0.0 0.0 0.3 1.0
   0.0 0.0 0.4 1.0
   0.0 0.0 0.5 1.0
   0.0 0.0 0.6 1.0
   0.0 0.0 0.7 1.0
   0.0 0.0 0.8 1.0
   0.0 0.0 0.9 1.0
   0.0 0.0 1.0 1.0
   0.0 0.0 0.0 1.0
   0.0 0.1 0.1 1.0
   0.0 0.2 0.2 1.0
   0.0 0.3 0.3 1.0
   0.0 0.4 0.4 1.0
   0.0 0.5 0.5 1.0
   0.0 0.6 0.6 1.0
   0.0 0.7 0.7 1.0
   0.0 0.8 0.8 1.0
   0.0 0.9 0.9 1.0
   0.0 1.0 1.0 1.0
   0.0 0.0 0.0 1.0
   0.1 0.1 0.1 1.0
   0.2 0.2 0.2 1.0
   0.3 0.3 0.3 1.0
   0.4 0.4 0.4 1.0
   0.5 0.5 0.5 1.0
EOF
$ECHO "  running the band-structure calculation for Cu...\c"
$PW_COMMAND < cu.band.in > cu.band.out
check_failure $?
$ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/cu*
$ECHO " done"

# self-consistent calculation with cg diagonalization
cat > cu.cg.in << EOF
 &control
    calculation='scf'
    restart_mode='from_scratch',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
    prefix='cu'
 /
 &system
    ibrav = 2, celldm(1) =6.73, nat= 1, ntyp= 1,
    ecutwfc = 25.0, ecutrho = 300.0
    occupations='smearing', smearing='marzari-vanderbilt', degauss=0.02
    noncolin = .true.
    starting_magnetization(1) = 0.5
    angle1(1) = 90.0
    angle2(1) =  0.0
 /
 &electrons
    conv_thr = 1.0e-8
    mixing_beta = 0.7
    diagonalization = 'cg'
 /
ATOMIC_SPECIES
 Cu 63.55 Cu.pz-d-rrkjus.UPF
ATOMIC_POSITIONS
 Cu 0.0 0.0 0.0
K_POINTS (automatic)
 8 8 8 0 0 0
EOF
$ECHO "  running the scf calculation for Cu with cg diagonalization...\c"
$PW_COMMAND < cu.cg.in > cu.cg.out
check_failure $?
$ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/cu*
$ECHO " done"

# self-consistent calculation with diis diagonalization
#cat > cu.diis.in << EOF
# &control
#    calculation='scf'
#    restart_mode='from_scratch',
#    pseudo_dir = '$PSEUDO_DIR/',
#    outdir='$TMP_DIR/'
#    prefix='cu'
# /
# &system
#    ibrav = 2, celldm(1) =6.73, nat= 1, ntyp= 1,
#    ecutwfc = 25.0, ecutrho = 300.0
#    occupations='smearing', smearing='marzari-vanderbilt', degauss=0.02
#    noncolin = .true.
#    starting_magnetization(1) = 0.5
#    angle1(1) = 90.0
#    angle2(1) =  0.0
# /
# &electrons
#    conv_thr = 1.0e-8
#    mixing_beta = 0.7
#    diagonalization = 'diis'
# /
#ATOMIC_SPECIES
# Cu 63.55 Cu.pz-d-rrkjus.UPF
#ATOMIC_POSITIONS
# Cu 0.0 0.0 0.0
#K_POINTS (automatic)
# 8 8 8 0 0 0
#EOF
# $ECHO "  running the scf calculation for Cu with diis diagonalization...\c"
# $PW_COMMAND < cu.diis.in > cu.diis.out
# check_failure $?
# $ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/cu*
$ECHO " done"

# self-consistent calculation
cat > ni.scf.in << EOF
 &control
    calculation='scf'
    restart_mode='from_scratch',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
    prefix='ni'
 /
 &system
    ibrav=2, celldm(1) =6.48, nat=1, ntyp=1,
    ecutwfc = 24.0, ecutrho = 288.0,
    occupations='smearing', smearing='marzari-vanderbilt', degauss=0.02
    noncolin = .true.
    starting_magnetization(1) = 0.1
    angle1(1) = 90.0
    angle2(1) =  0.0
 /
 &electrons
    conv_thr = 1.0e-8
    mixing_beta = 0.7
 /
ATOMIC_SPECIES
 Ni 58.69 Ni.pbe-nd-rrkjus.UPF
ATOMIC_POSITIONS
 Ni 0.0 0.0 0.0
K_POINTS
 60
   0.0625000  0.0625000  0.0625000   1.00
   0.0625000  0.0625000  0.1875000   3.00
   0.0625000  0.0625000  0.3125000   3.00
   0.0625000  0.0625000  0.4375000   3.00
   0.0625000  0.0625000  0.5625000   3.00
   0.0625000  0.0625000  0.6875000   3.00
   0.0625000  0.0625000  0.8125000   3.00
   0.0625000  0.0625000  0.9375000   3.00
   0.0625000  0.1875000  0.1875000   3.00
   0.0625000  0.1875000  0.3125000   6.00
   0.0625000  0.1875000  0.4375000   6.00
   0.0625000  0.1875000  0.5625000   6.00
   0.0625000  0.1875000  0.6875000   6.00
   0.0625000  0.1875000  0.8125000   6.00
   0.0625000  0.1875000  0.9375000   6.00
   0.0625000  0.3125000  0.3125000   3.00
   0.0625000  0.3125000  0.4375000   6.00
   0.0625000  0.3125000  0.5625000   6.00
   0.0625000  0.3125000  0.6875000   6.00
   0.0625000  0.3125000  0.8125000   6.00
   0.0625000  0.3125000  0.9375000   6.00
   0.0625000  0.4375000  0.4375000   3.00
   0.0625000  0.4375000  0.5625000   6.00
   0.0625000  0.4375000  0.6875000   6.00
   0.0625000  0.4375000  0.8125000   6.00
   0.0625000  0.4375000  0.9375000   6.00
   0.0625000  0.5625000  0.5625000   3.00
   0.0625000  0.5625000  0.6875000   6.00
   0.0625000  0.5625000  0.8125000   6.00
   0.0625000  0.6875000  0.6875000   3.00
   0.0625000  0.6875000  0.8125000   6.00
   0.0625000  0.8125000  0.8125000   3.00
   0.1875000  0.1875000  0.1875000   1.00
   0.1875000  0.1875000  0.3125000   3.00
   0.1875000  0.1875000  0.4375000   3.00
   0.1875000  0.1875000  0.5625000   3.00
   0.1875000  0.1875000  0.6875000   3.00
   0.1875000  0.1875000  0.8125000   3.00
   0.1875000  0.3125000  0.3125000   3.00
   0.1875000  0.3125000  0.4375000   6.00
   0.1875000  0.3125000  0.5625000   6.00
   0.1875000  0.3125000  0.6875000   6.00
   0.1875000  0.3125000  0.8125000   6.00
   0.1875000  0.4375000  0.4375000   3.00
   0.1875000  0.4375000  0.5625000   6.00
   0.1875000  0.4375000  0.6875000   6.00
   0.1875000  0.4375000  0.8125000   6.00
   0.1875000  0.5625000  0.5625000   3.00
   0.1875000  0.5625000  0.6875000   6.00
   0.1875000  0.6875000  0.6875000   3.00
   0.3125000  0.3125000  0.3125000   1.00
   0.3125000  0.3125000  0.4375000   3.00
   0.3125000  0.3125000  0.5625000   3.00
   0.3125000  0.3125000  0.6875000   3.00
   0.3125000  0.4375000  0.4375000   3.00
   0.3125000  0.4375000  0.5625000   6.00
   0.3125000  0.4375000  0.6875000   6.00
   0.3125000  0.5625000  0.5625000   3.00
   0.4375000  0.4375000  0.4375000   1.00
   0.4375000  0.4375000  0.5625000   3.00
EOF
$ECHO "  running the scf calculation for Ni...\c"
$PW_COMMAND < ni.scf.in > ni.scf.out
check_failure $?
$ECHO " done"

# band structure calculation along delta, sigma and lambda lines
cat > ni.band.in << EOF
 &control
    calculation='bands'
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
    prefix='ni'
 /
 &system
    ibrav=2, celldm(1) =6.48, nat=1, ntyp=1,
    starting_magnetization(1)=0.7,
    ecutwfc = 24.0, ecutrho = 288.0, nbnd = 8
    noncolin = .true.
    starting_magnetization(1) = 0.5
    angle1(1) = 90.0
    angle2(1) =  0.0

 /
 &electrons
 /
ATOMIC_SPECIES
 Ni 58.69 Ni.pbe-nd-rrkjus.UPF
ATOMIC_POSITIONS
 Ni 0.0 0.0 0.0
K_POINTS
 28
   0.0 0.0 0.0 1.0
   0.0 0.0 0.1 1.0
   0.0 0.0 0.2 1.0
   0.0 0.0 0.3 1.0
   0.0 0.0 0.4 1.0
   0.0 0.0 0.5 1.0
   0.0 0.0 0.6 1.0
   0.0 0.0 0.7 1.0
   0.0 0.0 0.8 1.0
   0.0 0.0 0.9 1.0
   0.0 0.0 1.0 1.0
   0.0 0.0 0.0 1.0
   0.0 0.1 0.1 1.0
   0.0 0.2 0.2 1.0
   0.0 0.3 0.3 1.0
   0.0 0.4 0.4 1.0
   0.0 0.5 0.5 1.0
   0.0 0.6 0.6 1.0
   0.0 0.7 0.7 1.0
   0.0 0.8 0.8 1.0
   0.0 0.9 0.9 1.0
   0.0 1.0 1.0 1.0
   0.0 0.0 0.0 1.0
   0.1 0.1 0.1 1.0
   0.2 0.2 0.2 1.0
   0.3 0.3 0.3 1.0
   0.4 0.4 0.4 1.0
   0.5 0.5 0.5 1.0
EOF
$ECHO "  running the band-structure calculation for Ni...\c"
$PW_COMMAND < ni.band.in > ni.band.out
check_failure $?
$ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/ni*
$ECHO " done"

# self-consistent calculation + relaxation of atoms
cat > o2.relax.in << EOF
 &control
    calculation='relax'
    restart_mode='from_scratch',!'restart', !
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
    prefix='o2'
 /
 &system
    ibrav = 1, celldm(1) =7.50, nat= 2, ntyp= 2,
    ecutwfc = 25.0,ecutrho = 200.0,
    report=1,
    occupations='smearing', smearing='marzari-vanderbilt', degauss=0.05
    noncolin = .true.
    starting_magnetization(1) = 0.5
    angle1(1) = 90.0
    angle2(1) =  0.0
    starting_magnetization(2) = 0.5
    angle1(2) = 90.0
    angle2(2) =  0.0
 /
 &electrons
    mixing_beta = 0.2
 /
 &ions
 /
ATOMIC_SPECIES
 O1 16.0 O.pbe-rrkjus.UPF
 O2 16.0 O.pbe-rrkjus.UPF
ATOMIC_POSITIONS
 O1 0.0 0.0 0.0
 O2 0.20 0.20 0.20
K_POINTS
 1
   0.0 0.0 0.0 1.00
EOF
$ECHO "  running scf calculation with relax for oxygen molecule...\c"
$PW_COMMAND < o2.relax.in > o2.relax.out
check_failure $?
$ECHO " done"
# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/o.*
$ECHO " done"


$ECHO
$ECHO "$EXAMPLE_DIR: done"
