#!/bin/sh

###############################################################################
##
##  HIGH VERBOSITY EXAMPLE
##
###############################################################################

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example calculates the band structure of ferromagnetic bcc-Fe."
$ECHO "in the noncollinear spin-orbit case."
$ECHO

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x bands.x plotband.x"
PSEUDO_LIST="Fe.rel-pbe-kjpaw.UPF Au.rel-pz-kjpaw.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE \
                http://www.quantum-espresso.org/pseudo/1.3/UPF/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
BAND_COMMAND="$PARA_PREFIX $BIN_DIR/bands.x $PARA_POSTFIX"
PLOTBAND_COMMAND="$BIN_DIR/plotband.x"
$ECHO
$ECHO "  running pw.x     as: $PW_COMMAND"
$ECHO " running bands.x as: $BAND_COMMAND"
$ECHO " running plotband.x as: $PLOTBAND_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"

# self-consistent calculation for bcc-Fe with fully relativistic PAW-PP
cat > Fe.scf_pbe.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>


<input calculation="scf" prefix="Fe">

	<cell type="qecell">
		<qecell ibrav="3" alat="5.42">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="1">
		<specie name="Fe">
			<property name="mass">
				<real>0.0</real>
			</property>
			<property name="pseudofile">
				<string>Fe.rel-pbe-kjpaw.UPF</string>
			</property>
			<property name="starting_magnetization">
				<real>0.5</real>
			</property>			
		</specie>
	</atomic_species>

	<atomic_list units="alat" nat="1" >
		<atom name="Fe">
			<position>
				<real rank="1" n1="3">
					0.0000000   0.00000000   0.0  
				</real>
			</position>
		</atom>						
	</atomic_list>		
	
	
	<field name="InputOutput">

		<parameter name="pseudo_dir">
			<string>
			 $PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
			  $TMP_DIR/
			</string>
		</parameter>
	
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				45.0
			</real>
		</parameter>
		
		<parameter name="ecutrho">
			<real>
				300.0
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.0d-10
			</real>
		</parameter>
		
	</field>
	
	<field name="Options">

		<parameter name="occupations">
			<string>
				smearing
			</string>
		</parameter>
		
		<parameter name="smearing">
			<string>
				mp
			</string>
		</parameter>
		
		<parameter name="degauss">
			<real>
				0.04
			</real>
		</parameter>			
		
		<parameter name="noncolin">
			<logical>
				true
			</logical>
		</parameter>
		
		<parameter name="lspinorb">
			<logical>
				true
			</logical>
		</parameter>
		
	</field>	
	
	<k_points type="automatic">
		<mesh>
			<integer rank="1" n1="6">
				8 8 8 1 1 1 
			</integer>
		</mesh> 
	</k_points>
	
</input>
EOF
$ECHO "  running the scf calculation for Fe with PAW spin-orbit...\c"
$PW_COMMAND < Fe.scf_pbe.xml > Fe.scf_pbe.out
check_failure $?
$ECHO " done"

# self-consistent calculation for bcc-Fe with fully relativistic PAW-PP
cat > Fe.band_pbe.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>


<input calculation="bands" prefix="Fe">

	<cell type="qecell">
		<qecell ibrav="3" alat="5.42">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="1">
		<specie name="Fe">
			<property name="mass">
				<real>0.0</real>
			</property>
			<property name="pseudofile">
				<string>Fe.rel-pbe-kjpaw.UPF</string>
			</property>
			<property name="starting_magnetization">
				<real>0.5</real>
			</property>			
		</specie>
	</atomic_species>

	<atomic_list units="alat" nat="1" >
		<atom name="Fe">
			<position>
				<real rank="1" n1="3">
					0.0000000   0.00000000   0.0
				</real>
			</position>
		</atom>						
	</atomic_list>		
	
	
	<field name="InputOutput">

		<parameter name="pseudo_dir">
			<string>
			 $PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
			  $TMP_DIR/
			</string>
		</parameter>
	
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				45.0
			</real>
		</parameter>
		
		<parameter name="ecutrho">
			<real>
				300.0
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.0d-10
			</real>
		</parameter>
		
	</field>
	
	<field name="Options">

		<parameter name="occupations">
			<string>
				smearing
			</string>
		</parameter>
		
		<parameter name="smearing">
			<string>
				mp
			</string>
		</parameter>
		
		<parameter name="degauss">
			<real>
				0.04
			</real>
		</parameter>			
		
		<parameter name="noncolin">
			<logical>
				true
			</logical>
		</parameter>
		
		<parameter name="lspinorb">
			<logical>
				true
			</logical>
		</parameter>
		
	</field>	
	
	<k_points type="tpiba_b">
		<mesh npoints="3">
			<real rank="2" n1="4" n2="3">
				    1.0 0.0 0.0 40.0
				    0.0 0.0 0.0 40.0
				    0.0 0.0 1.0 1.0
			</real>
		</mesh> 
	</k_points>
</input>
EOF
$ECHO "  running the band calculation for Fe with PAW and spin-orbit...\c"
$PW_COMMAND < Fe.band_pbe.xml > Fe.band_pbe.out
check_failure $?
$ECHO " done"

# self-consistent calculation for bcc-Fe with fully relativistic PAW-PP
cat > Fe.bands.in << EOF
 &inputpp
    prefix='Fe',
    outdir='$TMP_DIR/'
    filband='fe.band'
    lsym=.true.,
 /
EOF
$ECHO "  checking band symmetry of bcc-Fe with PAW and spin-orbit...\c"
$BAND_COMMAND < Fe.bands.in > Fe.bands.out
check_failure $?
$ECHO " done"

cat > plotband.in << EOF
fe.band
0 50
ciao
EOF
$ECHO "  Plotting the bands...\c"
$PLOTBAND_COMMAND < plotband.in > plotband.out
check_failure $?
$ECHO " done"

cat > plot.gnu << EOF
set encoding iso_8859_15
set terminal postscript enhanced color "Helvetica" 24
set output "gnuplot.ps"
#
set key off

set xrange [0:2]
set yrange [-.5:0.5]
set arrow from 1,-0.5 to 1,0.5 nohead lw 2 lt -1 front
set xzeroaxis lw 2 lt -1
set border lw 2
unset xtics
set size 0.85,1.0
set ylabel "Energy (eV)"
set label "{/Symbol G}" at -.02,-0.535
set label "{/Symbol G}" at 1.97,-0.535
set label "(1,0,0) H (0,0,1)" at 1.0,-0.535 center
set label " M//(0,0,1) " at 1.47,0.43
set label " D_{4h} [C_{4h}] " at -0.12,0.535 font ",16"
set label " D_{4h} [C_{4h}] " at  0.90,0.535 font ",16"
set label " D_{4h} [C_{4h}] " at  1.82,0.535 font ",16"
set label " C_{2v} [C_{s}] " at  0.4,0.535 font ",16"
set label " D_{4} [C_{4}] " at  1.4,0.535 font ",16"
set label " {/Symbol G}_4 " at 0.55,-0.45 font ",16" tc rgb "blue"
set label " {/Symbol G}_3 " at 0.24,-0.45 font ",16" tc rgb "red"
set label " {/Symbol G}_6 " at 1.08,-0.45 font ",16" tc rgb "black"
set label " {/Symbol G}_7 " at 1.32,-0.45 font ",16" tc rgb "green"
set label " {/Symbol G}_8 " at 1.2,-0.45 font ",16" tc rgb "blue"
set label " {/Symbol G}_5 " at 1.62,-0.45 font ",16" tc rgb "red"
ef=12.5628
plot 'ciao.1.1' u (1.-\$1):(\$2-ef) w l lw 3   lt 1 lc rgb "red", 'ciao.1.2' u (1.-\$1):(\$2-ef) w l lw 3 lt 5 lc rgb "blue", 'ciao.2.1' u (3.-\$1):(\$2-ef) w l lw 3 lt 1 lc rgb "red", 'ciao.2.2' u (3.-\$1):(\$2-ef) w l lw 3 lt 4 lc rgb "black", 'ciao.2.3' u (3.-\$1):(\$2-ef) w l lw 3 lt 1 lc rgb "green", 'ciao.2.4' u (3.-\$1):(\$2-ef) w l lw 3 lt 5 lc rgb "blue"
EOF

gnuplot plot.gnu

$ECHO
$ECHO "$EXAMPLE_DIR: done"
