#!/bin/bash

if [ ! -d bin ]; then
mkdir bin
fi

cd ./SRC

make
rm -f *.o

cd ../bin

ln -s  ../SRC/bands_to_gnuplot.x bands_to_gnuplot.x
ln -s  ../SRC/E_min_max.x E_min_max.x
ln -s  ../SRC/k_for_bands.x k_for_bands.x

cd ..



