#!/bin/sh

###############################################################################
##
##  HIGH VERBOSITY EXAMPLE
##
###############################################################################

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use pw.x and ph.x to calculate"
$ECHO "the Raman tensor for AlAs."

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x ph.x"
PSEUDO_LIST="Al.pz-vbc.UPF As.pz-bhs.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
PH_COMMAND="$PARA_PREFIX $BIN_DIR/ph.x $PARA_POSTFIX"

$ECHO
$ECHO "  running pw.x as:  $PW_COMMAND"
$ECHO "  running ph.x as:  $PH_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/alas*
rm -rf $TMP_DIR/_ph0/alas*
$ECHO " done"

#
# self-consistent calculation
#
cat > alas.scf.in << EOF
 &control
    calculation='scf'
    restart_mode='from_scratch',
    tstress = .true.
    tprnfor = .true.
    prefix='alas',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
 /
 &system
    nosym = .false.,
    ibrav=  2, celldm(1) =10.575, nat=  2, ntyp= 2,
    ecutwfc = 10.0
 /
 &electrons
    conv_thr =  1.0d-8
    mixing_beta = 0.7
 /
ATOMIC_SPECIES
 Al  26.98  Al.pz-vbc.UPF
 As  74.92  As.pz-bhs.UPF
ATOMIC_POSITIONS (alat)
 Al 0.00 0.00 0.00
 As 0.25 0.25 0.25
K_POINTS {automatic}
 4 4 4 1 1 1
EOF

$ECHO "  running the scf calculation...\c"
$PW_COMMAND < alas.scf.in > alas.scf.out
check_failure $?
$ECHO " done"

# response calculation
cat > alas.ph.in << EOF
phonons of AlAs at Gamma
 &inputph
  tr2_ph=1.0d-12,
  prefix='alas',
  epsil=.true.,
  trans=.true.,
  lraman=.true.,
  elop=.true.,
  zeu=.true.,
  zue=.true.,
  amass(1)=26.98,
  amass(2)=74.92,
  outdir='$TMP_DIR/',
  fildyn='alas.dynG',
  fildrho='alas.drho',
 /
0.0 0.0 0.0
EOF

$ECHO "  running the response calculation...\c"
$PH_COMMAND < alas.ph.in > alas.ph.out
$ECHO " done"

cat > alas.ph.rec.in << EOF
phonons of AlAs at Gamma
 &inputph
  tr2_ph=1.0d-12,
  prefix='alas',
  epsil=.true.,
  trans=.true.,
  lraman=.true.,
  elop=.true.,
  zeu=.true.,
  zue=.true.,
  recover=.true.
  amass(1)=26.98,
  amass(2)=74.92,
  outdir='$TMP_DIR/',
  fildyn='alas.dynG',
  fildrho='alas.drho',
 /
0.0 0.0 0.0
EOF

$ECHO "  recovering the response calculation...\c"
$PH_COMMAND < alas.ph.rec.in > alas.ph.rec.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR: done"

