cfft3ds – FFTXlib
cfft3ds Subroutine
Source File
Variables
m incx1 incx2 i k j err idir ip ii jj tscale icurrent dims
Subroutines
lookup init_plan
All Procedures
allowed bw_tg_cft3_scatter bw_tg_cft3_xy bw_tg_cft3_z cfft3d cfft3d cfft3d cfft3d cfft3d cfft3ds cfft3ds cfft3ds cfft3ds cfft3ds cft_1z cft_1z cft_1z cft_1z cft_1z cft_2xy cft_2xy cft_2xy cft_2xy cft_2xy cft_b cft_b_omp cft_b_omp_init cgather_sym cgather_sym_many cscatter_sym_many fft_box_allocate fft_box_deallocate fft_box_set fft_dlay_allocate fft_dlay_deallocate fft_dlay_scalar fft_dlay_set fft_scatter fftx_error__ fw_tg_cft3_scatter fw_tg_cft3_xy fw_tg_cft3_z fwfft fwfft_x gather_complex_grid gather_grid gather_real_grid good_fft_dimension good_fft_order invfft invfft_b invfft_x pack_group_sticks pstickset pstickset_custom scatter_complex_grid scatter_grid scatter_real_grid sticks_countg sticks_deallocate sticks_dist sticks_maps sticks_maps_scalar sticks_ordered_dist sticks_pairup sticks_sort task_groups_init task_groups_init_first tg_cft3s tg_cgather tg_gather unpack_group_sticks
public subroutine cfft3ds(f, nx, ny, nz, ldx, ldy, ldz, isign, do_fft_x, do_fft_y)
Arguments
Type Intent Optional Attributes Name
complex(kind=DP) :: f(ldx*ldy*ldz)
integer :: nx
integer :: ny
integer :: nz
integer :: ldx
integer :: ldy
integer :: ldz
integer :: isign
integer :: do_fft_x(:)
integer :: do_fft_y(:)
Calls
Variables
Type Visibility Attributes Name Initial
integer, public :: m
integer, public :: incx1
integer, public :: incx2
integer, public :: i
integer, public :: k
integer, public :: j
integer, public :: err
integer, public :: idir
integer, public :: ip
integer, public :: ii
integer, public :: jj
real(kind=DP), public :: tscale
integer, public, SAVE :: icurrent = 1
integer, public, SAVE :: dims(3,ndims) = -1
Subroutines
subroutine lookup()
Arguments
None
subroutine init_plan()
Arguments
None
Call graph
cfft3ds calls fftx_error__, fw_plan, dscal, bw_plan, fftw_inplace_drv_1d, lookup, init_plan