cft_1z – FFTXlib
cft_1z Subroutine
Source File
Variables
tscale i err idir ip void zdims icurrent found tid offset ldz_t hand dfti_first dfti_status
Subroutines
check_dims lookup init_dfti
All Procedures
allowed bw_tg_cft3_scatter bw_tg_cft3_xy bw_tg_cft3_z cfft3d cfft3d cfft3d cfft3d cfft3d cfft3ds cfft3ds cfft3ds cfft3ds cfft3ds cft_1z cft_1z cft_1z cft_1z cft_1z cft_2xy cft_2xy cft_2xy cft_2xy cft_2xy cft_b cft_b_omp cft_b_omp_init cgather_sym cgather_sym_many cscatter_sym_many fft_box_allocate fft_box_deallocate fft_box_set fft_dlay_allocate fft_dlay_deallocate fft_dlay_scalar fft_dlay_set fft_scatter fftx_error__ fw_tg_cft3_scatter fw_tg_cft3_xy fw_tg_cft3_z fwfft fwfft_x gather_complex_grid gather_grid gather_real_grid good_fft_dimension good_fft_order invfft invfft_b invfft_x pack_group_sticks pstickset pstickset_custom scatter_complex_grid scatter_grid scatter_real_grid sticks_countg sticks_deallocate sticks_dist sticks_maps sticks_maps_scalar sticks_ordered_dist sticks_pairup sticks_sort task_groups_init task_groups_init_first tg_cft3s tg_cgather tg_gather unpack_group_sticks
public subroutine cft_1z(c, nsl, nz, ldz, isign, cout)
Arguments
Type Intent Optional Attributes Name
complex(kind=DP) :: c(:)
integer, intent(in) :: nsl
integer, intent(in) :: nz
integer, intent(in) :: ldz
integer, intent(in) :: isign
complex(kind=DP) :: cout(:)
Calls
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=DP), public :: tscale
integer, public :: i
integer, public :: err
integer, public :: idir
integer, public :: ip
integer, public :: void
integer, public, SAVE :: zdims(3,ndims) = -1
integer, public, SAVE :: icurrent = 1
logical, public :: found
integer, public :: tid
integer, public :: offset
integer, public :: ldz_t
type(dfti_descriptor_array), public, SAVE :: hand(ndims)
logical, public, SAVE :: dfti_first = .TRUE.
integer, public :: dfti_status = 0
Subroutines
subroutine check_dims()
Arguments
None
subroutine lookup()
Arguments
None
subroutine init_dfti()
Arguments
None
Call graph
cft_1z calls check_dims, fftx_error__, lookup, dfticomputebackward, stop_clock, init_dfti, start_clock, dfticomputeforward
fw_tg_cft3_z calls cft_1z
tg_cft3s calls cft_1z
bw_tg_cft3_z calls cft_1z
invfft_x calls tg_cft3s
fwfft_x calls tg_cft3s