cft_2xy – FFTXlib
cft_2xy Subroutine
Source File
Variables
i k j err idir ip kk void tscale icurrent dims dofft done stdout offset nx_t ny_t nzl_t ldx_t ldy_t itid mytid ntids ltabl fw_tablex fw_tabley bw_tablex bw_tabley
All Procedures
allowed bw_tg_cft3_scatter bw_tg_cft3_xy bw_tg_cft3_z cfft3d cfft3d cfft3d cfft3d cfft3d cfft3ds cfft3ds cfft3ds cfft3ds cfft3ds cft_1z cft_1z cft_1z cft_1z cft_1z cft_2xy cft_2xy cft_2xy cft_2xy cft_2xy cft_b cft_b_omp cft_b_omp_init cgather_sym cgather_sym_many cscatter_sym_many fft_box_allocate fft_box_deallocate fft_box_set fft_dlay_allocate fft_dlay_deallocate fft_dlay_scalar fft_dlay_set fft_scatter fftx_error__ fw_tg_cft3_scatter fw_tg_cft3_xy fw_tg_cft3_z fwfft fwfft_x gather_complex_grid gather_grid gather_real_grid good_fft_dimension good_fft_order invfft invfft_b invfft_x pack_group_sticks pstickset pstickset_custom scatter_complex_grid scatter_grid scatter_real_grid sticks_countg sticks_deallocate sticks_dist sticks_maps sticks_maps_scalar sticks_ordered_dist sticks_pairup sticks_sort task_groups_init task_groups_init_first tg_cft3s tg_cgather tg_gather unpack_group_sticks
public subroutine cft_2xy(r, nzl, nx, ny, ldx, ldy, isign, pl2ix)
Arguments
Type Intent Optional Attributes Name
complex(kind=DP) :: r(:)
integer, intent(in) :: nzl
integer, intent(in) :: nx
integer, intent(in) :: ny
integer, intent(in) :: ldx
integer, intent(in) :: ldy
integer, intent(in) :: isign
integer, intent(in), optional :: pl2ix(:)
Calls
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: k
integer, public :: j
integer, public :: err
integer, public :: idir
integer, public :: ip
integer, public :: kk
integer, public :: void
real(kind=DP), public :: tscale
integer, public, SAVE :: icurrent = 1
integer, public, SAVE :: dims(4,ndims) = -1
logical, public :: dofft(nfftx)
logical, public :: done
integer, public, parameter :: stdout = 6
integer, public :: offset
integer, public :: nx_t
integer, public :: ny_t
integer, public :: nzl_t
integer, public :: ldx_t
integer, public :: ldy_t
integer, public :: itid
integer, public :: mytid
integer, public :: ntids
integer, public, parameter :: ltabl = 20000+3*nfftx
real(kind=DP), public, SAVE :: fw_tablex(ltabl,ndims)
real(kind=DP), public, SAVE :: fw_tabley(ltabl,ndims)
real(kind=DP), public, SAVE :: bw_tablex(ltabl,ndims)
real(kind=DP), public, SAVE :: bw_tabley(ltabl,ndims)
Call graph
cft_2xy calls fftx_error__, stop_clock, start_clock, dcft