cft_b – FFTXlib
cft_b Subroutine
Source File
Variables
isign naux ibid nplanes nstart k tscale ip i icurrent dims
All Procedures
allowed bw_tg_cft3_scatter bw_tg_cft3_xy bw_tg_cft3_z cfft3d cfft3d cfft3d cfft3d cfft3d cfft3ds cfft3ds cfft3ds cfft3ds cfft3ds cft_1z cft_1z cft_1z cft_1z cft_1z cft_2xy cft_2xy cft_2xy cft_2xy cft_2xy cft_b cft_b_omp cft_b_omp_init cgather_sym cgather_sym_many cscatter_sym_many fft_box_allocate fft_box_deallocate fft_box_set fft_dlay_allocate fft_dlay_deallocate fft_dlay_scalar fft_dlay_set fft_scatter fftx_error__ fw_tg_cft3_scatter fw_tg_cft3_xy fw_tg_cft3_z fwfft fwfft_x gather_complex_grid gather_grid gather_real_grid good_fft_dimension good_fft_order invfft invfft_b invfft_x pack_group_sticks pstickset pstickset_custom scatter_complex_grid scatter_grid scatter_real_grid sticks_countg sticks_deallocate sticks_dist sticks_maps sticks_maps_scalar sticks_ordered_dist sticks_pairup sticks_sort task_groups_init task_groups_init_first tg_cft3s tg_cgather tg_gather unpack_group_sticks
public subroutine cft_b(f, nx, ny, nz, ldx, ldy, ldz, imin3, imax3, sgn)
Arguments
Type Intent Optional Attributes Name
complex(kind=dp) :: f(:)
integer :: nx
integer :: ny
integer :: nz
integer :: ldx
integer :: ldy
integer :: ldz
integer :: imin3
integer :: imax3
integer :: sgn
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: isign
integer, public :: naux
integer, public :: ibid
integer, public :: nplanes
integer, public :: nstart
integer, public :: k
real(kind=DP), public :: tscale
integer, public :: ip
integer, public :: i
integer, public, save :: icurrent = 1
integer, public, save :: dims(4,ndims) = -1
Call graph
cft_b calls bw_planz, bw_planx, fftx_error__, bw_planxy, fftw_inplace_drv_1d, destroy_plan_1d, create_plan_1d, bw_plany, destroy_plan_2d, create_plan_2d
invfft_b calls cft_b