cgather_sym_many – FFTXlib
cgather_sym_many Subroutine
Source File
Variables
proc info ibnd jbnd displs recvcount
All Procedures
allowed bw_tg_cft3_scatter bw_tg_cft3_xy bw_tg_cft3_z cfft3d cfft3d cfft3d cfft3d cfft3d cfft3ds cfft3ds cfft3ds cfft3ds cfft3ds cft_1z cft_1z cft_1z cft_1z cft_1z cft_2xy cft_2xy cft_2xy cft_2xy cft_2xy cft_b cft_b_omp cft_b_omp_init cgather_sym cgather_sym_many cscatter_sym_many fft_box_allocate fft_box_deallocate fft_box_set fft_dlay_allocate fft_dlay_deallocate fft_dlay_scalar fft_dlay_set fft_scatter fftx_error__ fw_tg_cft3_scatter fw_tg_cft3_xy fw_tg_cft3_z fwfft fwfft_x gather_complex_grid gather_grid gather_real_grid good_fft_dimension good_fft_order invfft invfft_b invfft_x pack_group_sticks pstickset pstickset_custom scatter_complex_grid scatter_grid scatter_real_grid sticks_countg sticks_deallocate sticks_dist sticks_maps sticks_maps_scalar sticks_ordered_dist sticks_pairup sticks_sort task_groups_init task_groups_init_first tg_cft3s tg_cgather tg_gather unpack_group_sticks
public subroutine cgather_sym_many(dfftp, f_in, f_out, nbnd, nbnd_proc, start_nbnd_proc)
Arguments
Type Intent Optional Attributes Name
type(fft_dlay_descriptor), intent(in) :: dfftp
complex(kind=DP) :: f_in(dfftp%nnr,nbnd)
complex(kind=DP) :: f_out(dfftp%nnp*dfftp%nr3x,nbnd_proc(dfftp%mype+1))
integer :: nbnd
integer :: nbnd_proc(dfftp%nproc)
integer :: start_nbnd_proc(dfftp%nproc)
Calls
Variables
Type Visibility Attributes Name Initial
integer, public :: proc
integer, public :: info
integer, public :: ibnd
integer, public :: jbnd
integer, public :: displs(0:dfftp%nproc-1)
integer, public :: recvcount(0:dfftp%nproc-1)
Call graph
cgather_sym_many calls fftx_error__, start_clock, stop_clock, mpi_gatherv, mpi_barrier