fft_dlay_set – FFTXlib
fft_dlay_set Subroutine
Source File
Variables
npp n3 nsp np nq i is iss i1 i2 m1 m2 n1 n2 ip ncpx nppx sm
All Procedures
allowed bw_tg_cft3_scatter bw_tg_cft3_xy bw_tg_cft3_z cfft3d cfft3d cfft3d cfft3d cfft3d cfft3ds cfft3ds cfft3ds cfft3ds cfft3ds cft_1z cft_1z cft_1z cft_1z cft_1z cft_2xy cft_2xy cft_2xy cft_2xy cft_2xy cft_b cft_b_omp cft_b_omp_init cgather_sym cgather_sym_many cscatter_sym_many fft_box_allocate fft_box_deallocate fft_box_set fft_dlay_allocate fft_dlay_deallocate fft_dlay_scalar fft_dlay_set fft_scatter fftx_error__ fw_tg_cft3_scatter fw_tg_cft3_xy fw_tg_cft3_z fwfft fwfft_x gather_complex_grid gather_grid gather_real_grid good_fft_dimension good_fft_order invfft invfft_b invfft_x pack_group_sticks pstickset pstickset_custom scatter_complex_grid scatter_grid scatter_real_grid sticks_countg sticks_deallocate sticks_dist sticks_maps sticks_maps_scalar sticks_ordered_dist sticks_pairup sticks_sort task_groups_init task_groups_init_first tg_cft3s tg_cgather tg_gather unpack_group_sticks
public subroutine fft_dlay_set(desc, tk, nst, nr1, nr2, nr3, nr1x, nr2x, nr3x, ub, lb, idx, in1, in2, ncp, ncpw, ngp, ngpw, st, stw)
Arguments
Type Intent Optional Attributes Name
type(fft_dlay_descriptor) :: desc
logical, intent(in) :: tk
integer, intent(in) :: nst
integer, intent(in) :: nr1
integer, intent(in) :: nr2
integer, intent(in) :: nr3
integer, intent(in) :: nr1x
integer, intent(in) :: nr2x
integer, intent(in) :: nr3x
integer, intent(in) :: ub(3)
integer, intent(in) :: lb(3)
integer, intent(in) :: idx(:)
integer, intent(in) :: in1(:)
integer, intent(in) :: in2(:)
integer, intent(in) :: ncp(:)
integer, intent(in) :: ncpw(:)
integer, intent(in) :: ngp(:)
integer, intent(in) :: ngpw(:)
integer, intent(in) :: st(lb(1):ub(1),lb(2):ub(2))
integer, intent(in) :: stw(lb(1):ub(1),lb(2):ub(2))
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: npp(desc%nproc)
integer, public :: n3(desc%nproc)
integer, public :: nsp(desc%nproc)
integer, public :: np
integer, public :: nq
integer, public :: i
integer, public :: is
integer, public :: iss
integer, public :: i1
integer, public :: i2
integer, public :: m1
integer, public :: m2
integer, public :: n1
integer, public :: n2
integer, public :: ip
integer, public :: ncpx
integer, public :: nppx
integer, public :: sm
Call graph
fft_dlay_set calls fftx_error__
pstickset calls fft_dlay_set
pstickset_custom calls fft_dlay_set