fft_scatter – FFTXlib
fft_scatter Subroutine
Source File
Variables
dest from k offset proc ierr me nprocp gproc gcomm i kdest kfrom me_p nppx mc j npp nnp ii it ip ioff sendsiz ncpx ipp nblk nsiz use_tg_
All Procedures
allowed bw_tg_cft3_scatter bw_tg_cft3_xy bw_tg_cft3_z cfft3d cfft3d cfft3d cfft3d cfft3d cfft3ds cfft3ds cfft3ds cfft3ds cfft3ds cft_1z cft_1z cft_1z cft_1z cft_1z cft_2xy cft_2xy cft_2xy cft_2xy cft_2xy cft_b cft_b_omp cft_b_omp_init cgather_sym cgather_sym_many cscatter_sym_many fft_box_allocate fft_box_deallocate fft_box_set fft_dlay_allocate fft_dlay_deallocate fft_dlay_scalar fft_dlay_set fft_scatter fftx_error__ fw_tg_cft3_scatter fw_tg_cft3_xy fw_tg_cft3_z fwfft fwfft_x gather_complex_grid gather_grid gather_real_grid good_fft_dimension good_fft_order invfft invfft_b invfft_x pack_group_sticks pstickset pstickset_custom scatter_complex_grid scatter_grid scatter_real_grid sticks_countg sticks_deallocate sticks_dist sticks_maps sticks_maps_scalar sticks_ordered_dist sticks_pairup sticks_sort task_groups_init task_groups_init_first tg_cft3s tg_cgather tg_gather unpack_group_sticks
public subroutine fft_scatter(dfft, f_in, nr3x, nxx_, f_aux, ncp_, npp_, isgn, use_tg)
Arguments
Type Intent Optional Attributes Name
type(fft_dlay_descriptor), intent(in) :: dfft
complex(kind=DP), intent(inout) :: f_in(nxx_)
integer, intent(in) :: nr3x
integer, intent(in) :: nxx_
complex(kind=DP), intent(inout) :: f_aux(nxx_)
integer, intent(in) :: ncp_(:)
integer, intent(in) :: npp_(:)
integer, intent(in) :: isgn
logical, intent(in), optional :: use_tg
Description
f_in = 0.0_DP
f_in = 0.0_DP
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: dest
integer, public :: from
integer, public :: k
integer, public :: offset
integer, public :: proc
integer, public :: ierr
integer, public :: me
integer, public :: nprocp
integer, public :: gproc
integer, public :: gcomm
integer, public :: i
integer, public :: kdest
integer, public :: kfrom
integer, public :: me_p
integer, public :: nppx
integer, public :: mc
integer, public :: j
integer, public :: npp
integer, public :: nnp
integer, public :: ii
integer, public :: it
integer, public :: ip
integer, public :: ioff
integer, public :: sendsiz
integer, public :: ncpx
integer, public :: ipp
integer, public :: nblk
integer, public :: nsiz
logical, public :: use_tg_
Call graph
fft_scatter calls fftx_error__, start_clock, stop_clock, mpi_alltoall
bw_tg_cft3_scatter calls fft_scatter
fw_tg_cft3_scatter calls fft_scatter
tg_cft3s calls fw_scatter, bw_scatter
invfft_x calls tg_cft3s
fwfft_x calls tg_cft3s