fwfft_x – FFTXlib
fwfft_x Subroutine
Source File
Variables
DP
All Procedures
allowed bw_tg_cft3_scatter bw_tg_cft3_xy bw_tg_cft3_z cfft3d cfft3d cfft3d cfft3d cfft3d cfft3ds cfft3ds cfft3ds cfft3ds cfft3ds cft_1z cft_1z cft_1z cft_1z cft_1z cft_2xy cft_2xy cft_2xy cft_2xy cft_2xy cft_b cft_b_omp cft_b_omp_init cgather_sym cgather_sym_many cscatter_sym_many fft_box_allocate fft_box_deallocate fft_box_set fft_dlay_allocate fft_dlay_deallocate fft_dlay_scalar fft_dlay_set fft_scatter fftx_error__ fw_tg_cft3_scatter fw_tg_cft3_xy fw_tg_cft3_z fwfft fwfft_x gather_complex_grid gather_grid gather_real_grid good_fft_dimension good_fft_order invfft invfft_b invfft_x pack_group_sticks pstickset pstickset_custom scatter_complex_grid scatter_grid scatter_real_grid sticks_countg sticks_deallocate sticks_dist sticks_maps sticks_maps_scalar sticks_ordered_dist sticks_pairup sticks_sort task_groups_init task_groups_init_first tg_cft3s tg_cgather tg_gather unpack_group_sticks
subroutine fwfft_x(grid_type, f, dfft)
Uses:
fft_scalar
fft_parallel
fft_types
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: grid_type
complex(kind=DP) :: f(:)
type(fft_dlay_descriptor), intent(in) :: dfft
Calls
Variables
Type Visibility Attributes Name Initial
integer, public, parameter :: DP = selected_real_kind(14,200)
Call graph
fwfft_x calls cfft3d, tg_cft3s, cfft3ds, stop_clock, fftx_error__, start_clock
cfft3d calls dfticomputeforward, lookup, dfticomputebackward, check_dims, init_dfti
tg_cft3s calls fftx_error__, cft_2xy, unpack_group_sticks, cft_1z, bw_scatter, fw_scatter, pack_group_sticks
cfft3ds calls cfft3d
cft_2xy calls stop_clock, fftx_error__, start_clock, dfticomputeforward, dfticomputebackward, init_dfti, lookup
unpack_group_sticks calls stop_clock, fftx_error__, start_clock, mpi_alltoallv
cft_1z calls stop_clock, fftx_error__, start_clock, dfticomputeforward, dfticomputebackward, check_dims, lookup, init_dfti
pack_group_sticks calls stop_clock, fftx_error__, start_clock, mpi_alltoallv
fft_scatter calls stop_clock, fftx_error__, start_clock, mpi_alltoall