pstickset – FFTXlib
pstickset Subroutine
Source File
Variables
tk ub lb stw nstpw sstpw nstw nstpwx st nstp sstp nst nstpx sts nstps sstps nsts ist ip ngm_ ngs_ idx
All Procedures
allowed bw_tg_cft3_scatter bw_tg_cft3_xy bw_tg_cft3_z cfft3d cfft3d cfft3d cfft3d cfft3d cfft3ds cfft3ds cfft3ds cfft3ds cfft3ds cft_1z cft_1z cft_1z cft_1z cft_1z cft_2xy cft_2xy cft_2xy cft_2xy cft_2xy cft_b cft_b_omp cft_b_omp_init cgather_sym cgather_sym_many cscatter_sym_many fft_box_allocate fft_box_deallocate fft_box_set fft_dlay_allocate fft_dlay_deallocate fft_dlay_scalar fft_dlay_set fft_scatter fftx_error__ fw_tg_cft3_scatter fw_tg_cft3_xy fw_tg_cft3_z fwfft fwfft_x gather_complex_grid gather_grid gather_real_grid good_fft_dimension good_fft_order invfft invfft_b invfft_x pack_group_sticks pstickset pstickset_custom scatter_complex_grid scatter_grid scatter_real_grid sticks_countg sticks_deallocate sticks_dist sticks_maps sticks_maps_scalar sticks_ordered_dist sticks_pairup sticks_sort task_groups_init task_groups_init_first tg_cft3s tg_cgather tg_gather unpack_group_sticks
public subroutine pstickset(gamma_only, bg, gcut, gkcut, gcuts, dfftp, dffts, ngw, ngm, ngs, mype, root, nproc, comm, nogrp_, ionode, stdout, dfft3d)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: gamma_only
real(kind=DP), intent(in) :: bg(3,3)
real(kind=DP), intent(in) :: gcut
real(kind=DP), intent(in) :: gkcut
real(kind=DP), intent(in) :: gcuts
type(fft_dlay_descriptor), intent(inout) :: dfftp
type(fft_dlay_descriptor), intent(inout) :: dffts
integer, intent(out) :: ngw
integer, intent(out) :: ngm
integer, intent(out) :: ngs
integer, intent(in) :: mype
integer, intent(in) :: root
integer, intent(in) :: nproc
integer, intent(in) :: comm
integer, intent(in) :: nogrp_
logical, intent(in) :: ionode
integer, intent(in) :: stdout
type(fft_dlay_descriptor), intent(inout), optional :: dfft3d
Calls
Variables
Type Visibility Attributes Name Initial
logical, public :: tk
integer, public :: ub(3)
integer, public :: lb(3)
integer, public, ALLOCATABLE :: stw(:,:)
integer, public, ALLOCATABLE :: nstpw(:)
integer, public, ALLOCATABLE :: sstpw(:)
integer, public :: nstw
integer, public :: nstpwx
integer, public, ALLOCATABLE :: st(:,:)
integer, public, ALLOCATABLE :: nstp(:)
integer, public, ALLOCATABLE :: sstp(:)
integer, public :: nst
integer, public :: nstpx
integer, public, ALLOCATABLE :: sts(:,:)
integer, public, ALLOCATABLE :: nstps(:)
integer, public, ALLOCATABLE :: sstps(:)
integer, public :: nsts
integer, public, ALLOCATABLE :: ist(:,:)
integer, public :: ip
integer, public :: ngm_
integer, public :: ngs_
integer, public, ALLOCATABLE :: idx(:)
Call graph
pstickset calls fft_dlay_set, fft_dlay_scalar, sticks_dist, task_groups_init, fft_dlay_allocate, sticks_pairup, fftx_error__, sticks_sort, sticks_countg, sticks_maps, sticks_maps_scalar
fft_dlay_set calls fftx_error__
fft_dlay_scalar calls fftx_error__
task_groups_init calls fftx_error__, task_groups_init_first, mpi_allgather
fft_dlay_allocate calls fftx_error__
sticks_sort calls hpsort
sticks_countg calls fftx_error__
sticks_maps calls mpi_allreduce
task_groups_init_first calls fftx_error__, mpi_comm_size, mpi_comm_split, mpi_comm_rank