sticks_countg – FFTXlib
sticks_countg Subroutine
Source File
Variables
j1 j2 i1 i2 nct min_size
All Procedures
allowed bw_tg_cft3_scatter bw_tg_cft3_xy bw_tg_cft3_z cfft3d cfft3d cfft3d cfft3d cfft3d cfft3ds cfft3ds cfft3ds cfft3ds cfft3ds cft_1z cft_1z cft_1z cft_1z cft_1z cft_2xy cft_2xy cft_2xy cft_2xy cft_2xy cft_b cft_b_omp cft_b_omp_init cgather_sym cgather_sym_many cscatter_sym_many fft_box_allocate fft_box_deallocate fft_box_set fft_dlay_allocate fft_dlay_deallocate fft_dlay_scalar fft_dlay_set fft_scatter fftx_error__ fw_tg_cft3_scatter fw_tg_cft3_xy fw_tg_cft3_z fwfft fwfft_x gather_complex_grid gather_grid gather_real_grid good_fft_dimension good_fft_order invfft invfft_b invfft_x pack_group_sticks pstickset pstickset_custom scatter_complex_grid scatter_grid scatter_real_grid sticks_countg sticks_deallocate sticks_dist sticks_maps sticks_maps_scalar sticks_ordered_dist sticks_pairup sticks_sort task_groups_init task_groups_init_first tg_cft3s tg_cgather tg_gather unpack_group_sticks
public subroutine sticks_countg(tk, ub, lb, st, stw, sts, in1, in2, ngc, ngcw, ngcs)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: tk
integer, intent(in) :: ub(:)
integer, intent(in) :: lb(:)
integer, intent(in) :: st(lb(1):ub(1),lb(2):ub(2))
integer, intent(in) :: stw(lb(1):ub(1),lb(2):ub(2))
integer, intent(in) :: sts(lb(1):ub(1),lb(2):ub(2))
integer, intent(out) :: in1(:)
integer, intent(out) :: in2(:)
integer, intent(out) :: ngc(:)
integer, intent(out) :: ngcw(:)
integer, intent(out) :: ngcs(:)
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: j1
integer, public :: j2
integer, public :: i1
integer, public :: i2
integer, public :: nct
integer, public :: min_size
Call graph
sticks_countg calls fftx_error__
pstickset calls sticks_countg
pstickset_custom calls sticks_countg