task_groups_init – FFTXlib
task_groups_init Subroutine
Source File
Variables
stdout I IERR num_planes num_sticks nnrsx_vec pgroup strd
All Procedures
allowed bw_tg_cft3_scatter bw_tg_cft3_xy bw_tg_cft3_z cfft3d cfft3d cfft3d cfft3d cfft3d cfft3ds cfft3ds cfft3ds cfft3ds cfft3ds cft_1z cft_1z cft_1z cft_1z cft_1z cft_2xy cft_2xy cft_2xy cft_2xy cft_2xy cft_b cft_b_omp cft_b_omp_init cgather_sym cgather_sym_many cscatter_sym_many fft_box_allocate fft_box_deallocate fft_box_set fft_dlay_allocate fft_dlay_deallocate fft_dlay_scalar fft_dlay_set fft_scatter fftx_error__ fw_tg_cft3_scatter fw_tg_cft3_xy fw_tg_cft3_z fwfft fwfft_x gather_complex_grid gather_grid gather_real_grid good_fft_dimension good_fft_order invfft invfft_b invfft_x pack_group_sticks pstickset pstickset_custom scatter_complex_grid scatter_grid scatter_real_grid sticks_countg sticks_deallocate sticks_dist sticks_maps sticks_maps_scalar sticks_ordered_dist sticks_pairup sticks_sort task_groups_init task_groups_init_first tg_cft3s tg_cgather tg_gather unpack_group_sticks
private subroutine task_groups_init(dffts)
Uses:
fft_types
Arguments
Type Intent Optional Attributes Name
type(fft_dlay_descriptor), intent(inout) :: dffts
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: stdout = 6
integer, public :: I
integer, public :: IERR
integer, public :: num_planes
integer, public :: num_sticks
integer, public :: nnrsx_vec(dffts%nproc)
integer, public :: pgroup(dffts%nproc)
integer, public :: strd
Call graph
task_groups_init calls fftx_error__, task_groups_init_first, mpi_allgather
task_groups_init_first calls fftx_error__, mpi_comm_size, mpi_comm_split, mpi_comm_rank
pstickset calls task_groups_init