tg_cft3s – FFTXlib
tg_cft3s Subroutine
Source File
Variables
me_p n1 n2 n3 nx1 nx2 nx3 yf aux planes use_tg
Subroutines
fw_scatter bw_scatter
All Procedures
allowed bw_tg_cft3_scatter bw_tg_cft3_xy bw_tg_cft3_z cfft3d cfft3d cfft3d cfft3d cfft3d cfft3ds cfft3ds cfft3ds cfft3ds cfft3ds cft_1z cft_1z cft_1z cft_1z cft_1z cft_2xy cft_2xy cft_2xy cft_2xy cft_2xy cft_b cft_b_omp cft_b_omp_init cgather_sym cgather_sym_many cscatter_sym_many fft_box_allocate fft_box_deallocate fft_box_set fft_dlay_allocate fft_dlay_deallocate fft_dlay_scalar fft_dlay_set fft_scatter fftx_error__ fw_tg_cft3_scatter fw_tg_cft3_xy fw_tg_cft3_z fwfft fwfft_x gather_complex_grid gather_grid gather_real_grid good_fft_dimension good_fft_order invfft invfft_b invfft_x pack_group_sticks pstickset pstickset_custom scatter_complex_grid scatter_grid scatter_real_grid sticks_countg sticks_deallocate sticks_dist sticks_maps sticks_maps_scalar sticks_ordered_dist sticks_pairup sticks_sort task_groups_init task_groups_init_first tg_cft3s tg_cgather tg_gather unpack_group_sticks
public subroutine tg_cft3s(f, dfft, isgn, use_task_groups)
Uses:
fft_scalar
scatter_mod
fft_types
Arguments
Type Intent Optional Attributes Name
complex(kind=DP), intent(inout) :: f(:)
type(fft_dlay_descriptor), intent(in) :: dfft
integer, intent(in) :: isgn
logical, intent(in), optional :: use_task_groups
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: me_p
integer, public :: n1
integer, public :: n2
integer, public :: n3
integer, public :: nx1
integer, public :: nx2
integer, public :: nx3
complex(kind=DP), public, ALLOCATABLE :: yf(:)
complex(kind=DP), public, ALLOCATABLE :: aux(:)
integer, public :: planes(dfft%nr1x)
logical, public :: use_tg
Subroutines
subroutine fw_scatter(iopt)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iopt
subroutine bw_scatter(iopt)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iopt
Call graph
tg_cft3s calls cft_2xy, unpack_group_sticks, fftx_error__, cft_1z, bw_scatter, fw_scatter, pack_group_sticks
cft_2xy calls fftx_error__, dfticomputebackward, init_dfti, stop_clock, lookup, start_clock, dfticomputeforward
unpack_group_sticks calls fftx_error__, stop_clock, start_clock, mpi_alltoallv
cft_1z calls fftx_error__, dfticomputebackward, stop_clock, start_clock, dfticomputeforward, check_dims, lookup, init_dfti
pack_group_sticks calls fftx_error__, stop_clock, start_clock, mpi_alltoallv
fft_scatter calls fftx_error__, stop_clock, start_clock, mpi_alltoall
invfft_x calls tg_cft3s
fwfft_x calls tg_cft3s