#!/bin/sh

###############################################################################
##
##  HIGH VERBOSITY EXAMPLE
##
###############################################################################

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use pw.x and phcg.x to calculate the normal"
$ECHO "modes of a molecule (SiH4) at Gamma. "
$ECHO

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials

BIN_LIST="pw.x phcg.x "
PSEUDO_LIST="Si.pz-vbc.UPF H.pz-vbc.UPF C.pz-rrkjus.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE \
                http://www.quantum-espresso.org/pseudo/1.3/UPF/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
PHCG_COMMAND="$PARA_PREFIX $BIN_DIR/phcg.x $PARA_POSTFIX"
DYNMAT_COMMAND=" $BIN_DIR/dynmat.x"
$ECHO
$ECHO "  running pw.x     as: $PW_COMMAND"
$ECHO "  running phcg.x   as: $PHCG_COMMAND"
$ECHO "  running dynmat.x as: $DYNMAT_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"

# self-consistent calculation
cat > sih4.scf.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>


<input calculation="scf" prefix="sih4" title="Test Silane SiH4 gamma only">

	<cell type="qecell">
		<qecell ibrav="2" alat="12.0">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="2">
		<specie name="Si">
			<property name="mass">
				<real>28.086</real>
			</property>
			<property name="pseudofile">
				<string>Si.pz-vbc.UPF</string>
			</property>
		</specie>
		<specie name="H">
			<property name="mass">
				<real>1.008</real>
			</property>
			<property name="pseudofile">
				<string>H.pz-vbc.UPF</string>
			</property>
		</specie>
	</atomic_species>

	<atomic_list units="alat" nat="5" >
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.000000000   0.000000000   0.000000000
				</real>
			</position>
		</atom>	
		<atom name="H">
			<position>
				<real rank="1" n1="3">
					0.128530744   0.128530744   0.128530744
				</real>
			</position>
		</atom>	
		<atom name="H">
			<position>
				<real rank="1" n1="3">
					-0.128530744  -0.128530744   0.128530744
				</real>
			</position>
		</atom>	
		<atom name="H">
			<position>
				<real rank="1" n1="3">
					-0.128530744   0.128530744  -0.128530744
				</real>
			</position>
		</atom>	
		<atom name="H">
			<position>
				<real rank="1" n1="3">
					0.128530744  -0.128530744  -0.128530744
				</real>
			</position>
		</atom>						
	</atomic_list>	
	
	
	<field name="InputOutput">

		<parameter name="pseudo_dir">
			<string>
				$PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
				$TMP_DIR/
			</string>
		</parameter>
		
		<parameter name="tstress">
			<logical>
				true
			</logical>
		</parameter>	
		
		<parameter name="tprnfor">
			<logical>
				true
			</logical>
		</parameter>			
					
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				16.0
			</real>
		</parameter>
		
		<parameter name="mixing_mode">
			<string>
				plain
			</string>
		</parameter>
		
		<parameter name="mixing_beta">
			<real>
				0.7
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.0d-8
			</real>
		</parameter>
		
	</field>
	
	<k_points type="gamma">	
	</k_points>
</input>
EOF
$ECHO "  running the scf calculation for SiH4...\c"
$PW_COMMAND < sih4.scf.xml > sih4.scf.out
check_failure $?
$ECHO " done"

# normal mode calculation for SiH4
cat > sih4.nm.in << EOF
normal modes for sih4
 &inputph
  tr2_ph=1.0d-14,
  prefix='sih4',
  amass(1)=28.086,
  amass(2)=1.008,
  outdir='$TMP_DIR/',
  epsil=.true.,
  trans=.true., asr=.true.
  raman=.false.
  fildyn='sih4.dyn'
 /
 0.0 0.0 0.0
EOF
$ECHO "  running normal mode calculation for SiH4...\c"
$PHCG_COMMAND < sih4.nm.in > sih4.nm.out
check_failure $?
$ECHO " done"

# IR cross sections  for SiH4
cat > sih4.dyn.in << EOF
 &input fildyn='sih4.dyn', asr='zero-dim' /
EOF

$ECHO "  running IR cross section calculation for SiH4...\c"
$DYNMAT_COMMAND < sih4.dyn.in > sih4.dyn.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR: done"
