#!/bin/bash

LD1=../../bin/ld1.x
workd=./results/

mkdir -p $workd

(
echo "Today is: $(date)"
echo
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo "!!!                          Doing tests for Oxygen                          !!!"
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo

prefix[0]=O_LDA
prefix[1]=O_PBE_NLCC
dft[0]=LDA
dft[1]=PBE
nlcc[0]=.false.
nlcc[1]=.true.

for i in 0 1; do

echo "Generating pseudo ${dft[$i]} for O with nlcc=${nlcc[$i]} ..."
file=$workd/${prefix[$i]}.gen
cat <<EOF > $file.in
 &input
        title='O',
        zed=8.0,
        rel=0,
        beta=0.5,
        iswitch=3,
        dft='${dft[$i]}',
        prefix='$workd/o_${dft[$i]}'
        nld=0
 /
4
1S  1  0  2.0  1
2S  2  0  2.0  1
2P  2  1  4.0  1
3D  3  2 -1.0  1
 &inputp
   pseudotype=3,
   nlcc=${nlcc[$i]}, rcore=0.50
   lloc=2,
   file_pseudopw='$workd/O${dft[$i]}.RRKJ3.UPF',
   zval=6.d0,
   lpaw=.true.
 /
5
2S  2  0  2.00  0.00  1.40  1.70
2S  2  0  0.00  0.05  1.40  1.70
2P  2  1  4.00  0.00  1.40  1.70
2P  2  1  0.00  0.05  1.40  1.70
3D  3  2 -2.00  0.15  1.40  1.40
 &test
  nconf=1,
 / 
2
2S  1  0  2.00  0.00  1.40  1.70  1
2P  2  1  4.00  0.00  1.40  1.70  1
EOF
$LD1 < $file.in > $file.out
echo "Pseudopotential generated in the (1s2) 2s2 2p4 configuration"
echo "  Pseudo energy = $(awk '/Etotps/{printf "%11.6f\n", $3}' $file.out ) Ryd"
echo
echo "Testing pseudo ${dft[$i]} for O with nlcc=${nlcc[$i]} ..."
file=$workd/${prefix[$i]}.test
cat << EOF > $file.in
 &input
        title='O',
        zed=8.0,
        rel=0,
        beta=0.5,
        iswitch=2,
        dft='${dft[$i]}',
        prefix='$workd/o_${dft[$i]}'
        nld=0
 /
4
1S  1  0  2.0  1
2S  2  0  2.0  1
2P  2  1  4.0  1
3D  3  2 -1.0  1
 &test
  file_pseudo='$workd/O${dft[$i]}.RRKJ3.UPF',
  nconf=3,
 / 
2
2S  1  0  2.00  0.00  1.40  1.60  1
2P  2  1  4.00  0.00  1.40  1.60  1
2
2S  1  0  0.00  0.00  1.40  1.60  1
2P  2  1  6.00  0.00  1.40  1.60  1
2
2S  1  0  0.00  0.00  1.40  1.60  1
2P  2  1  4.00  0.00  1.40  1.60  1
EOF
$LD1 < $file.in > $file.out
echo "Pseudopotential generated in the (1s2) 2s2 2p4 configuration"
echo "  Pseudo energy = $(awk '/Etotps/{printf "%11.6f\n", $3}' $file.out | awk '(NR==1)' ) Ryd"
echo "Pseudopotential tested in the (1s2) 2s0 2p6 configuration"
echo "  Pseudo energy = $(awk '/Etotps/{printf "%11.6f\n", $3}' $file.out | awk '(NR==2)' ) Ryd"
echo "  Error         = $(awk '/Delta E=/{printf "%11.6f\n", $7}' $file.out | awk '(NR==2)' ) Ryd"
echo "Pseudopotential tested in the (1s2) 2s0 2p4 configuration"
echo "  Pseudo energy = $(awk '/Etotps/{printf "%11.6f\n", $3}' $file.out | awk '(NR==3)' ) Ryd"
echo "  Error         = $(awk '/Delta E=/{printf "%11.6f\n", $7}' $file.out | awk '(NR==3)' ) Ryd"
echo
echo "Testing pseudo ${dft[$i]} for O with nlcc=${nlcc[$i]} ..."
file=$workd/${prefix[$i]}.spin
cat << EOF > $file.in
 &input
        title='O',
        zed=8.0,
        lsd=1,
        rel=0,
        beta=0.5,
        iswitch=2,
        dft='${dft[$i]}',
        prefix='$workd/o_${dft[$i]}'
        nld=0
 /
8
1S  1  0  1.0  1
2S  2  0  1.0  1
2P  2  1  2.0  1
3D  3  2 -1.0  1
1S  1  0  1.0  2
2S  2  0  1.0  2
2P  2  1  2.0  2
3D  3  2 -1.0  2
 &test
  file_pseudo='$workd/O${dft[$i]}.RRKJ3.UPF',
  nconf=3,
 / 
4
2S  1  0  1.00  0.00  1.40  1.60  1
2P  2  1  2.00  0.00  1.40  1.60  1
2S  1  0  1.00  0.00  1.40  1.60  2
2P  2  1  2.00  0.00  1.40  1.60  2
4
2S  1  0  0.00  0.00  1.40  1.60  1
2P  2  1  3.00  0.00  1.40  1.60  1
2S  1  0  0.00  0.00  1.40  1.60  2
2P  2  1  3.00  0.00  1.40  1.60  2
4
2S  1  0  1.00  0.00  1.40  1.60  1
2P  2  1  1.00  0.00  1.40  1.60  1
2S  1  0  1.00  0.00  1.40  1.60  2
2P  2  1  3.00  0.00  1.40  1.60  2
EOF
$LD1 < $file.in > $file.out
echo "Pseudopotential generated in the (1s2) 2s2 2p4 configuration"
echo "  Pseudo energy = $(awk '/Etotps/{printf "%11.6f\n", $3}' $file.out | awk '(NR==1)' ) Ryd"
echo "Pseudopotential tested in the (1s2) 2s0 2s0 2p3 2p3 configuration"
echo "  Pseudo energy = $(awk '/Etotps/{printf "%11.6f\n", $3}' $file.out | awk '(NR==2)' ) Ryd"
echo "  Error         = $(awk '/Delta E=/{printf "%11.6f\n", $7}' $file.out | awk '(NR==2)' ) Ryd"
echo "Pseudopotential tested in the (1s2) 2s1 2s1 2p1 2p3 configuration"
echo "  Pseudo energy = $(awk '/Etotps/{printf "%11.6f\n", $3}' $file.out | awk '(NR==3)' ) Ryd"
echo "  Error         = $(awk '/Delta E=/{printf "%11.6f\n", $7}' $file.out | awk '(NR==3)' ) Ryd"
echo
echo
done

) > $workd/run-test.out

echo
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo "Now doing: \"diff reference/run-test.out $workd/run-test.out\""
echo
diff reference/run-test.out $workd/run-test.out
