import sys
dtype=['complex','real','integer']
stype=['real','real','integer']
stype_conv=['real','real','int']
sk=['dp','dp','i4b']
kind=['4','8']
mold=[0,1,2,3,4,5,6,7]


molds={}
for r in mold:
    m='('
    for i in range(0,r-1):
       m+=':,'
    m+=':)'
    if r==0: m=''
    molds[r]=m


proc=f'''
!WARNING: THIS FILE IS AUTOMATICALLY GENERATED BY {sys.argv[0]}
interface checkpoint
'''
subs=f'''!WARNING: THIS FILE IS AUTOMATICALLY GENERATED BY {sys.argv[0]}
'''

for t,s, s_k, s_c in zip(dtype,stype,sk,stype_conv):
    for k in kind:
        for r in mold:
            array = False if r==0 else True
            sum_='sum' if array else ''
            maxval_='maxval' if array else ""
            proc+=f'''module procedure checkpoint_{t}_{k}_{r}
'''
            subs+=f'''
subroutine checkpoint_{t}_{k}_{r}( arr, file, line)
{t}(kind={k}), intent(in) :: arr{molds[r]}
character(len=64) :: fname
character(*) file
integer line
integer :: iun,iun2,i,j
{t}(kind={k}), allocatable :: arr_{molds[r]}
CHARACTER(LEN=6), EXTERNAL :: int_to_char
INTEGER, EXTERNAL :: find_free_unit
{s}(kind={s_k}) :: sumt
if ( .not. checkpoint_debug_active) then
    return
end if

counter = counter + 1
fname = trim(fname_prefix)// int_to_char(counter)
iun = find_free_unit()
WRITE(*,*) msg_pref, file,':', line
if (testing) then
    if (ionode) &
     WRITE(*,*) msg_pref,'reading {t}(kind={k}){molds[r]}', shape(arr), ' from file '//trim(fname)
    open (iun, file=trim(fname),form='UNFORMATTED',access='STREAM',action='read')
    allocate(arr_, mold=arr)
    read (iun) arr_
    close(iun)
    sumt = {s_c}({sum_}(abs(arr_-arr)),kind={s_k})
    call mp_sum(sumt,communicator) 
    write(*,*) msg_pref,'sum of absolute value of difference = ',sumt
    if (sumt > 1.0e-4) then
       if (ionode) &
          WRITE(*,*) msg_pref,'difference is too big: saving the computed data to '//trim(fname)//'.err'
       iun2 = find_free_unit()
       open (iun, file=trim(fname)//'.err',form='UNFORMATTED',access='STREAM',action='write')
       write (iun) arr
       close(iun)
    endif
    sumt = {s_c}({maxval_}(abs(arr_-arr)),kind={s_k})
    call mp_max(sumt,communicator) 
    write(*,*) msg_pref,'max of absolute value of difference = ',sumt
    sumt = {s_c}({sum_}(abs(arr)),kind={s_k})
    call mp_sum(sumt,communicator) 
    write(*,*) msg_pref,'sum of absolute value of computed array = ',sumt
    deallocate(arr_)
else ! write the file
    if (ionode) &
     WRITE(*,*) msg_pref,'writing {t}(kind={k}){molds[r]}', shape(arr), ' on file '//trim(fname)
    open (iun, file=trim(fname),form='UNFORMATTED',access='STREAM',action='write')
    write (iun) arr
    close(iun)
end if
end subroutine
'''
proc+='''end interface
'''

with open('debug_proc.fh','w') as o:
    o.write(proc)
with open('debug_sub.fh','w') as o:
    o.write(subs)

