#!/bin/bash

work=./results
reference=./reference
ld1dir=../../atomic/

mkdir $work
rm -f $work/*

if test -e difference ; then /bin/rm difference > /dev/null ; fi
touch difference

for atom in ar f he cu cu1 h pt mg u u1 w ne_oep c_oep ; do
    $ld1dir/ld1.x < $atom.in > $work/$atom.out
    echo "diff -wib ./results/$atom.out ./reference/$atom.out" >> difference
    diff -wib $work/$atom.out $reference/ >> difference
done

/bin/rm ld1.wfc
