#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use pw.x to relax a 2-atom cell of As"
$ECHO "at 2 different pressures, 0 kbar and 500 kbar. At those pressures"
$ECHO "As relax to different structures, sc and A7."

# set the needed environment variables 
. ../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x"
PSEUDO_LIST="As.gon.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then 
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x as: $PW_COMMAND"
$ECHO



    # clean TMP_DIR
    $ECHO "  cleaning $TMP_DIR...\c"
    rm -rf $TMP_DIR/*
    $ECHO " done"

    # VCS-MD calculation
    cat > As.vcs00.in << EOF
 &CONTROL
   calculation =   "vc-relax"   ,
   restart_mode = 'from_scratch' ,
   outdir='$TMP_DIR/' ,
   pseudo_dir = '$PSEUDO_DIR' ,
   disk_io = 'default' ,
   verbosity = 'default' ,
   tstress = .true. ,
   tprnfor = .true. ,
   nstep =  55  ,
               etot_conv_thr = 1.0E-5  ,
               forc_conv_thr = 1.0D-4 ,
                      iprint = 1 ,
                 max_seconds = 6000 ,
                          dt = 150 ,
 /
 &SYSTEM
   ibrav = 0 ,
   A = 3.70971016 ,
   B = 3.70971016 ,
   C = 3.70971016 ,
   cosAB = 0.49517470 ,
   cosAC = 0.49517470 ,
   cosBC = 0.49517470 ,
                         nat  =  2 , 
                        ntyp  =  1 , 
                     ecutwfc  =  25.0 ,
                     ecutrho  =  100.0 , 
                        nbnd  =  9 , 
                       nelec  =  10 , 
                 occupations  =  'smearing' ,
                    smearing  =  'mp' ,
                     degauss  =  0.005 ,
                       nspin  =  1 , 
                  lda_plus_u  =  .false. , 
 /
 &ELECTRONS
            electron_maxstep  =  70  , 
                    conv_thr  =  1.0d-7  , 
             diagonalization   =   'david'   ,  
 /
 &IONS
 /
 &CELL
   cell_dynamics = 'damp-w' ,
   press = 0.00 ,
   wmass =  0.00700000  ,
 /
CELL_PARAMETERS cubic 
    0.58012956  0.00000000  0.81452422
   -0.29006459  0.50240689  0.81452422
   -0.29006459 -0.50240689  0.81452422
ATOMIC_SPECIES
   As   74.90000  As.gon.UPF
ATOMIC_POSITIONS crystal 
As    0.290010       0.290010       0.290010
As   -0.290010      -0.290010      -0.290010
K_POINTS automatic 
  4 4 4   1 1 1 
EOF


    $ECHO "  running the VCS-MD calculation for As at 0 kbar. \c"
    $PW_COMMAND < As.vcs00.in > As.vcs00.out
    $ECHO " done"

    # VCS-MD calculation
    cat > As.vcs500.in << EOF
 &CONTROL
   calculation =   "vc-relax"   ,
   restart_mode = 'from_scratch' ,
   outdir='$TMP_DIR/' , 
   pseudo_dir = '$PSEUDO_DIR' ,
   disk_io = 'default' ,
   verbosity = 'default' ,
   tstress = .true. ,
   tprnfor = .true. ,
   nstep =  55  ,
               etot_conv_thr = 1.0E-5  ,
               forc_conv_thr = 1.0D-4 ,
                      iprint = 1 ,
                 max_seconds = 6000 ,
                          dt = 150 ,
 /
 &SYSTEM
   ibrav = 0 ,
   A = 3.70971016 ,
   B = 3.70971016 ,
   C = 3.70971016 ,
   cosAB = 0.49517470 ,
   cosAC = 0.49517470 ,
   cosBC = 0.49517470 ,
                         nat  =  2 , 
                        ntyp  =  1 , 
                     ecutwfc  =  25.0 ,
                     ecutrho  =  100.0 , 
                        nbnd  =  9 , 
                       nelec  =  10 , 
                 occupations  =  'smearing' ,
                    smearing  =  'mp' ,
                     degauss  =  0.005 ,
                       nspin  =  1 , 
                  lda_plus_u  =  .false. , 
 /
 &ELECTRONS
            electron_maxstep  =  70  , 
                    conv_thr  =  1.0d-7  , 
             diagonalization   =   'david'   ,  
 /
 &IONS
 /
 &CELL
   cell_dynamics = 'damp-w' ,
   press = 500.00 ,
   wmass =  0.00700000  ,
 /
CELL_PARAMETERS cubic 
    0.58012956  0.00000000  0.81452422
   -0.29006459  0.50240689  0.81452422
   -0.29006459 -0.50240689  0.81452422
ATOMIC_SPECIES
   As   74.90000  As.gon.UPF
ATOMIC_POSITIONS crystal 
As    0.290010       0.290010       0.290010
As   -0.290010      -0.290010      -0.290010
K_POINTS automatic 
  4 4 4   1 1 1 
EOF


    $ECHO "  running the VCS-MD calculation for As at 500 kbar. \c"
    $PW_COMMAND < As.vcs500.in > As.vcs500.out
    $ECHO " done"



$ECHO
$ECHO "$EXAMPLE_DIR : done"
