#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use pw.x to perform electronic structure"
$ECHO "calculations in the presence of a finite homogeneous electric field "
$ECHO "described through the modern theory of the polarization. The example"
$ECHO "shows how to calculate high-frequency dielectric constant of bulk Silicon"

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x"
PSEUDO_LIST="Si.pbe-rrkj.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE \
                http://www.quantum-espresso.org/pseudo/1.3/UPF/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"


# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x as: $PW_COMMAND"
$ECHO


# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"


cat > si.scf.efield.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>


<input calculation="scf" prefix="silicon">

	<cell type="qecell">
		<qecell ibrav="1" alat="10.18">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="1">
		<specie name="Si">
			<property name="mass">
				<real>28.086</real>
			</property>
			<property name="pseudofile">
				<string>Si.pbe-rrkj.UPF</string>
			</property>
		</specie>
	</atomic_species>

	<atomic_list units="alat" nat="8" >
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					-0.125 -0.125 -0.125
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.375  0.375 -0.125
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.375 -0.125  0.375
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					-0.125  0.375  0.375
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.125  0.125  0.125
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.625  0.625  0.125
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.625  0.125  0.625
				</real>
			</position>
		</atom>		
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.125  0.625  0.625
				</real>
			</position>
		</atom>	
	</atomic_list>		
	
	
	<field name="InputOutput">

		<parameter name="restart_mode">
			<string>
				from_scratch
			</string>
		</parameter>

		<parameter name="pseudo_dir">
			<string>
				$PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
				$TMP_DIR/
			</string>
		</parameter>
		
		<parameter name="startingwfc">
			<string>
				random
			</string>
		</parameter>
		
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				20.0
			</real>
		</parameter>
		
		<parameter name="diagonalization">
			<string>
				david
			</string>
		</parameter>
		
		<parameter name="mixing_beta">
			<real>
				0.5
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.0d-8
			</real>
		</parameter>
		
	</field>
	
	<field name="Fields">

		<parameter name="lelfield">
			<logical>
				true
			</logical>
		</parameter>
		
		<parameter name="nberrycyc">
			<integer>
				1
			</integer>
		</parameter>
		
		<parameter name="efield_cart">
			<real rank="1" n1="3">
				0.d0 0.d0 0.d0
			</real>
		</parameter>
		
	</field>
	
	<k_points type="automatic">
		<mesh>
			<integer rank="1" n1="6">
				3 3 7 0 0 0
			</integer>
		</mesh> 
	</k_points>
</input>
EOF
$ECHO "  running the PW calculation for bulk Si E_field=0.0  a.u. ...\c"
$PW_COMMAND < si.scf.efield.xml > si.scf.efield.out
check_failure $?
$ECHO " done"

cat > si.scf.efield2.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>


<input calculation="scf" prefix="silicon">

	<cell type="qecell">
		<qecell ibrav="1" alat="10.18">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="1">
		<specie name="Si">
			<property name="mass">
				<real>28.086</real>
			</property>
			<property name="pseudofile">
				<string>Si.pbe-rrkj.UPF</string>
			</property>
		</specie>
	</atomic_species>

	<atomic_list units="alat" nat="8" >
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					-0.125 -0.125 -0.125
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.375  0.375 -0.125
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.375 -0.125  0.375
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					-0.125  0.375  0.375
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					 0.125  0.125  0.125
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.625  0.625  0.125
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.625  0.125  0.625
				</real>
			</position>
		</atom>		
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.125  0.625  0.625
				</real>
			</position>
		</atom>	
	</atomic_list>		
	
	
	<field name="InputOutput">

		<parameter name="restart_mode">
			<string>
				from_scratch
			</string>
		</parameter>

		<parameter name="pseudo_dir">
			<string>
				$PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
				$TMP_DIR/
			</string>
		</parameter>
		
		<parameter name="startingwfc">
			<string>
				random
			</string>
		</parameter>
		
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				20.0
			</real>
		</parameter>
		
		<parameter name="diagonalization">
			<string>
				david
			</string>
		</parameter>
		
		<parameter name="mixing_beta">
			<real>
				0.5
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.0d-8
			</real>
		</parameter>
		
	</field>
	
	<field name="Fields">

		<parameter name="lelfield">
			<logical>
				true
			</logical>
		</parameter>
		
		<parameter name="nberrycyc">
			<integer>
				3
			</integer>
		</parameter>
		
		<parameter name="efield_cart">
			<real rank="1" n1="3">
				0.d0 0.d0 0.001d0
			</real>
		</parameter>
		
	</field>
	
	<k_points type="automatic">
		<mesh>
			<integer rank="1" n1="6">
				3 3 7 0 0 0
			</integer>
		</mesh> 
	</k_points>
</input>
EOF
$ECHO "  running the PW calculation for bulk Si E_field=0.001  a.u. ...\c"
$PW_COMMAND < si.scf.efield2.xml > si.scf.efield2.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR : done"
