#!/bin/sh

###############################################################################
##
##  HIGH VERBOSITY EXAMPLE
##
###############################################################################

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

# function to test the exit status of a job
. ../check_failure.sh

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use pw.x and phcg.x to calculate the normal"
$ECHO "modes of a molecule (SiH4) at Gamma. It shows also the use of ph.x"
$ECHO "for molecules (CH4) at Gamma."
$ECHO

# set the needed environment variables
. ../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x phcg.x ph.x"
PSEUDO_LIST="Si.pz-vbc.UPF H.pz-vbc.UPF C.pz-rrkjus.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE \
                http://www.quantum-espresso.org/pseudo/1.3/UPF/$FILE 2> /dev/null 
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
PH_COMMAND="$PARA_PREFIX $BIN_DIR/ph.x $PARA_POSTFIX"
PHCG_COMMAND="$PARA_PREFIX $BIN_DIR/phcg.x $PARA_POSTFIX"
DYNMAT_COMMAND=" $BIN_DIR/dynmat.x"
$ECHO
$ECHO "  running pw.x     as: $PW_COMMAND"
$ECHO "  running ph.x     as: $PH_COMMAND"
$ECHO "  running phcg.x   as: $PHCG_COMMAND"
$ECHO "  running dynmat.x as: $DYNMAT_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"

# self-consistent calculation
cat > sih4.scf.in << EOF
 &control
    calculation='scf'
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
    title='Test Silane SiH4 gamma only'
    prefix='sih4'
    tprnfor=.true., tstress=.true.
 /
 &system
    ibrav=2, celldm(1) =12.0, nat=5, ntyp= 2,
    ecutwfc =16.0
 /
  &electrons
    mixing_mode='plain'
    mixing_beta = 0.7,
    conv_thr =  1.0d-8
 /
ATOMIC_SPECIES
 Si 28.086 Si.pz-vbc.UPF
  H  1.008  H.pz-vbc.UPF
ATOMIC_POSITIONS (alat)
 Si   0.000000000   0.000000000   0.000000000
  H   0.128530744   0.128530744   0.128530744
  H  -0.128530744  -0.128530744   0.128530744
  H  -0.128530744   0.128530744  -0.128530744
  H   0.128530744  -0.128530744  -0.128530744
K_POINTS (gamma)
EOF
$ECHO "  running the scf calculation for SiH4...\c"
$PW_COMMAND < sih4.scf.in > sih4.scf.out
check_failure $?
$ECHO " done"

# normal mode calculation for SiH4
cat > sih4.nm.in << EOF
normal modes for sih4
 &inputph
  tr2_ph=1.0d-14,
  prefix='sih4',
  amass(1)=28.086,
  amass(2)=1.008,
  outdir='$TMP_DIR/',
  epsil=.true.,
  trans=.true., asr=.true.
  raman=.false.
  fildyn='sih4.dyn'
 /
 0.0 0.0 0.0
EOF
$ECHO "  running normal mode calculation for SiH4...\c"
$PHCG_COMMAND < sih4.nm.in > sih4.nm.out
check_failure $?
$ECHO " done"

# IR cross sections  for SiH4
cat > sih4.dyn.in << EOF
 &input fildyn='sih4.dyn', asr='zero-dim' /
EOF

$ECHO "  running IR cross section calculation for SiH4...\c"
$DYNMAT_COMMAND < sih4.dyn.in > sih4.dyn.out
check_failure $?
$ECHO " done"

# Self consistent calculation for CH4
cat > ch4.scf.in << EOF
ch4
ch4 molecule in a cubic box
 &control
    calculation = 'scf',
    restart_mode='from_scratch',
    prefix='ch4',
    tprnfor = .true.,
    pseudo_dir = '$PSEUDO_DIR',
    outdir='$TMP_DIR'
 /
 &system
    ibrav=  1,
    celldm(1) =15.0,
    nat=5,
    ntyp= 2,
    ecutwfc =25.0,
    ecutrho =100.0,
 /
 &electrons
    mixing_beta = 0.5,
    conv_thr =  1.0d-8
 /
ATOMIC_SPECIES
 H  1.0   H.pz-vbc.UPF
 C  12.0  C.pz-rrkjus.UPF
ATOMIC_POSITIONS
H        0.080728893   0.080728893   0.080728893
H       -0.080728893  -0.080728893   0.080728893
H        0.080728893  -0.080728893  -0.080728893
H       -0.080728893   0.080728893  -0.080728893
C        0.000000000   0.000000000   0.000000000
K_POINTS
1
0.0 0.0 0.0 1.0
EOF
$ECHO "  running the scf calculation for CH4...\c"
$PW_COMMAND < ch4.scf.in > ch4.scf.out
check_failure $?
$ECHO " done"

# normal mode calculation for CH4
cat > ch4.nm.in << EOF
vibrations of ch4
 &inputph
  tr2_ph=4.0d-17,
  prefix='ch4',
  outdir='$TMP_DIR',
  amass(1)=1.d0,
  amass(2)=12.d0,
  asr=.true.,
  zue=.true.,
  epsil=.true.,
  trans=.true.,
  fildyn='ch4.dyn.xml',
 /
0.0 0.0 0.0
EOF
$ECHO "  running normal mode calculation for CH4...\c"
$PH_COMMAND < ch4.nm.in > ch4.nm.out
check_failure $?
$ECHO " done"

# IR cross sections  for CH4
cat > ch4.dyn.in << EOF
 &input fildyn='ch4.dyn.xml', asr='zero-dim' /
EOF

$ECHO "  running IR cross section calculation for CH4...\c"
$DYNMAT_COMMAND < ch4.dyn.in > ch4.dyn.out
check_failure $?
$ECHO " done"


$ECHO
$ECHO "$EXAMPLE_DIR: done"
