#!/bin/sh
#
# 30 min
# contributed by Y. Kanai (ykanai@princeton.edu)
# reference: JCP 121, 3359 (2004)
#
# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use cp.x to calculate minimum energy path"
$ECHO "(MEP) using string method (smd)."
$ECHO
$ECHO " This script runs a sequence of CP-SMD calculations to get the MEP"
$ECHO " 1. Minimize electronic degrees of freedom"
$ECHO " 2. Locate the MEP" 

# set the needed environment variables
. ../environment_variables

# required executables and pseudopotentials
BIN_LIST="cp.x"
PSEUDO_LIST="H_US.van"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
     fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
CP_COMMAND="$PARA_PREFIX $BIN_DIR/cp.x $PARA_POSTFIX"
$ECHO
$ECHO "  running cp.x as: $CP_COMMAND"
$ECHO

# clean TMP_DIR
if test "0$1" -le 1 ; then
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"
fi

# Now is ....
date

# run smd in one shot

cat > smd1.in << EOF
 &control
    restart_mode='from_scratch',
    calculation='smd',
    nstep=15, iprint=100, dt=10.d0,
    ndr=60, ndw=60,
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
 /
 &system
    ibrav = 1,
    celldm(1) = 10.d0, celldm(2) = 0.d0, celldm(3) = 0.d0,
    celldm(4) = 0.d0, celldm(5) = 0.d0, celldm(6) = 0.d0,
    nspin = 2, nelup = 2, neldw = 1,
    nat   = 3, nbnd  = 2, nelec  = 3, ntyp  = 1, ecutwfc  = 15.0d0,
    ecutrho = 100.0,
    nr1b= 15, nr2b = 15, nr3b = 15,
    xc_type = 'PBE'
 /
 &electrons
    emass = 500.d0,
    emass_cutoff = 2.5d0,
    electron_damping = 1.0,
    orthogonalization = 'ortho',
    electron_dynamics = 'damp',
 /
 &ions
    ion_dynamics = 'none',
    ion_damping = 1.0,
    num_of_images = 9,
    ion_radius(1) = 0.8,
    smd_smcp = .true.,
    smd_smlm = .false.,
    smd_smopt = .false.,
    smd_linr = .true.,
    smd_polm = .false.,
    smd_kwnp = 2,
    smd_stcd = .false.,
    smd_lmfreq  = 1,
    smd_tol = 1.d-5,
    smd_maxlm = 100,
    smd_codf = 50,
    smd_forf = 50,
    smd_smwf = 1, 
    smd_ene_ini = -1.63640, 
    smd_ene_fin = -1.63640  
 /
ATOMIC_SPECIES
H   1.0  H_US.van  1
ATOMIC_POSITIONS ( bohr )
first_image
H  0.000000 0.000000 0.000000
H  0.000000 0.000000 1.456300
H  0.000000 0.000000 4.500000
last_image
H  0.000000 0.000000 0.000000
H  0.000000 0.000000 3.043700
H  0.000000 0.000000 4.500000
EOF
$ECHO "  running first SMD calculation ...\c"
if test "0$2" -ge 1 ; then
 if test "0$1" -le 1 ; then
    $CP_COMMAND < smd1.in > smd1.out
    $ECHO " done"
 else
    $ECHO " skipped"
 fi
else
    $ECHO " skipped" # too big, don't run
fi

cat > smd2.in << EOF
 &control
    restart_mode='reset_counters',
    calculation='smd',
    nstep=30, iprint=100, dt=10.d0,
    ndr=60, ndw=60,
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
 /
 &system
    ibrav = 1,
    celldm(1) = 10.d0, celldm(2) = 0.d0, celldm(3) = 0.d0,
    celldm(4) = 0.d0, celldm(5) = 0.d0, celldm(6) = 0.d0,
    nspin = 2, nelup = 2, neldw = 1,
    nat   = 3, nbnd  = 2, nelec  = 3, ntyp  = 1, ecutwfc  = 15.0d0,
    ecutrho = 100.0,
    nr1b= 15, nr2b = 15, nr3b = 15,
    xc_type = 'PBE'
 /
 &electrons
    emass = 500.d0,
    emass_cutoff = 2.5d0,
    electron_damping = 0.5,
    orthogonalization = 'ortho',
    electron_dynamics = 'damp',
 /
 &ions
    ion_dynamics = 'none',
    ion_damping = 1.0,
    num_of_images = 9,
    ion_radius(1) = 0.8,
    smd_smcp = .true.,
    smd_smlm = .false.,
    smd_smopt = .false.,
    smd_linr = .true.,
    smd_polm = .false.,
    smd_kwnp = 2,
    smd_stcd = .false.,
    smd_lmfreq  = 1,
    smd_tol = 1.d-5,
    smd_maxlm = 100,
    smd_codf = 50,
    smd_forf = 50,
    smd_smwf = 1,
    smd_ene_ini = -1.63640,
    smd_ene_fin = -1.63640
 /
ATOMIC_SPECIES
H   1.0  H_US.van  1
ATOMIC_POSITIONS ( bohr )
first_image
H  0.000000 0.000000 0.000000
H  0.000000 0.000000 1.456300
H  0.000000 0.000000 4.500000
last_image
H  0.000000 0.000000 0.000000
H  0.000000 0.000000 3.043700
H  0.000000 0.000000 4.500000
EOF
$ECHO "  running second SMD calculation ...\c"
if test "0$2" -ge 2 ; then
 if test "0$1" -le 2 ; then
    $CP_COMMAND < smd2.in > smd2.out
    $ECHO " done"
 else
    $ECHO " skipped"
 fi
else
    $ECHO " skipped" # too big, don't run
fi

cat > smd3.in << EOF
 &control
    restart_mode='restart',
    calculation='smd',
    nstep=60, iprint=100, dt=10.d0,
    ndr=60, ndw=60,
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
 /
 &system
    ibrav = 1,
    celldm(1) = 10.d0, celldm(2) = 0.d0, celldm(3) = 0.d0,
    celldm(4) = 0.d0, celldm(5) = 0.d0, celldm(6) = 0.d0,
    nspin = 2, nelup = 2, neldw = 1,
    nat   = 3, nbnd  = 2, nelec  = 3, ntyp  = 1, ecutwfc  = 15.0d0,
    ecutrho = 100.0,
    nr1b= 15, nr2b = 15, nr3b = 15,
    xc_type = 'PBE'
 /
 &electrons
    emass = 500.d0,
    emass_cutoff = 2.5d0,
    electron_damping = 0.1,
    orthogonalization = 'ortho',
    electron_dynamics = 'damp',
 /
 &ions
    ion_dynamics = 'none',
    ion_damping = 1.0,
    num_of_images = 9,
    ion_radius(1) = 0.8,
    smd_smcp = .true.,
    smd_smlm = .false.,
    smd_smopt = .false.,
    smd_linr = .true.,
    smd_polm = .false.,
    smd_kwnp = 2,
    smd_stcd = .false.,
    smd_lmfreq  = 1,
    smd_tol = 1.d-5,
    smd_maxlm = 100,
    smd_codf = 50,
    smd_forf = 50,
    smd_smwf = 1,
    smd_ene_ini = -1.63640,
    smd_ene_fin = -1.63640
 /
ATOMIC_SPECIES
H   1.0  H_US.van  1
ATOMIC_POSITIONS ( bohr )
first_image
H  0.000000 0.000000 0.000000
H  0.000000 0.000000 1.456300
H  0.000000 0.000000 4.500000
last_image
H  0.000000 0.000000 0.000000
H  0.000000 0.000000 3.043700
H  0.000000 0.000000 4.500000
EOF
$ECHO "  running third SMD calculation ...\c"
if test "0$2" -ge 3 ; then
 if test "0$1" -le 3 ; then
    $CP_COMMAND < smd3.in > smd3.out
    $ECHO " done"
 else
    $ECHO " skipped"
 fi
else
    $ECHO " skipped" # too big, don't run
fi

cat > smd4.in << EOF
 &control
    restart_mode='restart',
    calculation='smd',
    nstep=60, iprint=100, dt=10.d0,
    ndr=60, ndw=60,
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
 /
&system
    ibrav = 1,
    celldm(1) = 10.d0, celldm(2) = 0.d0, celldm(3) = 0.d0,
    celldm(4) = 0.d0, celldm(5) = 0.d0, celldm(6) = 0.d0,
    nspin = 2, nelup = 2, neldw = 1,
    nat   = 3, nbnd  = 2, nelec  = 3, ntyp  = 1, ecutwfc  = 15.0d0,
    ecutrho = 100.0,
    nr1b= 15, nr2b = 15, nr3b = 15,
    xc_type = 'PBE'
 /
 &electrons
    emass = 500.d0,
    emass_cutoff = 2.5d0,
    electron_damping = 0.01,
    orthogonalization = 'ortho',
    electron_dynamics = 'damp',
 /
 &ions
    ion_dynamics = 'none',
    ion_damping = 1.0,
    num_of_images = 9,
    ion_radius(1) = 0.8,
    smd_smcp = .true.,
    smd_smlm = .false.,
    smd_smopt = .false.,
    smd_linr = .true.,
    smd_polm = .false.,
    smd_kwnp = 2,
    smd_stcd = .false.,
    smd_lmfreq  = 1,
    smd_tol = 1.d-5,
    smd_maxlm = 100,
    smd_codf = 50,
    smd_forf = 50,
    smd_smwf = 1,
    smd_ene_ini = -1.63640,
    smd_ene_fin = -1.63640
 /
ATOMIC_SPECIES
H   1.0  H_US.van  1
ATOMIC_POSITIONS ( bohr )
first_image
H  0.000000 0.000000 0.000000
H  0.000000 0.000000 1.456300
H  0.000000 0.000000 4.500000
last_image
H  0.000000 0.000000 0.000000
H  0.000000 0.000000 3.043700
H  0.000000 0.000000 4.500000
EOF
$ECHO "  running fourth SMD calculation ...\c"
if test "0$2" -ge 4 ; then
 if test "0$1" -le 4 ; then
    $CP_COMMAND < smd4.in > smd4.out
    $ECHO " done"
 else
    $ECHO " skipped"
 fi
else
    $ECHO " skipped" # too big, don't run
fi

cat > smd5.in << EOF
 &control
    restart_mode='reset_counters',
    calculation='smd',
    nstep=50, iprint=100, dt=10.d0,
    ndr=60, ndw=70,
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
 /
 &system
    ibrav = 1,
    celldm(1) = 10.d0, celldm(2) = 0.d0, celldm(3) = 0.d0,
    celldm(4) = 0.d0, celldm(5) = 0.d0, celldm(6) = 0.d0,
    nspin = 2, nelup = 2, neldw = 1,
    nat   = 3, nbnd  = 2, nelec  = 3, ntyp  = 1, ecutwfc  = 15.0d0,
    ecutrho = 100.0,
    nr1b= 15, nr2b = 15, nr3b = 15,
    xc_type = 'PBE'
 /
 &electrons
    emass = 500.d0,
    emass_cutoff = 2.5d0,
    electron_damping = 1.0,
    orthogonalization = 'ortho',
    electron_dynamics = 'damp',
 /
 &ions
    ion_dynamics = 'damp',
    ion_damping = 0.8,
    num_of_images = 9,
    ion_radius(1) = 0.8,
    smd_smcp = .false.,
    smd_smlm = .true.,
    smd_smopt = .false.,
    smd_linr = .true.,
    smd_polm = .false.,
    smd_kwnp = 2,
    smd_stcd = .false.,
    smd_lmfreq  = 1,
    smd_tol = 1.d-5,
    smd_maxlm = 100,
    smd_codf = 50,
    smd_forf = 50,
    smd_smwf = 1,
    smd_ene_ini = -1.63640,
    smd_ene_fin = -1.63640
 /
ATOMIC_SPECIES
H   1.0  H_US.van  1
ATOMIC_POSITIONS ( bohr )
first_image
H  0.000000 0.000000 0.000000
H  0.000000 0.000000 1.456300
H  0.000000 0.000000 4.500000
last_image
H  0.000000 0.000000 0.000000
H  0.000000 0.000000 3.043700
H  0.000000 0.000000 4.500000
EOF
$ECHO "  running fifth SMD calculation ...\c"
if test "0$2" -ge 5 ; then
 if test "0$1" -le 5 ; then
    $CP_COMMAND < smd5.in > smd5.out
    $ECHO " done"
 else
    $ECHO " skipped"
 fi
else
    $ECHO " skipped" # too big, don't run
fi

cat > smd6.in << EOF
 &control
    restart_mode='restart',
    calculation='smd',
    nstep=50, iprint=100, dt=10.d0,
    ndr=70, ndw=70,
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
 /
 &system
    ibrav = 1,
    celldm(1) = 10.d0, celldm(2) = 0.d0, celldm(3) = 0.d0,
    celldm(4) = 0.d0, celldm(5) = 0.d0, celldm(6) = 0.d0,
    nspin = 2, nelup = 2, neldw = 1,
    nat   = 3, nbnd  = 2, nelec  = 3, ntyp  = 1, ecutwfc  = 15.0d0,
    ecutrho = 100.0,
    nr1b= 15, nr2b = 15, nr3b = 15,
    xc_type = 'PBE'
 /
 &electrons
    emass = 500.d0,
    emass_cutoff = 2.5d0,
    electron_damping = 0.5,
    orthogonalization = 'ortho',
    electron_dynamics = 'damp',
 /
 &ions
    ion_dynamics = 'damp',
    ion_damping = 0.2,
    num_of_images = 9,
    ion_radius(1) = 0.8,
    smd_smcp = .false.,
    smd_smlm = .true.,
    smd_smopt = .false.,
    smd_linr = .true.,
    smd_polm = .false.,
    smd_kwnp = 2,
    smd_stcd = .false.,
    smd_lmfreq  = 1,
    smd_tol = 1.d-5,
    smd_maxlm = 100,
    smd_codf = 50,
    smd_forf = 50,
    smd_smwf = 1,
    smd_ene_ini = -1.63640,
    smd_ene_fin = -1.63640
 /
ATOMIC_SPECIES
H   1.0  H_US.van  1
ATOMIC_POSITIONS ( bohr )
first_image
H  0.000000 0.000000 0.000000
H  0.000000 0.000000 1.456300
H  0.000000 0.000000 4.500000
last_image
H  0.000000 0.000000 0.000000
H  0.000000 0.000000 3.043700
H  0.000000 0.000000 4.500000
EOF
$ECHO "  running sixth SMD calculation ...\c"
if test "0$2" -ge 6 ; then
 if test "0$1" -le 6 ; then
    $CP_COMMAND < smd6.in > smd6.out
    $ECHO " done"
 else
    $ECHO " skipped"
 fi
else
    $ECHO " skipped" # too big, don't run
fi

cat > smd7.in << EOF
 &control
    restart_mode='restart',
    calculation='smd',
    nstep=100, iprint=100, dt=10.d0,
    ndr=70, ndw=70,
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
 /
 &system
    ibrav = 1,
    celldm(1) = 10.d0, celldm(2) = 0.d0, celldm(3) = 0.d0,
    celldm(4) = 0.d0, celldm(5) = 0.d0, celldm(6) = 0.d0,
    nspin = 2, nelup = 2, neldw = 1,
    nat   = 3, nbnd  = 2, nelec  = 3, ntyp  = 1, ecutwfc  = 15.0d0,
    ecutrho = 100.0,
    nr1b= 15, nr2b = 15, nr3b = 15,
    xc_type = 'PBE'
 /
 &electrons
    emass = 500.d0,
    emass_cutoff = 2.5d0,
    electron_damping = 0.1,
    orthogonalization = 'ortho',
    electron_dynamics = 'damp',
 /
 &ions
    ion_dynamics = 'damp',
    ion_damping = 0.05,
    num_of_images = 9,
    ion_radius(1) = 0.8,
    smd_smcp = .false.,
    smd_smlm = .true.,
    smd_smopt = .false.,
    smd_linr = .true.,
    smd_polm = .false.,
    smd_kwnp = 2,
    smd_stcd = .false.,
    smd_lmfreq  = 1,
    smd_tol = 1.d-5,
    smd_maxlm = 100,
    smd_codf = 50,
    smd_forf = 50,
    smd_smwf = 1,
    smd_ene_ini = -1.63640,
    smd_ene_fin = -1.63640
 /
ATOMIC_SPECIES
H   1.0  H_US.van  1
ATOMIC_POSITIONS ( bohr )
first_image
H  0.000000 0.000000 0.000000
H  0.000000 0.000000 1.456300
H  0.000000 0.000000 4.500000
last_image
H  0.000000 0.000000 0.000000
H  0.000000 0.000000 3.043700
H  0.000000 0.000000 4.500000
EOF
$ECHO "  running seventh SMD calculation ...\c"
if test "0$2" -ge 7 ; then
 if test "0$1" -le 7 ; then
    $CP_COMMAND < smd7.in > smd7.out
    $ECHO " done"
 else
    $ECHO " skipped"
 fi
else
    $ECHO " skipped" # too big, don't run
fi

# clean TMP_DIR
#$ECHO "  cleaning $TMP_DIR...\c"
#rm -rf $TMP_DIR/*
#$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR : done"

# Now is ....
date
