#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use cp.x to calculate Wannier functions and"
$ECHO "to perform dynamics with an external electric field."

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="cp.x"
PSEUDO_LIST="H.blyp-vbc.UPF O.blyp-mt.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE \
                http://www.quantum-espresso.org/pseudo/1.3/UPF/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
CP_COMMAND="$PARA_PREFIX $BIN_DIR/cp.x $PARA_POSTFIX"
$ECHO
$ECHO "  running cp.x as: $CP_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"

cat > h2o.scf.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>


<input calculation="scf" prefix="h2o_mol">

	<cell type="qecell">
		<qecell ibrav="1" alat="16.0">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="2">
		<specie name="O">
			<property name="mass">
				<real>8.0</real>
			</property>
			<property name="pseudofile">
				<string>O.blyp-mt.UPF</string>
			</property>
		</specie>
		<specie name="H">
			<property name="mass">
				<real>1.0</real>
			</property>
			<property name="pseudofile">
				<string>H.blyp-vbc.UPF</string>
			</property>
		</specie>
	</atomic_species>

	<atomic_list units="bohr" nat="3" >
		<atom name="O">
			<position>
				<real rank="1" n1="3">
					5.093750000000  5.093750000000  5.093750000000
				</real>
			</position>
		</atom>	
		<atom name="H">
			<position>
				<real rank="1" n1="3">
					3.648508572765  5.093750000000  3.967985471743
				</real>
			</position>
		</atom>		
		<atom name="H">
			<position>
				<real rank="1" n1="3">
					6.538991443058  5.093750000000  3.967985459417
				</real>
			</position>
		</atom>			
	</atomic_list>		
	
	
	<field name="InputOutput">

		<parameter name="pseudo_dir">
			<string>
				$PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
				$TMP_DIR/
			</string>
		</parameter>
		
		<parameter name="restart_mode">
			<string>
				from_scratch
			</string>
		</parameter>
		
		<parameter name="iprint">
			<integer>
				1
			</integer>
		</parameter>
		
		<parameter name="tstress">
			<logical>
				FALSE
			</logical>
		</parameter>
		
		<parameter name="tprnfor">
			<logical>
				TRUE
			</logical>
		</parameter>
	
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				70.0
			</real>
		</parameter>
		
		<parameter name="etot_conv_thr">
			<real>
				1.0d-6
			</real>
		</parameter>
		
		<parameter name="forc_conv_thr">
			<real>
				1.0d-2
			</real>
		</parameter>
		
		<parameter name="ecutrho">
			<real>
				280.0
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.d-8
			</real>
		</parameter>
		
	</field>
	
	<field name="Options">

		<parameter name="nbnd">
			<integer>
				4
			</integer>
		</parameter>
		
	</field>
	
	<field name="CP">
	
<!--nstep e dt esistono anche nel PW ma nn sapevo in che field metterli  -->
		<parameter name="nstep">
			<integer>
				1000
			</integer>
		</parameter>
		
		<parameter name="dt">
			<real>
				1.0d0
			</real>
		</parameter>
		
<!-- Da qui in poi esistono solo in CP-->
		
		<parameter name="saverho">
			<logical>
				TRUE
			</logical>
		</parameter>
		
		<parameter name="ndw">
			<integer>
				50
			</integer>
		</parameter>
		
		<parameter name="emass">
			<real>
				400.d0
			</real>
		</parameter>
		
		<parameter name="emass_cutoff">
			<real>
				3.d0
			</real>
		</parameter>
		
		<parameter name="ekin_conv_thr">
			<real>
				1.0d-8
			</real>
		</parameter>
		
		<parameter name="orthogonalization">
			<string>
				Gram-Schmidt
			</string>
		</parameter>
		
		<parameter name="tcg">
			<logical>
				TRUE
			</logical>
		</parameter>
		
		<parameter name="passop">
			<real>
				0.3
			</real>
		</parameter>
		
		<parameter name="maxiter">
			<integer>
				250
			</integer>
		</parameter>
			
	</field>
	
</input>
EOF

$ECHO "  running electronic minimization...\c"
$CP_COMMAND < h2o.scf.xml > h2o.scf.out
check_failure $?
$ECHO " done"

cat > h2o.wannier.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>


<input calculation="cp-wf" prefix="h2o_mol">

	<cell type="qecell">
		<qecell ibrav="1" alat="16.0">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="2">
		<specie name="O">
			<property name="mass">
				<real>8.0</real>
			</property>
			<property name="pseudofile">
				<string>O.blyp-mt.UPF</string>
			</property>
		</specie>
		<specie name="H">
			<property name="mass">
				<real>1.0</real>
			</property>
			<property name="pseudofile">
				<string>H.blyp-vbc.UPF</string>
			</property>
		</specie>
	</atomic_species>

	<atomic_list units="bohr" nat="3" >
		<atom name="O">
			<position>
				<real rank="1" n1="3">
					5.093750000000  5.093750000000  5.093750000000
				</real>
			</position>
		</atom>	
		<atom name="H">
			<position>
				<real rank="1" n1="3">
					3.648508572765  5.093750000000  3.967985471743
				</real>
			</position>
		</atom>		
		<atom name="H">
			<position>
				<real rank="1" n1="3">
					6.538991443058  5.093750000000  3.967985459417
				</real>
			</position>
		</atom>			
	</atomic_list>		
	
	
	<field name="InputOutput">

		<parameter name="pseudo_dir">
			<string>
				$PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
				$TMP_DIR/
			</string>
		</parameter>
		
		<parameter name="restart_mode">
			<string>
				restart
			</string>
		</parameter>
		
		<parameter name="iprint">
			<integer>
				1
			</integer>
		</parameter>
		
		<parameter name="tstress">
			<logical>
				FALSE
			</logical>
		</parameter>
		
		<parameter name="tprnfor">
			<logical>
				TRUE
			</logical>
		</parameter>
	
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				70.0
			</real>
		</parameter>
		
		<parameter name="etot_conv_thr">
			<real>
				1.0d-6
			</real>
		</parameter>
		
		<parameter name="forc_conv_thr">
			<real>
				1.0d-2
			</real>
		</parameter>
		
		<parameter name="ecutrho">
			<real>
				280.0
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.d-8
			</real>
		</parameter>
		
	</field>
	
	<field name="Options">

		<parameter name="nbnd">
			<integer>
				4
			</integer>
		</parameter>
		
	</field>
	
	<field name="CP">
	
<!--nstep, dt e ion_dynamics esistono anche nel PW ma nn sapevo in che field metterli  -->
		<parameter name="nstep">
			<integer>
				1000
			</integer>
		</parameter>
		
		<parameter name="dt">
			<real>
				1.0d0
			</real>
		</parameter>
		
		<parameter name="ion_dynamics">
			<string>
				none
			</string>
		</parameter>
		
<!-- Da qui in poi esistono solo in CP-->
		
		<parameter name="saverho">
			<logical>
				TRUE
			</logical>
		</parameter>
		
		<parameter name="ndr">
			<integer>
				50
			</integer>
		</parameter>
		
		<parameter name="ndw">
			<integer>
				51
			</integer>
		</parameter>
		
		<parameter name="emass">
			<real>
				400.d0
			</real>
		</parameter>
		
		<parameter name="emass_cutoff">
			<real>
				3.d0
			</real>
		</parameter>
		
		<parameter name="ekin_conv_thr">
			<real>
				1.0d-8
			</real>
		</parameter>
		
		<parameter name="nsteps">
			<integer>
				200
			</integer>
		</parameter>
		
		<parameter name="orthogonalization">
			<string>
				Gram-Schmidt
			</string>
		</parameter>
		
		<parameter name="tcg">
			<logical>
				TRUE
			</logical>
		</parameter>
		
		<parameter name="passop">
			<real>
				0.3
			</real>
		</parameter>
		
		<parameter name="maxiter">
			<integer>
				250
			</integer>
		</parameter>
		
		<parameter name="wfsd">
			<integer>
				3
			</integer>
		</parameter>
		
		<parameter name="calwf">
			<integer>
				4
			</integer>
		</parameter>
		
		<parameter name="nit">
			<integer>
				100
			</integer>
		</parameter>
		
		<parameter name="nsd">
			<integer>
				100
			</integer>
		</parameter>
		
		<parameter name="tolw">
			<real>
				1.0D-14
			</real>
		</parameter>
			
	</field>
	
</input>
EOF

$ECHO "  running Wannier function calculation...\c"
$CP_COMMAND < h2o.wannier.xml > h2o.wannier.out
check_failure $?
$ECHO " done"

$ECHO "">> h2o.wannier.out
$ECHO "  Wannier functions centers:">> h2o.wannier.out
tail -4 $TMP_DIR/h2o_mol.wfc  >> h2o.wannier.out
tail -4 fort.24  >> h2o.wannier.out
$ECHO
$ECHO "$EXAMPLE_DIR: done"
