#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This is a second example of how to use cp.x to calculate Wannier functions,"
$ECHO "using Jacobi Rotation as localization algorithm (courtesy of IRRMA Lausanne)."

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="cp.x"
PSEUDO_LIST="H.blyp-vbc.UPF O.blyp-mt.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null         
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
CP_COMMAND="$PARA_PREFIX $BIN_DIR/cp.x $PARA_POSTFIX"
$ECHO
$ECHO "  running cp.x as: $CP_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/cp*
$ECHO " done"

cat > h2o.scf.in << EOF
&control
    calculation = 'scf'
    restart_mode='from_scratch',
    prefix='h2o_mol',
    tstress = .false.
    tprnfor = .true.
    saverho = .true.
    pseudo_dir    = "$PSEUDO_DIR/",
    outdir        = "$TMP_DIR/",
    ndw=50
    nstep=1000
    iprint=1
    dt = 1.0d0
    ekin_conv_thr = 1.0d-8
    etot_conv_thr = 1.0d-6
    forc_conv_thr = 1.0d-2
 /
&system
    ibrav=  1, celldm(1)=16.0, nat=  3, ntyp= 2,
    ecutwfc = 70.0, ecutrho=280.0, nbnd=4,
 /
 &electrons
  emass = 400.d0,
  emass_cutoff = 3.d0,
  orthogonalization = 'Gram-Schmidt',
  tcg=.true.,
  passop=0.3,
  maxiter = 250,
  conv_thr=1.d-8
/
ATOMIC_SPECIES
O  8  O.blyp-mt.UPF
H  1  H.blyp-vbc.UPF
ATOMIC_POSITIONS {bohr}
O 5.093750000000        5.093750000000  5.093750000000
H 3.648508572765        5.093750000000  3.967985471743
H 6.538991443058        5.093750000000  3.967985459417
EOF

$ECHO "  running electronic minimization...\c"
$CP_COMMAND < h2o.scf.in > h2o.scf.out
check_failure $?
$ECHO " done"

cat > h2o.wannier.in << EOF
&control
    calculation = 'cp-wf'
    restart_mode='restart',
    prefix='h2o_mol',
    tstress = .false.
    tprnfor = .true.
    saverho = .true.
    pseudo_dir    = "$PSEUDO_DIR/",
    outdir        = "$TMP_DIR/",
    ndr=50
    ndw=51
    nstep=1000
    iprint=1
    dt = 1.0d0
    ekin_conv_thr = 1.0d-8
    etot_conv_thr = 1.0d-6
    forc_conv_thr = 1.0d-2
 /
&system
    ibrav=  1, celldm(1)=16.0, nat=  3, ntyp= 2,
    ecutwfc = 70.0, ecutrho=280.0, nbnd=4,
 /
 &electrons
  emass = 400.d0,
  emass_cutoff = 3.d0,
  orthogonalization = 'Gram-Schmidt',
  tcg=.true.,
  passop=0.3,
  maxiter = 250,
  conv_thr=1.d-8
/
&ions
    ion_dynamics = 'none'
/
&wannier
    wfsd = 3
    calwf = 4
    nit = 100
    nsd = 100
    nsteps = 200 
    tolw = 1.0D-14 
/
ATOMIC_SPECIES
O  8  O.blyp-mt.UPF
H  1  H.blyp-vbc.UPF
ATOMIC_POSITIONS {bohr}
O 5.093750000000        5.093750000000  5.093750000000
H 3.648508572765        5.093750000000  3.967985471743
H 6.538991443058        5.093750000000  3.967985459417
EOF

$ECHO "  running Wannier function calculation...\c"
$CP_COMMAND < h2o.wannier.in > h2o.wannier.out
check_failure $?
$ECHO " done"

$ECHO "">> h2o.wannier.out
$ECHO "  Wannier functions centers:">> h2o.wannier.out
tail -4 $TMP_DIR/h2o_mol.wfc  >> h2o.wannier.out
tail -4 fort.24  >> h2o.wannier.out
$ECHO
$ECHO "$EXAMPLE_DIR: done"
