#!/bin/sh

###############################################################################
##
##  HIGH VERBOSITY EXAMPLE
##
###############################################################################

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use pw.x, ph.x and d3.x to calculate the"
$ECHO "third-order expansion coefficients of the total energy of Si."

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x ph.x d3.x"
PSEUDO_LIST="Si.pz-vbc.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
PH_COMMAND="$PARA_PREFIX $BIN_DIR/ph.x $PARA_POSTFIX"
D3_COMMAND="$PARA_PREFIX $BIN_DIR/d3.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x as: $PW_COMMAND"
$ECHO "  running ph.x as: $PH_COMMAND"
$ECHO "  running d3.x as: $D3_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/silicon*
rm -rf $TMP_DIR/_ph0/silicon*
$ECHO " done"

# self-consistent calculation
cat > si.scf.in << EOF
 &control
    calculation = 'scf'
    restart_mode='from_scratch',
    prefix='silicon',
    tstress = .true.
    tprnfor = .true.
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
 /
 &system
    ibrav=  2, celldm(1) =10.20, nat=  2, ntyp= 1,
    ecutwfc =24.0,
 /
 &electrons
    mixing_beta = 0.7
    conv_thr =  1.0d-8
 /
ATOMIC_SPECIES
 Si  28.086  Si.pz-vbc.UPF
ATOMIC_POSITIONS
 Si 0.00 0.00 0.00
 Si 0.25 0.25 0.25
K_POINTS {automatic}
4 4 4  1 1 1
EOF
$ECHO "  running the scf calculation for Si...\c"
$PW_COMMAND < si.scf.in > si.scf.out
check_failure $?
$ECHO " done"

# calculation of the dynamical matrix at Gamma
cat > si.phG.in << EOF
phonons of Si at Gamma
 &inputph
  tr2_ph=1.0d-12,
  prefix='silicon',
  epsil=.false.,
  trans=.true.,
  zue=.false.,
  amass(1)=28.0855,
  amass(2)=28.0855,
  outdir='$TMP_DIR/',
  fildyn='si.dyn_G',
  fildrho='si.drho_G',
 /
0.0 0.0 0.0
EOF
$ECHO "  running the phonon calculation for Si at Gamma...\c"
$PH_COMMAND < si.phG.in > si.phG.out
check_failure $?
$ECHO " done"

# calculation of the anharmonic tensor at Gamma
cat > si.d3G.in << EOF
Anharm at Gamma
&inputph
   prefix = 'silicon',
   fildrho = 'si.drho_G',
   fild0rho = 'si.drho_G',
   amass(1) = 28.0855,
   outdir = '$TMP_DIR/',
   fildyn = 'si.anh_G',
 /
0.0 0.0 0.0
EOF
$ECHO "  running the calculation of D3(0,0,0)...\c"
$D3_COMMAND < si.d3G.in > si.d3G.out
check_failure $?
$ECHO " done"

# calculation of the dynamical matrix at the X-point
cat > si.phX.in << EOF
phonons of Si at the X-point
 &inputph
  tr2_ph=1.0d-12,
  prefix='silicon',
  trans=.true.,
  amass(1)=28.0855,
  outdir='$TMP_DIR/',
  fildyn='si.dyn_X',
  fildrho='si.drho_X',
 /
0.0 0.0 1.0
EOF
$ECHO "  running the phonon calculation for Si at X...\c"
$PH_COMMAND < si.phX.in > si.phX.out
check_failure $?
$ECHO " done"

# calculation of the anharmonic tensor at X
cat > si.d3X.in << EOF
Anharm at the X-point
&inputph
   prefix = 'silicon',
   fildrho = 'si.drho_X',
   fild0rho = 'si.drho_G',
   amass(1) = 28.0855,
   outdir = '$TMP_DIR/',
   fildyn = 'si.anh_X',
 /
0.0 0.0 1.0
EOF
$ECHO "  running the calculation of D3(0,X,-X)...\c"
$D3_COMMAND < si.d3X.in > si.d3X.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR: done"
