#!/bin/sh

###############################################################################
##
##  HIGH VERBOSITY EXAMPLE
##
###############################################################################

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example tests pw.x with PAW in the noncollinear, spin-orbit case."
$ECHO "It calculates the band structure of ferromagnetic bcc-Fe."
$ECHO

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x"
PSEUDO_LIST="Fe.rel-pbe-kjpaw.UPF Au.rel-pz-kjpaw.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE \
                http://www.quantum-espresso.org/pseudo/1.3/UPF/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x     as: $PW_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"

# self-consistent calculation for bcc-Fe with fully relativistic PAW-PP
cat > Fe.scf_pbe.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>


<input calculation="scf" prefix="Fe">

	<cell type="qecell">
		<qecell ibrav="3" alat="5.42">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="1">
		<specie name="Fe">
			<property name="mass">
				<real>0.0</real>
			</property>
			<property name="pseudofile">
				<string>Fe.rel-pbe-kjpaw.UPF</string>
			</property>
			<property name="starting_magnetization">
				<real>0.5</real>
			</property>			
		</specie>
	</atomic_species>

	<atomic_list units="alat" nat="1" >
		<atom name="Fe">
			<position>
				<real rank="1" n1="3">
					0.0000000   0.00000000   0.0  
				</real>
			</position>
		</atom>						
	</atomic_list>		
	
	
	<field name="InputOutput">

		<parameter name="pseudo_dir">
			<string>
			 $PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
			  $TMP_DIR/
			</string>
		</parameter>
	
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				45.0
			</real>
		</parameter>
		
		<parameter name="ecutrho">
			<real>
				300.0
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.0d-10
			</real>
		</parameter>
		
	</field>
	
	<field name="Options">

		<parameter name="occupations">
			<string>
				smearing
			</string>
		</parameter>
		
		<parameter name="smearing">
			<string>
				mp
			</string>
		</parameter>
		
		<parameter name="degauss">
			<real>
				0.04
			</real>
		</parameter>			
		
		<parameter name="noncolin">
			<logical>
				true
			</logical>
		</parameter>
		
		<parameter name="lspinorb">
			<logical>
				true
			</logical>
		</parameter>
		
	</field>	
	
	<k_points type="automatic">
		<mesh>
			<integer rank="1" n1="6">
				8 8 8 1 1 1 
			</integer>
		</mesh> 
	</k_points>
	
</input>
EOF
$ECHO "  running the scf calculation for Fe with PAW spin-orbit...\c"
$PW_COMMAND < Fe.scf_pbe.xml > Fe.scf_pbe.out
check_failure $?
$ECHO " done"

# self-consistent calculation for bcc-Fe with fully relativistic PAW-PP
cat > Fe.band_pbe.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>


<input calculation="bands" prefix="Fe">

	<cell type="qecell">
		<qecell ibrav="3" alat="5.42">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="1">
		<specie name="Fe">
			<property name="mass">
				<real>0.0</real>
			</property>
			<property name="pseudofile">
				<string>Fe.rel-pbe-kjpaw.UPF</string>
			</property>
			<property name="starting_magnetization">
				<real>0.5</real>
			</property>			
		</specie>
	</atomic_species>

	<atomic_list units="alat" nat="1" >
		<atom name="Fe">
			<position>
				<real rank="1" n1="3">
					0.0000000   0.00000000   0.0
				</real>
			</position>
		</atom>						
	</atomic_list>		
	
	
	<field name="InputOutput">

		<parameter name="pseudo_dir">
			<string>
			 $PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
			  $TMP_DIR/
			</string>
		</parameter>
	
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				45.0
			</real>
		</parameter>
		
		<parameter name="ecutrho">
			<real>
				300.0
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.0d-10
			</real>
		</parameter>
		
	</field>
	
	<field name="Options">

		<parameter name="occupations">
			<string>
				smearing
			</string>
		</parameter>
		
		<parameter name="smearing">
			<string>
				mp
			</string>
		</parameter>
		
		<parameter name="degauss">
			<real>
				0.04
			</real>
		</parameter>			
		
		<parameter name="noncolin">
			<logical>
				true
			</logical>
		</parameter>
		
		<parameter name="lspinorb">
			<logical>
				true
			</logical>
		</parameter>
		
	</field>	
	
	<k_points type="tpiba_b">
		<mesh npoints="3">
			<real rank="2" n1="4" n2="3">
				    1.0 0.0 0.0 40.0
				    0.0 0.0 0.0 40.0
				    0.0 0.0 1.0 1.0
			</real>
		</mesh> 
	</k_points>
</input>
EOF
$ECHO "  running the band calculation for Fe with PAW and spin-orbit...\c"
$PW_COMMAND < Fe.band_pbe.xml > Fe.band_pbe.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR: done"
