#!/bin/sh

###############################################################################
##
##  HIGH VERBOSITY EXAMPLE
##
###############################################################################

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example tests pw.x with PAW in the noncollinear, spin-orbit case."
$ECHO "It calculates the band structure of ferromagnetic bcc-Fe."
$ECHO

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x"
PSEUDO_LIST="Fe.rel-pbe-kjpaw.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x     as: $PW_COMMAND"
$ECHO

# self-consistent calculation for bcc-Fe with fully relativistic PAW-PP
cat > Fe.scf_pbe.in << EOF
 &control
    calculation = 'scf'
    prefix='Fe',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
 /
 &system    
    ibrav=  3, 
    celldm(1) =5.42, 
    nat=  1, 
    ntyp= 1,
    nr1=27,
    nr2=27,
    nr3=27,
    noncolin=.true.
    lspinorb=.true.
    starting_magnetization(1)=0.5,
    occupations='smearing',
    smearing='mp',
    degauss=0.04,
    ecutwfc =45.0, 
    ecutrho =300.0
 /
 &electrons
    conv_thr =  1.0d-10
 /
ATOMIC_SPECIES
Fe  0.0    Fe.rel-pbe-kjpaw.UPF
ATOMIC_POSITIONS
Fe  0.0000000   0.00000000   0.0  
K_POINTS AUTOMATIC
8 8 8 1 1 1 
EOF
$ECHO "  running the scf calculation for Fe with PAW spin-orbit...\c"
$PW_COMMAND < Fe.scf_pbe.in > Fe.scf_pbe.out
check_failure $?
$ECHO " done"

# self-consistent calculation for bcc-Fe with fully relativistic PAW-PP
cat > Fe.band_pbe.in << EOF
 &control
    calculation = 'bands'
    prefix='Fe',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
 /
 &system    
    ibrav=  3, 
    celldm(1) =5.42, 
    nat=  1, 
    ntyp= 1,
    nr1=27,
    nr2=27,
    nr3=27,
    noncolin=.true.
    lspinorb=.true.
    starting_magnetization(1)=0.5,
    occupations='smearing',
    smearing='mp',
    degauss=0.04,
    ecutwfc =45.0, 
    ecutrho =300.0
 /
 &electrons
    conv_thr =  1.0d-10
 /
ATOMIC_SPECIES
Fe  0.0    Fe.rel-pbe-kjpaw.UPF
ATOMIC_POSITIONS
Fe  0.0000000   0.00000000   0.0  
K_POINTS tpiba_b
3
1.0 0.0 0.0 40
0.0 0.0 0.0 40
0.0 0.0 1.0 1
EOF
$ECHO "  running the band calculation for Fe with PAW and spin-orbit...\c"
$PW_COMMAND < Fe.band_pbe.in > Fe.band_pbe.out
check_failure $?
$ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/Fe*
$ECHO " done"


$ECHO
$ECHO "$EXAMPLE_DIR: done"
