#!/bin/bash
#
#  The following PPs are not on the web and are not removed

tobesaved="HUSPBE.RRKJ3          \
	   O_US.van  H_US.van    \
	   Rh.pbe-rrkjus_lb.UPF  \
	   Rhs.pbe-rrkjus_lb.UPF \
	   Si.bhs	         \
	   Au.pz-rrkjus_aewfc.UPF\
	   C.UPF C_3.98148.UPF   \
	   pb_s.UPF              \
	   Si_r.upf              \
           C-q4.gth O-q6.gth H-q1.gth \
           B-PBE.upf N-PBE.upf Fe.lda-pseudoDojo.UPF Fe.pbe-nc.UPF "
#
# REASON:
# HUSPBE.RRKJ3, O_US.van, H_US.van, Si.bhs, C.UPF : old formats
# Au.pz-rrkjus_aewfc.UPF : contains all-electron wavefunctions
# Rh.pbe-rrkjus_lb.UPF, Rhs.pbe-rrkjus_lb.UPF : core-hole PPs
# C_3.98148.UPF : B-C VCA pseudopotential, for slightly B-doped C systems
# pb_s.UPF  Si_r.upf : fully relativistic
# C-q4.gth O-q6.gth H-q1.gth : GTH format 
# B-PBE.upf N-PBE.upf Fe.lda-pseudoDojo.UPF Fe.pbe-nc.UPF : unknown reasons

mkdir .save
mv $tobesaved .save
/bin/rm *.UPF *.upf >& /dev/null
mv .save/* .
rmdir .save


