#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use pw.x to perform molecular dynamics for"
$ECHO "2- and 8-atom cells of Si starting with compressed bonds along (111)."

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x"
PSEUDO_LIST="Si.pz-vbc.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE \
                http://www.quantum-espresso.org/pseudo/1.3/UPF/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x as: $PW_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"

# MD in a 2-atom cell
cat > si.md2.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>

<input calculation="md">

	<cell type="qecell">
		<qecell ibrav="2" alat="10.18">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="1">
		<specie name="Si">
			<property name="mass">
				<real>28.086</real>
			</property>
			<property name="pseudofile">
				<string>Si.pz-vbc.UPF</string>
			</property>
		</specie>
	</atomic_species>

	<atomic_list units="alat" nat="2" >
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					-0.123 -0.123 -0.123
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.123  0.123  0.123
				</real>
			</position>
		</atom>						
	</atomic_list>
	
	
	<field name="InputOutput">

		<parameter name="restart_mode">
			<string>
				from_scratch
			</string>
		</parameter>
		
		<parameter name="pseudo_dir">
			<string>
				$PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
				$TMP_DIR/
			</string>
		</parameter>
		<parameter name="disk_io">
			<string>
				high
			</string>
		</parameter>
				
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				8.0
			</real>
		</parameter>
		
		<parameter name="nosym">
			<logical>
				true
			</logical>
		</parameter>
		
		<parameter name="mixing_beta">
			<real>
				0.7
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.0d-8
			</real>
		</parameter>
		
	</field>	
	
	<field name="MD">

		<parameter name="dt">
			<real>
				20.0
			</real>
		</parameter>
		<parameter name="nstep">
			<integer>
				100				
			</integer>
		</parameter>
		<parameter name="pot_extrapolation">
			<string>
				second-order
			</string>
		</parameter>			
		<parameter name="wfc_extrapolation">
			<string>
				second-order
			</string>
		</parameter>		
	
	</field>
	
	<k_points type="automatic">
		<mesh>
			<integer rank="1" n1="6">
				1 1 1 0 0 0
			</integer>
		</mesh> 
	</k_points>
</input>
EOF
$ECHO "  running the MD calculation for Si in a 2 atom cell. G-point...\c"
$PW_COMMAND < si.md2.xml > si.md2.out
check_failure $?
$ECHO " done"

awk '/Ekin/{ek=$3;et=$11; print it,time,ek,u,et}/Dynamics/{it=$5;time=$8}/^\!/{u=$5}' si.md2.out > MD2

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"

# MD in a 8-atom cell
cat > si.md8.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>

<input calculation="md">

	<cell type="qecell">
		<qecell ibrav="1" alat="10.18">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="1">
		<specie name="Si">
			<property name="mass">
				<real>28.086</real>
			</property>
			<property name="pseudofile">
				<string>Si.pz-vbc.UPF</string>
			</property>
		</specie>
	</atomic_species>

	<atomic_list units="alat" nat="8" >
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					-0.123 -0.123 -0.123
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.377  0.377 -0.123
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.377 -0.123  0.377
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					-0.123  0.377  0.377
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.123  0.123  0.123
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.623  0.623  0.123
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.623  0.123  0.623
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.123  0.623  0.623
				</real>
			</position>
		</atom>						
	</atomic_list>		
	
	
	<field name="InputOutput">

		<parameter name="restart_mode">
			<string>
				from_scratch
			</string>
		</parameter>
		
		<parameter name="pseudo_dir">
			<string>
				$PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
				$TMP_DIR/
			</string>
		</parameter>
		<parameter name="disk_io">
			<string>
				high
			</string>
		</parameter>
				
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				8.0
			</real>
		</parameter>
		
		<parameter name="nosym">
			<logical>
				true
			</logical>
		</parameter>
		
		<parameter name="mixing_beta">
			<real>
				0.7
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.0d-8
			</real>
		</parameter>
		
	</field>	
	
	<field name="MD">

		<parameter name="dt">
			<real>
				20.0
			</real>
		</parameter>
		<parameter name="nstep">
			<integer>
				100				
			</integer>
		</parameter>
		<parameter name="pot_extrapolation">
			<string>
				second-order
			</string>
		</parameter>			
		<parameter name="wfc_extrapolation">
			<string>
				second-order
			</string>
		</parameter>		
	
	</field>
	
	<k_points type="automatic">
		<mesh>
			<integer rank="1" n1="6">
				1 1 1 0 0 0
			</integer>
		</mesh> 
	</k_points>
</input>
EOF
$ECHO "  running the MD calculation for Si in a 8 atom cell. G-point...\c"
$PW_COMMAND < si.md8.xml > si.md8.out
check_failure $?
$ECHO " done"

awk '/Ekin/{ek=$3;et=$11; print it,time,ek,u,et}/Dynamics/{it=$5;time=$8}/^\!/{u=$5}' si.md8.out > MD8

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"

# MD in a 2-atom cell. Gamma+3X
cat > si.md2_G3X.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>

<input calculation="md">

	<cell type="qecell">
		<qecell ibrav="2" alat="10.18">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="1">
		<specie name="Si">
			<property name="mass">
				<real>28.086</real>
			</property>
			<property name="pseudofile">
				<string>Si.pz-vbc.UPF</string>
			</property>
		</specie>
	</atomic_species>

	<atomic_list units="alat" nat="2" >
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					-0.123 -0.123 -0.123
				</real>
			</position>
		</atom>	
		<atom name="Si">
			<position>
				<real rank="1" n1="3">
					0.123  0.123  0.123
				</real>
			</position>
		</atom>						
	</atomic_list>				
	
	
	<field name="InputOutput">

		<parameter name="restart_mode">
			<string>
				from_scratch
			</string>
		</parameter>
		
		<parameter name="pseudo_dir">
			<string>
				$PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
				$TMP_DIR/
			</string>
		</parameter>
		<parameter name="disk_io">
			<string>
				high
			</string>
		</parameter>
				
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				8.0
			</real>
		</parameter>
		
		<parameter name="nosym">
			<logical>
				true
			</logical>
		</parameter>
		
		<parameter name="mixing_beta">
			<real>
				0.7
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.0d-8
			</real>
		</parameter>
		
	</field>	
	
	<field name="MD">

		<parameter name="dt">
			<real>
				20.0
			</real>
		</parameter>
		<parameter name="nstep">
			<integer>
				100				
			</integer>
		</parameter>
		<parameter name="pot_extrapolation">
			<string>
				second-order
			</string>
		</parameter>			
		<parameter name="wfc_extrapolation">
			<string>
				second-order
			</string>
		</parameter>		
	
	</field>
	
	<k_points type="tpiba">
		<mesh npoints="4">
			<real rank="2" n1="4" n2="4">
				   	 0.0 0.0 0.0 1.0
					 1.0 0.0 0.0 1.0
					 0.0 1.0 0.0 1.0
					 0.0 0.0 1.0 1.0
			</real>
		</mesh>
	</k_points>
</input>
EOF
$ECHO "  running the MD calculation for Si in a 2 atom cell. G3X-points...\c"
$PW_COMMAND < si.md2_G3X.xml > si.md2_G3X.out
check_failure $?
$ECHO " done"

awk '/Ekin/{ek=$3;et=$11; print it,time,ek,u,et} \
     /Dynamics/{it=$5;time=$8}/^\!/{u=$5}' si.md2_G3X.out > MD2_G3X

$ECHO
$ECHO "$EXAMPLE_DIR: done"
