#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to calculate the total energy of an isolated"
$ECHO "atom in a supercell with fixed occupations."
$ECHO "Three examples: LDA energy of Al, sigma-GGA energy of O,"
$ECHO "and sigma-GGA energy of Ni in two configurations"

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x"
PSEUDO_LIST=" Al.pz-vbc.UPF O.pbe-rrkjus.UPF  Ni.pbe-nd-rrkjus.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x as: $PW_COMMAND"
$ECHO

# self-consistent calculation for isolated Al atom
cat > al.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    pseudo_dir='$PSEUDO_DIR/'
    outdir='$TMP_DIR/'
 /
 &system
   ibrav=1,
   celldm(1)=20.0,
   nat=1,
   ntyp=1,
   nbnd=6,
   nosym=.true.,
   ecutwfc=15.0,
   occupations='from_input',
 /
 &electrons
   mixing_beta=0.35,
   conv_thr=1.0E-8,
 /
ATOMIC_SPECIES
Al     26.98154    Al.pz-vbc.UPF
ATOMIC_POSITIONS
Al      0.0000000000   0.0000000000     0.000
K_POINTS  AUTOMATIC
1   1   1   0   0   0
OCCUPATIONS
2.0 0.3333333333333 0.333333333333 0.3333333333333 0.0 0.0
EOF
$ECHO "  running self-consistent calculation for Al atom...\c"
$PW_COMMAND < al.in > al.out
check_failure $?
$ECHO " done"

# self consistent calculation for the spin polarized O atom
cat > O.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    pseudo_dir='$PSEUDO_DIR/'
    outdir='$TMP_DIR/'
 /
 &system
   ibrav=1,
   celldm(1)=14.0,
   nat=1,
   ntyp=1,
   nbnd=6,
   nosym=.true.,
   ecutwfc=27.0,
   ecutrho=216.0,
   occupations='from_input',
   nspin=2,
   starting_magnetization(1)=0.5d0,
 /
 &electrons
   mixing_beta=0.25,
   conv_thr=1.0E-8,
 /
ATOMIC_SPECIES
O     15.99994   O.pbe-rrkjus.UPF
ATOMIC_POSITIONS
O   0.000000000   0.000000000   0.000000000
K_POINTS AUTOMATIC
1   1   1   0   0   0
OCCUPATIONS
1.0 1.0 1.0 1.0 0.0 0.0
1.0 0.33333333333 0.33333333333 0.33333333333 0.0 0.0
EOF
$ECHO "  running calculation for O atom...\c"
$PW_COMMAND < O.in > O.out
check_failure $?
$ECHO " done"

#
cat > O_gamma.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    pseudo_dir='$PSEUDO_DIR/'
    outdir='$TMP_DIR/'
 /
 &system
   ibrav=1,
   celldm(1)=14.0,
   nat=1,
   ntyp=1,
   nbnd=6,
   nosym=.true.,
   ecutwfc=27.0,
   ecutrho=216.0,
   occupations='from_input',
   nspin=2,
   starting_magnetization(1)=0.5d0,
 /
 &electrons
   mixing_beta=0.25,
   conv_thr=1.0E-8,
 /
ATOMIC_SPECIES
O     15.99994   O.pbe-rrkjus.UPF
ATOMIC_POSITIONS
O   0.000000000   0.000000000   0.000000000
K_POINTS (gamma)
OCCUPATIONS
1.0 1.0 1.0 1.0 0.0 0.0
1.0 0.33333333333 0.33333333333 0.33333333333 0.0 0.0
EOF
$ECHO "  running calculation for O atom, Gamma-only...\c"
$PW_COMMAND < O_gamma.in > O_gamma.out
check_failure $?
$ECHO " done"

cat > Ni_gamma_d8s2.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    pseudo_dir='$PSEUDO_DIR/'
    outdir='$TMP_DIR/'
 /
 &system
   ibrav=1,
   celldm(1)=14.0,
   nat=1,
   ntyp=1,
   nbnd=6,
   nosym=.true.,
   ecutwfc=27.0,
   ecutrho=300.0,
   occupations='from_input',
   nspin=2,
   starting_magnetization(1)=0.5d0,
   one_atom_occupations=.true.,
 /
 &electrons
   mixing_beta=0.25,
   conv_thr=1.0E-8,
   startingwfc='atomic'
 /
ATOMIC_SPECIES
Ni     0.0   Ni.pbe-nd-rrkjus.UPF
ATOMIC_POSITIONS
Ni   0.000000000   0.000000000   0.000000000
K_POINTS (gamma)
OCCUPATIONS
1.0 1.0 1.0 1.0 1.0 1.0
1.0 0.6 0.6 0.6 0.6 0.6
EOF
$ECHO "  running calculation for Ni atom d8 s2, Gamma-only...\c"
$PW_COMMAND < Ni_gamma_d8s2.in > Ni_gamma_d8s2.out
check_failure $?
$ECHO " done"

cat > Ni_gamma_d9s1.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    pseudo_dir='$PSEUDO_DIR/'
    outdir='$TMP_DIR/'
 /
 &system
   ibrav=1,
   celldm(1)=14.0,
   nat=1,
   ntyp=1,
   nbnd=6,
   nosym=.true.,
   ecutwfc=27.0,
   ecutrho=300.0,
   occupations='from_input',
   nspin=2,
   starting_magnetization(1)=0.5d0,
   one_atom_occupations=.true.,
 /
 &electrons
   mixing_beta=0.25,
   conv_thr=1.0E-8,
   startingwfc='atomic'
 /
ATOMIC_SPECIES
Ni     0.0   Ni.pbe-nd-rrkjus.UPF
ATOMIC_POSITIONS
Ni   0.000000000   0.000000000   0.000000000
K_POINTS (gamma)
OCCUPATIONS
1.0 1.0 1.0 1.0 1.0 1.0
0.0 0.8 0.8 0.8 0.8 0.8
EOF
$ECHO "  running calculation for Ni atom d9 s1, Gamma-only...\c"
$PW_COMMAND < Ni_gamma_d9s1.in > Ni_gamma_d9s1.out
check_failure $?
$ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/pwscf*
$ECHO " done"


$ECHO
$ECHO "$EXAMPLE_DIR: done"
