#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether ECHO has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use pw.x and ph.x to calculate dynamic"
$ECHO "polarizability of methane molecule "

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x ph.x"
PSEUDO_LIST="C.pz-vbc.UPF H.pz-vbc.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE \
                http://www.quantum-espresso.org/pseudo/1.3/UPF/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
PH_COMMAND="$PARA_PREFIX $BIN_DIR/ph.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x as: $PW_COMMAND"
$ECHO "  running ph.x as: $PH_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"


# self-consistent calculation
chbl=1.10           #C-H bond length in CH4
bohr=0.529177
n=5
lc=$(echo "scale=5; $n * $chbl / $bohr" | bc)  # latt. const. in a.u.
pos=$(echo "scale=5; 1.0/$n/sqrt(3)" | bc )
ecut=40.0
#
cat > ch4.scf.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>


<input calculation="relax" prefix="ch4">

	<cell type="qecell">
		<qecell ibrav="1" alat="$lc">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="2">
		<specie name="C">
			<property name="mass">
				<real>12.0107</real>
			</property>
			<property name="pseudofile">
				<string>C.pz-vbc.UPF</string>
			</property>
		</specie>
		<specie name="H">
			<property name="mass">
				<real>1.00794</real>
			</property>
			<property name="pseudofile">
				<string>H.pz-vbc.UPF</string>
			</property>
		</specie>
	</atomic_species>

	<atomic_list units="alat" nat="5" >
		<atom name="C">
			<position>
				<real rank="1" n1="3">
					0.00  0.00  0.00
				</real>
			</position>
		</atom>	
		<atom name="H">
			<position>
				<real rank="1" n1="3">
					$pos   $pos   $pos
				</real>
			</position>
		</atom>	
		<atom name="H">
			<position>
				<real rank="1" n1="3">
					$pos  -$pos  -$pos
				</real>
			</position>
		</atom>	
		<atom name="H">
			<position>
				<real rank="1" n1="3">
					-$pos  -$pos   $pos
				</real>
			</position>
		</atom>	
		<atom name="H">
			<position>
				<real rank="1" n1="3">
					-$pos   $pos  -$pos
				</real>
			</position>
		</atom>						
	</atomic_list>	
	
	
	<field name="InputOutput">

		<parameter name="restart_mode">
			<string>
				from_scratch
			</string>
		</parameter>
		
		<parameter name="pseudo_dir">
			<string>
				$PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
				$TMP_DIR/
			</string>
		</parameter>
		
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				$ecut
			</real>
		</parameter>
		
	</field>
	
	<k_points type="tpiba">
		<mesh npoints="1">
			<real rank="2" n1="4" n2="1">
				  	0.00 0.00 0.00 1.0
			</real>
		</mesh>
	</k_points>
</input>
EOF
#
$ECHO "  running the scf calculation...\c"
$PW_COMMAND < ch4.scf.xml > ch4.scf.out
check_failure $?
$ECHO " done"
#
# dynamic polarizability calculation
#
cat > ch4.fpol.in << EOF

&inputph
  tr2_ph=1.0d-14,
  prefix='ch4',
  epsil=.true.,
  trans=.false.,
  fpol=.true.,
  amass(1)=12.0107,
  amass(2)=1.00794,
  outdir='$TMP_DIR/',
  fildyn='ch4.dynG',
 /
0.0 0.0 0.0

FREQUENCIES
 2
 0.0d0
 1.5d0
EOF
#
$ECHO "  running the dynamic polarizability calculation ...\c"
$PH_COMMAND < ch4.fpol.in > ch4.fpol.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR : done"
