#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use cp.x to perform molecular dynamics"
$ECHO "simulation of H2O."

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="cp.x"
PSEUDO_LIST="O.blyp-mt.UPF H.blyp-vbc.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null         
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
FPMD_COMMAND="$PARA_PREFIX $BIN_DIR/cp.x $PARA_POSTFIX"
$ECHO
$ECHO "  running cp.x as: $FPMD_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/cp*
$ECHO " done"

# molecular dynamics calculation
cat > h2o-mol1.in << EOF
 &control
    title = ' Water Molecule ',
    calculation = 'cp',
    restart_mode = 'from_scratch',
    ndr = 51,
    ndw = 51,
    nstep  = 50,
    iprint = 10,
    isave  = 100,
    tstress = .TRUE.,
    tprnfor = .TRUE.,
    dt    = 5.0d0,
    etot_conv_thr = 1.d-9,
    ekin_conv_thr = 1.d-4,
    prefix = 'h2o_mol'
    pseudo_dir='$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
 /
 &system
    ibrav = 14,
    celldm(1) = 12.0,
    celldm(2) = 1.0,
    celldm(3) = 1.0,
    celldm(4) = 0.0,
    celldm(5) = 0.0,
    celldm(6) = 0.0,
    nat  = 3,
    ntyp = 2,
    nbnd = 4,
    ecutwfc = 80.0,
    input_dft = 'BLYP'
 /
 &electrons
    emass = 400.d0,
    emass_cutoff = 2.5d0,
    orthogonalization = 'ortho',
    ortho_eps = 5.d-8,
    ortho_max = 15,
    electron_dynamics = 'sd',
 /
 &ions
    ion_dynamics = 'none',
    ion_radius(1) = 0.8d0,
    ion_radius(2) = 0.8d0,
 /
 &cell
    cell_dynamics = 'none',
    press = 0.0d0,
 /
ATOMIC_SPECIES
 O 16.0d0 O.blyp-mt.UPF
 H 1.00d0 H.blyp-vbc.UPF
ATOMIC_POSITIONS (bohr)
   O     0.0099    0.0099    0.0000  0 0 0
   H     1.8325   -0.2243   -0.0001  1 1 1
   H    -0.2243    1.8325    0.0002  1 1 1
EOF
$ECHO "  running the calculation with fixed ions...\c"
$FPMD_COMMAND < h2o-mol1.in > h2o-mol1.out
check_failure $?
$ECHO " done"

# molecular dynamics calculation
cat > h2o-mol2.in << EOF
 &control
    title = ' Water Molecule ',
    calculation = 'cp',
    restart_mode = 'restart',
    ndr = 51,
    ndw = 51,
    nstep  = 50,
    iprint = 10,
    isave  = 100,
    tstress = .TRUE.,
    tprnfor = .TRUE.,
    dt    = 5.0d0,
    etot_conv_thr = 1.d-9,
    ekin_conv_thr = 1.d-4,
    prefix = 'h2o_mol'
    pseudo_dir='$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
 /
 &system
    ibrav = 14,
    celldm(1) = 12.0,
    celldm(2) = 1.0,
    celldm(3) = 1.0,
    celldm(4) = 0.0,
    celldm(5) = 0.0,
    celldm(6) = 0.0,
    nat  = 3,
    ntyp = 2,
    nbnd = 4,
    ecutwfc = 80.0,
    input_dft = 'BLYP'
 /
 &electrons
    emass = 400.d0,
    emass_cutoff = 2.5d0,
    orthogonalization = 'ortho',
    ortho_eps = 5.d-8,
    ortho_max = 15,
    electron_dynamics = 'sd',
 /
 &ions
    ion_dynamics = 'none',
    ion_radius(1) = 0.8d0,
    ion_radius(2) = 0.8d0,
 /
 &cell
    cell_dynamics = 'none',
    press = 0.0d0,
 /
ATOMIC_SPECIES
 O 16.0d0 O.blyp-mt.UPF
 H 1.00d0 H.blyp-vbc.UPF
ATOMIC_POSITIONS (bohr)
   O     0.0099    0.0099    0.0000  0 0 0
   H     1.8325   -0.2243   -0.0001  1 1 1
   H    -0.2243    1.8325    0.0002  1 1 1
EOF
$ECHO "  running the calculation with fixed ions, restart...\c"
$FPMD_COMMAND < h2o-mol2.in > h2o-mol2.out
check_failure $?
$ECHO " done"

cat > h2o-mol3.in << EOF
 &control
    title = ' Water Molecule ',
    calculation = 'cp',
    restart_mode = 'restart',
    ndr = 51,
    ndw = 51,
    nstep  = 50,
    iprint = 10,
    isave  = 100,
    tstress = .TRUE.,
    tprnfor = .TRUE.,
    dt    = 5.0d0,
    etot_conv_thr = 1.d-9,
    ekin_conv_thr = 1.d-4,
    prefix = 'h2o_mol'
    pseudo_dir='$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
 /
 &system
    ibrav = 14,
    celldm(1) = 12.0,
    celldm(2) = 1.0,
    celldm(3) = 1.0,
    celldm(4) = 0.0,
    celldm(5) = 0.0,
    celldm(6) = 0.0,
    nat  = 3,
    ntyp = 2,
    nbnd = 4,
    ecutwfc = 80.0,
    input_dft = 'BLYP'
 /
 &electrons
    emass = 400.d0,
    emass_cutoff = 2.5d0,
    orthogonalization = 'ortho',
    ortho_eps = 5.d-8,
    ortho_max = 15,
    electron_dynamics = 'verlet',
    electron_velocities = 'zero',
    electron_temperature = 'not_controlled',
 /
 &ions
    ion_dynamics = 'verlet',
    ion_radius(1) = 0.8d0,
    ion_radius(2) = 0.8d0,
    ion_velocities = 'zero',
 /
 &cell
    cell_dynamics = 'none',
    press = 0.0d0,
 /
ATOMIC_SPECIES
 O 16.0d0 O.blyp-mt.UPF
 H 1.00d0 H.blyp-vbc.UPF
ATOMIC_POSITIONS (bohr)
   O     0.0099    0.0099    0.0000  0 0 0
   H     1.8325   -0.2243   -0.0001  1 1 1
   H    -0.2243    1.8325    0.0002  1 1 1
EOF
$ECHO "  running the calculation with ionic dynamics...\c"
$FPMD_COMMAND < h2o-mol3.in > h2o-mol3.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR : done"
