#!/bin/sh

###############################################################################
##
##  ESM EXAMPLE
##
###############################################################################

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use ESM to calculate H2O and Al(001)"
$ECHO "using the three available sets of boundary conditions."
$ECHO "This example also shows how to use ESM to calculate stress of"
$ECHO "graphene using the three available sets of boundary conditions."
$ECHO

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x"
PSEUDO_LIST="Al.pbe-n-van.UPF H.pbe-van_ak.UPF O.pbe-van_ak.UPF C.pz-van_ak.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
       echo $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x     as: $PW_COMMAND"
$ECHO


# scf calculation for H2O with no ESM
cat > H2O_pbc.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    prefix='H2O_pbc',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor = .TRUE.
 /
 &system
    ibrav = 0,
    nat= 3, ntyp= 2,
    ecutwfc = 25.0, ecutrho = 200.0,
    occupations='smearing', smearing='mp', degauss=0.03,
    assume_isolated = 'esm', esm_bc='pbc'
 /
 &electrons
    mixing_beta = 0.3
 /
ATOMIC_SPECIES
 H  1.00794  H.pbe-van_ak.UPF 
 O  55.847   O.pbe-van_ak.UPF  
CELL_PARAMETERS angstrom
    10.5835400000    0.0000000000    0.0000000000
     0.0000000000   10.5835400000    0.0000000000
     0.0000000000    0.0000000000   12.7002480000
ATOMIC_POSITIONS angstrom
O    0.0000000000    5.2917700000    0.0000000000
H    0.4565612154    4.5618084292    0.4559209112
H    0.3877322213    6.1004201907    0.3804697962
K_POINTS gamma
EOF
$ECHO "  running the calculation for H2O without ESM...\c"
$PW_COMMAND < H2O_pbc.in > H2O_pbc.out
check_failure $?
$ECHO " done"
mv $TMP_DIR/H2O_pbc.esm1 .

# scf calculation for H2O with ESM bc1 (vacuum-slab-vacuum)
cat > H2O_bc1.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    prefix='H2O_bc1',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor = .TRUE.
 /
 &system
    ibrav = 0,
    nat= 3, ntyp= 2,
    ecutwfc = 25.0, ecutrho = 200.0,
    occupations='smearing', smearing='mp', degauss=0.03,
    assume_isolated = 'esm', esm_bc='bc1'
 /
 &electrons
    mixing_beta = 0.3
 /
ATOMIC_SPECIES
 H  1.00794  H.pbe-van_ak.UPF 
 O  55.847   O.pbe-van_ak.UPF  
CELL_PARAMETERS angstrom
    10.5835400000    0.0000000000    0.0000000000
     0.0000000000   10.5835400000    0.0000000000
     0.0000000000    0.0000000000   12.7002480000
ATOMIC_POSITIONS angstrom
O    0.0000000000    5.2917700000    0.0000000000
H    0.4565612154    4.5618084292    0.4559209112
H    0.3877322213    6.1004201907    0.3804697962
K_POINTS gamma
EOF
$ECHO "  running the calculation for H2O with ESM bc1 (vacuum-slab-vacuum)...\c"
$PW_COMMAND < H2O_bc1.in > H2O_bc1.out
check_failure $?
$ECHO " done"
mv $TMP_DIR/H2O_bc1.esm1 .

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/H2O*
$ECHO " done"

# calculation for Al(001) without ESM
cat > Al001_pbc.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    prefix='Al001_pbc',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor = .TRUE.
 /
 &system
    ibrav = 0,
    nat= 4, ntyp= 1,
    ecutwfc = 20.0,
    nosym=.TRUE.
    occupations='smearing', smearing='mp', degauss=0.03
    assume_isolated='esm', esm_bc='pbc'
 /
 &electrons
    mixing_beta = 0.3
 /
ATOMIC_SPECIES
 Al  26.981538   Al.pbe-n-van.UPF
CELL_PARAMETERS angstrom
     5.7269000760    0.0000000000    0.0000000000
     0.0000000000    5.7269000760    0.0000000000
     0.0000000000    0.0000000000   11.9999975199
ATOMIC_POSITIONS angstrom
Al   0.0000000000    0.0000000000    0.0000000000
Al   2.8634500380    0.0000000000    0.0000000000
Al   0.0000000000    2.8634500380    0.0000000000
Al   2.8634500380    2.8634500380    0.0000000000
 K_POINTS automatic
 6 6 1 1 1 0
EOF
$ECHO "  running the calculation for Al(001) without ESM\c"
$PW_COMMAND < Al001_pbc.in > Al001_pbc.out
check_failure $?
$ECHO " done"
mv $TMP_DIR/Al001_pbc.esm1 .

# calculation for Al(001) with ESM bc1 (vacuum-slab-vacuum)
cat > Al001_bc1.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    prefix='Al001_bc1',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor = .TRUE.
 /
 &system
    ibrav = 0,
    nat= 4, ntyp= 1,
    ecutwfc = 20.0,
    nosym=.TRUE.
    occupations='smearing', smearing='mp', degauss=0.03
    assume_isolated='esm', esm_bc='bc1'
 /
 &electrons
    mixing_beta = 0.3
 /
ATOMIC_SPECIES
 Al  26.981538   Al.pbe-n-van.UPF
CELL_PARAMETERS angstrom
     5.7269000760    0.0000000000    0.0000000000
     0.0000000000    5.7269000760    0.0000000000
     0.0000000000    0.0000000000   11.9999975199
ATOMIC_POSITIONS angstrom
Al   0.0000000000    0.0000000000    0.0000000000
Al   2.8634500380    0.0000000000    0.0000000000
Al   0.0000000000    2.8634500380    0.0000000000
Al   2.8634500380    2.8634500380    0.0000000000
 K_POINTS automatic
 6 6 1 1 1 0
EOF
$ECHO "  running the calculation for Al(001) with ESM bc1 (vacuum-slab-vacuuml)"
$PW_COMMAND < Al001_bc1.in > Al001_bc1.out
check_failure $?
$ECHO " done"
mv $TMP_DIR/Al001_bc1.esm1 .

# calculation for Al(001) with ESM bc2 (metal-slab-metal), no field
cat > Al001_bc2.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    prefix='Al001_bc2',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor = .TRUE.
 /
 &system
    ibrav = 0,
    nat= 4, ntyp= 1,
    ecutwfc = 20.0,
    nosym=.TRUE.
    occupations='smearing', smearing='mp', degauss=0.03
    assume_isolated='esm', esm_bc='bc2'
 /
 &electrons
    mixing_beta = 0.3
 /
ATOMIC_SPECIES
 Al  26.981538   Al.pbe-n-van.UPF
CELL_PARAMETERS angstrom
     5.7269000760    0.0000000000    0.0000000000
     0.0000000000    5.7269000760    0.0000000000
     0.0000000000    0.0000000000   11.9999975199
ATOMIC_POSITIONS angstrom
Al   0.0000000000    0.0000000000    0.0000000000
Al   2.8634500380    0.0000000000    0.0000000000
Al   0.0000000000    2.8634500380    0.0000000000
Al   2.8634500380    2.8634500380    0.0000000000
 K_POINTS automatic
 6 6 1 1 1 0
EOF
$ECHO "  running the calculation for Al(001) with ESM bc2 (metal-slab-metal)"
$ECHO "  (no applied field)...\c"
$PW_COMMAND < Al001_bc2.in > Al001_bc2.out
check_failure $?
$ECHO " done"
mv $TMP_DIR/Al001_bc2.esm1 .

# calculation for Al(001) with ESM bc2 (metal-slab-metal), with field
cat > Al001_bc2_efield.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    prefix='Al001_bc2_efield',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor = .TRUE.
 /
 &system
    ibrav = 0,
    nat= 4, ntyp= 1,
    ecutwfc = 20.0,
    nosym=.TRUE.
    occupations='smearing', smearing='mp', degauss=0.03
    assume_isolated='esm', esm_bc='bc2', esm_efield=0.00192148511256006
 /
 &electrons
    mixing_beta = 0.3
 /
ATOMIC_SPECIES
 Al  26.981538   Al.pbe-n-van.UPF
CELL_PARAMETERS angstrom
     5.7269000760    0.0000000000    0.0000000000
     0.0000000000    5.7269000760    0.0000000000
     0.0000000000    0.0000000000   11.9999975199
ATOMIC_POSITIONS angstrom
Al   0.0000000000    0.0000000000    0.0000000000
Al   2.8634500380    0.0000000000    0.0000000000
Al   0.0000000000    2.8634500380    0.0000000000
Al   2.8634500380    2.8634500380    0.0000000000
 K_POINTS automatic
 6 6 1 1 1 0
EOF
$ECHO "  running the calculation for Al(001) with ESM bc2 (metal-slab-metal)"
$ECHO "  with applied electric field...\c"
$PW_COMMAND < Al001_bc2_efield.in > Al001_bc2_efield.out
check_failure $?
$ECHO " done"
mv $TMP_DIR/Al001_bc2_efield.esm1 .

# calculation for Al(001) with ESM bc3 (vacuum-slab-metal), uncharged
cat > Al001_bc3.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    prefix='Al001_bc3',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor = .TRUE.
 /
 &system
    ibrav = 0,
    nat= 4, ntyp= 1,
    ecutwfc = 20.0,
    nosym=.TRUE.
    occupations='smearing', smearing='mp', degauss=0.03
    assume_isolated='esm', esm_bc='bc3'
 /
 &electrons
    mixing_beta = 0.3
 /
ATOMIC_SPECIES
 Al  26.981538   Al.pbe-n-van.UPF
CELL_PARAMETERS angstrom
     5.7269000760    0.0000000000    0.0000000000
     0.0000000000    5.7269000760    0.0000000000
     0.0000000000    0.0000000000   11.9999975199
ATOMIC_POSITIONS angstrom
Al   0.0000000000    0.0000000000    0.0000000000
Al   2.8634500380    0.0000000000    0.0000000000
Al   0.0000000000    2.8634500380    0.0000000000
Al   2.8634500380    2.8634500380    0.0000000000
 K_POINTS automatic
 6 6 1 1 1 0
EOF
$ECHO "  running the calculation for Al(001) with ESM bc3 (vacuum-slab-metal)"
$ECHO "  (neutrally charged)...\c"
$PW_COMMAND < Al001_bc3.in > Al001_bc3.out
check_failure $?
$ECHO " done"
mv $TMP_DIR/Al001_bc3.esm1 .

# calculation for Al(001) with ESM bc3 (vacuum-slab-metal), - charged
cat > Al001_bc3_m002.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    prefix='Al001_bc3_m002',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor = .TRUE.
 /
 &system
    ibrav = 0,
    nat= 4, ntyp= 1,
    ecutwfc = 20.0,
    nosym=.TRUE.
    occupations='smearing', smearing='mp', degauss=0.03
    assume_isolated='esm', esm_bc='bc3'
    tot_charge = -0.02,
 /
 &electrons
    mixing_beta = 0.3
 /
ATOMIC_SPECIES
 Al  26.981538   Al.pbe-n-van.UPF
CELL_PARAMETERS angstrom
     5.7269000760    0.0000000000    0.0000000000
     0.0000000000    5.7269000760    0.0000000000
     0.0000000000    0.0000000000   11.9999975199
ATOMIC_POSITIONS angstrom
Al   0.0000000000    0.0000000000    0.0000000000
Al   2.8634500380    0.0000000000    0.0000000000
Al   0.0000000000    2.8634500380    0.0000000000
Al   2.8634500380    2.8634500380    0.0000000000
 K_POINTS automatic
 6 6 1 1 1 0
EOF
$ECHO "  running the calculation for Al(001) with ESM bc3 (vacuum-slab-metal)"
$ECHO "  (-0.02e charged)...\c"
$PW_COMMAND < Al001_bc3_m002.in > Al001_bc3_m002.out
check_failure $?
$ECHO " done"
mv $TMP_DIR/Al001_bc3_m002.esm1 .

# calculation for Al(001) with ESM bc3 (vacuum-slab-metal), + charged
cat > Al001_bc3_p002.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    prefix='Al001_bc3_p002',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor = .TRUE.
 /
 &system
    ibrav = 0,
    nat= 4, ntyp= 1,
    ecutwfc = 20.0,
    nosym=.TRUE.
    occupations='smearing', smearing='mp', degauss=0.03
    assume_isolated='esm', esm_bc='bc3'
    tot_charge = 0.02,
 /
 &electrons
    mixing_beta = 0.3
 /
ATOMIC_SPECIES
 Al  26.981538   Al.pbe-n-van.UPF
CELL_PARAMETERS angstrom
     5.7269000760    0.0000000000    0.0000000000
     0.0000000000    5.7269000760    0.0000000000
     0.0000000000    0.0000000000   11.9999975199
ATOMIC_POSITIONS angstrom
Al   0.0000000000    0.0000000000    0.0000000000
Al   2.8634500380    0.0000000000    0.0000000000
Al   0.0000000000    2.8634500380    0.0000000000
Al   2.8634500380    2.8634500380    0.0000000000
 K_POINTS automatic
 6 6 1 1 1 0
EOF
$ECHO "  running the calculation for Al(001) with ESM bc3 (vacuum-slab-metal)"
$ECHO "  (+0.02e charged)...\c"
$PW_COMMAND < Al001_bc3_p002.in > Al001_bc3_p002.out
check_failure $?
$ECHO " done"
mv $TMP_DIR/Al001_bc3_p002.esm1 .

# constant-mu calculation for Al(001) with ESM bc3 (vacuum-slab-metal), 
# target mu = potential of zero charge (neutral surface)
cat > Al001_bc3_v00.in << EOF
 &control
    calculation='relax',
    restart_mode='from_scratch',
    prefix='Al001_bc3_v00',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor = .TRUE.
    lfcpopt = .TRUE.
 /
 &system
    ibrav = 0,
    nat= 4, ntyp= 1,
    ecutwfc = 20.0,
    nosym=.TRUE.
    occupations='smearing', smearing='mp', degauss=0.03
    assume_isolated='esm', esm_bc='bc3'
    fcp_mu = -0.312573,
 /
 &electrons
    mixing_beta = 0.3
 /
 &ions
 ion_dynamics = 'bfgs'
 /
ATOMIC_SPECIES
 Al  26.981538   Al.pbe-n-van.UPF
CELL_PARAMETERS angstrom
     5.7269000760    0.0000000000    0.0000000000
     0.0000000000    5.7269000760    0.0000000000
     0.0000000000    0.0000000000   11.9999975199
ATOMIC_POSITIONS angstrom
Al   0.0000000000    0.0000000000    0.0000000000
Al   2.8634500380    0.0000000000    0.0000000000
Al   0.0000000000    2.8634500380    0.0000000000
Al   2.8634500380    2.8634500380    0.0000000000
 K_POINTS automatic
 6 6 1 1 1 0
EOF
$ECHO "  running the constant-mu calculation for Al(001) with ESM bc3 (vacuum-slab-metal)"
$ECHO "  (target mu = 0V vs pzc)...\c"
$PW_COMMAND < Al001_bc3_v00.in > Al001_bc3_v00.out
check_failure $?
$ECHO " done"
mv $TMP_DIR/Al001_bc3_v00.esm1 .

# constant-mu calculation for Al(001) with ESM bc3 (vacuum-slab-metal), 
# target mu = +0.5V vs pzc
cat > Al001_bc3_vp05.in << EOF
 &control
    calculation='relax',
    restart_mode='from_scratch',
    prefix='Al001_bc3_vp05',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor = .TRUE.
    lfcpopt = .TRUE.
 /
 &system
    ibrav = 0,
    nat= 4, ntyp= 1,
    ecutwfc = 20.0,
    nosym=.TRUE.
    occupations='smearing', smearing='mp', degauss=0.03
    assume_isolated='esm', esm_bc='bc3'
    fcp_mu = -0.275809,
 /
 &electrons
    mixing_beta = 0.3
 /
 &ions
 ion_dynamics = 'bfgs'
 /
ATOMIC_SPECIES
 Al  26.981538   Al.pbe-n-van.UPF
CELL_PARAMETERS angstrom
     5.7269000760    0.0000000000    0.0000000000
     0.0000000000    5.7269000760    0.0000000000
     0.0000000000    0.0000000000   11.9999975199
ATOMIC_POSITIONS angstrom
Al   0.0000000000    0.0000000000    0.0000000000
Al   2.8634500380    0.0000000000    0.0000000000
Al   0.0000000000    2.8634500380    0.0000000000
Al   2.8634500380    2.8634500380    0.0000000000
 K_POINTS automatic
 6 6 1 1 1 0
EOF
$ECHO "  running the constant-mu calculation for Al(001) with ESM bc3 (vacuum-slab-metal)"
$ECHO "  (target mu = +0.5V vs pzc)...\c"
$PW_COMMAND < Al001_bc3_vp05.in > Al001_bc3_vp05.out
check_failure $?
$ECHO " done"
mv $TMP_DIR/Al001_bc3_vp05.esm1 .

# constant-mu calculation for Al(001) with ESM bc3 (vacuum-slab-metal), 
# target mu = -0.5V vs pzc
cat > Al001_bc3_vm05.in << EOF
 &control
    calculation='relax',
    restart_mode='from_scratch',
    prefix='Al001_bc3_vm05',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor = .TRUE.
    lfcpopt = .TRUE.
 /
 &system
    ibrav = 0,
    nat= 4, ntyp= 1,
    ecutwfc = 20.0,
    nosym=.TRUE.
    occupations='smearing', smearing='mp', degauss=0.03
    assume_isolated='esm', esm_bc='bc3'
    fcp_mu = -0.349338,
 /
 &electrons
    mixing_beta = 0.3
 /
 &ions
 ion_dynamics = 'bfgs'
 /
ATOMIC_SPECIES
 Al  26.981538   Al.pbe-n-van.UPF
CELL_PARAMETERS angstrom
     5.7269000760    0.0000000000    0.0000000000
     0.0000000000    5.7269000760    0.0000000000
     0.0000000000    0.0000000000   11.9999975199
ATOMIC_POSITIONS angstrom
Al   0.0000000000    0.0000000000    0.0000000000
Al   2.8634500380    0.0000000000    0.0000000000
Al   0.0000000000    2.8634500380    0.0000000000
Al   2.8634500380    2.8634500380    0.0000000000
 K_POINTS automatic
 6 6 1 1 1 0
EOF
$ECHO "  running the constant-mu calculation for Al(001) with ESM bc3 (vacuum-slab-metal)"
$ECHO "  (target mu = -0.5V vs pzc)...\c"
$PW_COMMAND < Al001_bc3_vm05.in > Al001_bc3_vm05.out
check_failure $?
$ECHO " done"
mv $TMP_DIR/Al001_bc3_vm05.esm1 .

# stress calculation for graphene with PBC (slab-slab-slab)
cat > graphene_pbc.in << EOF
 &control
    calculation = 'scf',
    restart_mode='from_scratch',
    prefix='graphene_pbc',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor = .true.,
    tstress = .true.,
 /
 &system
    ibrav = 0,
    nat = 2, ntyp = 1,
    ecutwfc = 36.0, ecutrho = 144.0,
    occupations = 'smearing', smearing = 'mp', degauss = 0.03,
    assume_isolated = 'none',  esm_bc = 'pbc'
 /
 &electrons
    mixing_beta = 0.7, conv_thr = 1.0d-8
 /
ATOMIC_SPECIES
C  12.0107  C.pz-van_ak.UPF
CELL_PARAMETERS angstrom
     2.6458850000    0.0000000000    0.0000000000
    -1.3229425000    2.2914025571    0.0000000000
     0.0000000000    0.0000000000    5.2917700000
ATOMIC_POSITIONS angstrom
C    0.0000000000    0.0000000000    0.0000000000
C    0.0000000000    1.5276024985    0.0000000000
K_POINTS {automatic}
12 12 1 0 0 0
EOF
$ECHO "  running the stress calculation for graphene with PBC (slab-slab-slab)"
$PW_COMMAND < graphene_pbc.in > graphene_pbc.out
check_failure $?
$ECHO " done"

# stress calculation for graphene with ESM bc1 (vacuum-slab-vacuum)
cat > graphene_bc1.in << EOF
 &control
    calculation = 'scf',
    restart_mode='from_scratch',
    prefix='graphene_bc1',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor = .true.,
    tstress = .true.,
 /
 &system
    ibrav = 0,
    nat = 2, ntyp = 1,
    ecutwfc = 36.0, ecutrho = 144.0,
    occupations = 'smearing', smearing = 'mp', degauss = 0.03,
    assume_isolated = 'esm',  esm_bc = 'bc1'
 /
 &electrons
    mixing_beta = 0.7, conv_thr = 1.0d-8
 /
ATOMIC_SPECIES
C  12.0107  C.pz-van_ak.UPF
CELL_PARAMETERS angstrom
     2.6458850000    0.0000000000    0.0000000000
    -1.3229425000    2.2914025571    0.0000000000
     0.0000000000    0.0000000000   16.0000000000 
ATOMIC_POSITIONS angstrom
C    0.0000000000    0.0000000000    0.0000000000
C    0.0000000000    1.5276024985    0.0000000000
K_POINTS {automatic}
12 12 1 0 0 0
EOF
$ECHO "  running the stress calculation for graphene with BC1 (vacuum-slab-vacuum)"
$PW_COMMAND < graphene_bc1.in > graphene_bc1.out
check_failure $?
$ECHO " done"
mv $TMP_DIR/graphene_bc1.esm1 .

# stress calculation for graphene with ESM bc2 (metal-slab-metal)
cat > graphene_bc2.in << EOF
 &control
    calculation = 'scf',
    restart_mode='from_scratch',
    prefix='graphene_bc2',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor = .true.,
    tstress = .true.,
 /
 &system
    ibrav = 0,
    nat = 2, ntyp = 1,
    ecutwfc = 36.0, ecutrho = 144.0,
    occupations = 'smearing', smearing = 'mp', degauss = 0.03,
    assume_isolated = 'esm',  esm_bc = 'bc2'
 /
 &electrons
     mixing_beta = 0.7, conv_thr = 1.0d-8
 /
ATOMIC_SPECIES
C  12.0107  C.pz-van_ak.UPF
CELL_PARAMETERS angstrom
     2.6458850000    0.0000000000    0.0000000000
    -1.3229425000    2.2914025571    0.0000000000
     0.0000000000    0.0000000000   16.0000000000 
ATOMIC_POSITIONS angstrom
C    0.0000000000    0.0000000000    0.0000000000
C    0.0000000000    1.5276024985    0.0000000000
K_POINTS {automatic}
12 12 1 0 0 0
EOF
$ECHO "  running the stress calculation for graphene with BC2 (metal-slab-metal)"
$PW_COMMAND < graphene_bc2.in > graphene_bc2.out
check_failure $?
$ECHO " done"
mv $TMP_DIR/graphene_bc2.esm1 .


# stress calculation for graphene with ESM bc3 (vacuum-slab-metal)
cat > graphene_bc3.in << EOF
 &control
    calculation = 'scf',
    restart_mode='from_scratch',
    prefix='graphene_bc3',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor = .true.,
    tstress = .true.,
 /
 &system
    ibrav = 0,
    nat = 2, ntyp = 1,
    ecutwfc = 36.0, ecutrho = 144.0,
    occupations = 'smearing', smearing = 'mp', degauss = 0.03,
    assume_isolated = 'esm',  esm_bc = 'bc3'
 /
 &electrons
    mixing_beta = 0.7, conv_thr = 1.0d-8
 /
ATOMIC_SPECIES
C  12.0107  C.pz-van_ak.UPF
CELL_PARAMETERS angstrom
     2.6458850000    0.0000000000    0.0000000000
    -1.3229425000    2.2914025571    0.0000000000
     0.0000000000    0.0000000000   16.0000000000 
ATOMIC_POSITIONS angstrom
C    0.0000000000    0.0000000000    0.0000000000
C    0.0000000000    1.5276024985    0.0000000000
K_POINTS {automatic}
12 12 1 0 0 0
EOF
$ECHO "  running the stress calculation for graphene with BC3 (vacuum-slab-metal)"
$PW_COMMAND < graphene_bc3.in > graphene_bc3.out
check_failure $?
$ECHO " done"
mv $TMP_DIR/graphene_bc3.esm1 .


# vc-relax calculation for graphene with ESM bc1 (vacuum-slab-vacuum)
# Angle of lattice vector starts from 117 degree, and it will be optimized to 
# 120 degree.

cat > graphene_bc1_vc-relax.in << EOF
 &control
    calculation = 'vc-relax',
    restart_mode='from_scratch',
    prefix='graphene_bc1_vc-relax',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor = .true.,
    tstress = .true.,
 /
 &system
    ibrav = 0,
    nat = 2, ntyp = 1,
    ecutwfc = 36.0, ecutrho = 144.0,
    occupations = 'smearing', smearing = 'mp', degauss = 0.03,
    assume_isolated = 'esm', esm_bc = 'bc1',
 /
 &electrons
    mixing_beta = 0.7, conv_thr = 1.0d-8
 /
 &ions
    ion_dynamics = 'bfgs'
 /
 &cell
    cell_dofree="2Dxy"
 /
ATOMIC_SPECIES
C  12.0107  C.pz-van_ak.UPF
CELL_PARAMETERS angstrom
     2.6458850000    0.0000000000    0.0000000000
    -1.1906482500    2.3628520357    0.0000000000
     0.0000000000    0.0000000000   16.0000000000
ATOMIC_POSITIONS angstrom
C    0.0000000000    0.0000000000    0.0000000000
C    0.0000000000    1.5276024985    0.0000000000
K_POINTS {automatic}
12 12 1 0 0 0
EOF
$ECHO "  running the vc-relax calculation for graphene with BC1 (vacuum-slab-vacuum)"
$PW_COMMAND < graphene_bc1_vc-relax.in > graphene_bc1_vc-relax.out
check_failure $?
$ECHO " done"
mv $TMP_DIR/graphene_bc1_vc-relax.esm1 .


# vc-relax calculation for graphene with ESM bc3 (vacuum-slab-metal) + charged
# Angle of lattice vector starts from 117 degree, and it will be optimized to 
# 120 degree.
cat > graphene_bc3_vc-relax_p002.in << EOF
 &control
    calculation = 'vc-relax',
    restart_mode='from_scratch',
    prefix='graphene_bc3_vc-relax_p002',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor = .true.,
    tstress = .true.,
 /
 &system
    ibrav = 0,
    nat = 2, ntyp = 1,
    ecutwfc = 36.0, ecutrho = 144.0,
    occupations = 'smearing', smearing = 'mp', degauss = 0.03,
    assume_isolated = 'esm', esm_bc = 'bc3',
    tot_charge = 0.02,
 /
 &electrons
    mixing_beta = 0.7, conv_thr = 1.0d-8
 /
 &ions
    ion_dynamics = 'bfgs'
 /
 &cell
    cell_dofree="2Dxy"
 /
ATOMIC_SPECIES
C  12.0107  C.pz-van_ak.UPF
CELL_PARAMETERS angstrom
     2.6458850000    0.0000000000    0.0000000000
    -1.1906482500    2.3628520357    0.0000000000
     0.0000000000    0.0000000000   16.0000000000
ATOMIC_POSITIONS angstrom
C    0.0000000000    0.0000000000    0.0000000000
C    0.0000000000    1.5276024985    0.0000000000
K_POINTS {automatic}
12 12 1 0 0 0
EOF
$ECHO "  running the vc-relax calculation for graphene with BC3 (vacuum-slab-metal) + charged"
$PW_COMMAND < graphene_bc3_vc-relax_p002.in > graphene_bc3_vc-relax_p002.out
check_failure $?
$ECHO " done"
mv $TMP_DIR/graphene_bc3_vc-relax_p002.esm1 .


# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR: done"
