#!/bin/sh
# the next line restarts using tclsh \
exec tclsh "$0" "$@"

set basedir   [file normalize [file dirname [info script]]]
set sourcedir [file join $basedir helpdoc.d]

source [file join $sourcedir helpdoc.tcl]

# custom XSLTPROC program
#set ::helpdoc::xsltproc /path/to/xsltproc

#
# MAIN
#

set usage "
    Usage: $argv0 \[-version value\] file1.def ?file2.def? ...
"

if { $argc < 1 } {
    puts stderr $usage
    exit 1
}

set options {
    {version.arg {} "Quantum ESPRESSO version number"}
}
   
set argv_orig $argv
array set opt [::cmdline::getoptions argv $options $usage]
	       
if { [llength $::argv] == 0 } {
        puts stderr "
### no deffile specified on the command line:  [concat $::argv0 $::argv_orig]
"
        exit 1
}


# MAKE-IT-ALL

::helpdoc::process $argv
