#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use pw.x to calculate the total energy"
$ECHO "and the band structure of fcc-Pt with a fully relativistic "
$ECHO "pseudo-potential including spin-orbit coupling."

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x"
PSEUDO_LIST="Pt.rel-pz-n-rrkjus.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE \
                http://www.quantum-espresso.org/pseudo/1.3/UPF/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x as: $PW_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"

# self-consistent calculation
cat > pt.scf.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>

<input calculation="scf" prefix="Pt">

	<cell type="qecell">
		<qecell ibrav="2" alat="7.42">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="1">
		<specie name="Pt">
			<property name="mass">
				<real>0.0</real>
			</property>
			<property name="pseudofile">
				<string>Pt.rel-pz-n-rrkjus.UPF</string>
			</property>
			<property name="starting_magnetization">
				<real>0.0</real>
			</property>
		</specie>
	</atomic_species>

	<atomic_list units="alat" nat="1" >
		<atom name="Pt">
			<position>
				<real rank="1" n1="3">
					0.0000000   0.00000000   0.0
				</real>
			</position>
		</atom>						
	</atomic_list>		
	
	
	<field name="InputOutput">

		<parameter name="restart_mode">
			<string>
				from_scratch
			</string>
		</parameter>

		<parameter name="pseudo_dir">
			<string>
				$PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
				$TMP_DIR/
			</string>
		</parameter>
		
		<parameter name="tprnfor">
			<logical>
				true
			</logical>
		</parameter>
		
		<parameter name="tstress">
			<logical>
				true
			</logical>
		</parameter>		
		
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				30.0
			</real>
		</parameter>
		
		<parameter name="ecutrho">
			<real>
				250.0
			</real>
		</parameter>
		
		<parameter name="mixing_beta">
			<real>
				0.7
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.0d-8
			</real>
		</parameter>
		
	</field>
	
	<field name="Options">

		<parameter name="occupations">
			<string>
				smearing
			</string>
		</parameter>
		
		<parameter name="smearing">
			<string>
				mp
			</string>
		</parameter>
		
		<parameter name="degauss">
			<real>
				0.02
			</real>
		</parameter>
		
		<parameter name="noncolin">
			<logical>
				true
			</logical>
		</parameter>
		
		<parameter name="lspinorb">
			<logical>
				true
			</logical>
		</parameter>
		
	</field>	
	
	<k_points type="automatic">
		<mesh>
			<integer rank="1" n1="6">
				4 4 4 1 1 1
			</integer>
		</mesh> 
	</k_points>

</input>
EOF
$ECHO "  running the scf calculation for Pt with spin-orbit coupling...\c"
$PW_COMMAND < pt.scf.xml > pt.scf.out
check_failure $?
$ECHO " done"

# a non self-consistent calculation
cat > pt.nscf.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>


<input calculation="nscf" prefix="Pt">

	<cell type="qecell">
		<qecell ibrav="2" alat="7.42">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="1">
		<specie name="Pt">
			<property name="mass">
				<real>0.0</real>
			</property>
			<property name="pseudofile">
				<string>Pt.rel-pz-n-rrkjus.UPF</string>
			</property>
			<property name="starting_magnetization">
				<real>0.0</real>
			</property>	
		</specie>
	</atomic_species>

	<atomic_list units="alat" nat="1" >
		<atom name="Pt">
			<position>
				<real rank="1" n1="3">
					0.0000000   0.00000000   0.0
				</real>
			</position>
		</atom>						
	</atomic_list>		
	
	
	<field name="InputOutput">

		<parameter name="restart_mode">
			<string>
				from_scratch
			</string>
		</parameter>

		<parameter name="pseudo_dir">
			<string>
				$PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
				$TMP_DIR/
			</string>
		</parameter>
		
		<parameter name="tprnfor">
			<logical>
				true
			</logical>
		</parameter>		
		
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				30.0
			</real>
		</parameter>
		
		<parameter name="ecutrho">
			<real>
				250.0
			</real>
		</parameter>
		
		<parameter name="mixing_beta">
			<real>
				0.7
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.0d-8
			</real>
		</parameter>
		
	</field>
	
	<field name="Options">

		<parameter name="occupations">
			<string>
				smearing
			</string>
		</parameter>
		
		<parameter name="smearing">
			<string>
				mp
			</string>
		</parameter>
		
		<parameter name="degauss">
			<real>
				0.02
			</real>
		</parameter>
		
		<parameter name="noncolin">
			<logical>
				true
			</logical>
		</parameter>
		
		<parameter name="lspinorb">
			<logical>
				true
			</logical>
		</parameter>
		
	</field>	
	
	<k_points type="tpiba">
		<mesh npoints="8">
			<real rank="2" n1="4" n2="8">
				0.0 0.0 0.0 1.0
				0.1 0.0 0.0 1.0
				1.0 0.0 0.0 1.0
				0.4 0.2 0.1 1.0
				0.4 0.4 0.0 1.0
				0.4 0.4 0.4 1.0
				0.5 0.5 0.5 1.0
				0.75 0.75 0.0 1.0
			</real>
		</mesh> 
	</k_points>

</input>
EOF
$ECHO "  running the non-scf calculation for Pt with spin-orbit coupling...\c"
$PW_COMMAND < pt.nscf.xml > pt.nscf.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR: done"
