#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname

echo
echo "run all ESM examples: starting"

# run all examples
for example in run_example_ESM run_example_FCP run_example_GCSCF;
do 
    if test -f $example
    then
        sh $example
    fi
done

echo
echo "run all ESM examples: done"
