#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

# function to test the exit status of a job
. ../check_failure.sh

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use gipaw.x to calculate the magnetic"
$ECHO "susceptibility and NMR chemical shift of fcc Si, diamond, and of"
$ECHO "two molecules: CH4 and C2H4"

# set the needed environment variables
. ../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x gipaw.x"
PSEUDO_LIST="C.pz-tm-gipaw.upf  H.pz-tm-gipaw.upf  Si.pz-tm-gipaw.upf"
PSEUDO_DIR=$EXAMPLE_DIR/pseudo

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
GIPAW_COMMAND="$PARA_PREFIX $BIN_DIR/gipaw.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x as: $PW_COMMAND"
$ECHO "  running gipaw.x as: $GIPAW_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"

########################################################################
# fcc silicon
########################################################################
# self-consistent calculation
cat > si.scf.in << EOF
 &control
    calculation = 'scf'
    restart_mode = 'from_scratch'
    prefix = 'si'
    tstress = .true.
    tprnfor = .true.
    pseudo_dir = '$PSEUDO_DIR/'
    outdir = '$TMP_DIR/'
    wf_collect = .true.
 /
 &system
    ibrav = 2
    celldm(1) = 10.20
    nat = 2 
    ntyp = 1
    ecutwfc = 18.0
    spline_ps = .true.
 /
 &electrons
    diagonalization = 'david'
    mixing_mode = 'plain'
    mixing_beta = 0.7
    conv_thr =  1.0d-14
 /
ATOMIC_SPECIES
Si  28.086  Si.pz-tm-gipaw.upf

ATOMIC_POSITIONS crystal
Si   0.00   0.00   0.00
Si   0.25   0.25   0.25

K_POINTS automatic
6  6  6  0 0 0
EOF
$ECHO "  running the scf calculation for Si...\c"
$PW_COMMAND < si.scf.in > si.scf.out
check_failure $?
$ECHO " done"

# NMR
cat > si.nmr.in << EOF
&inputgipaw
	job = 'nmr'
	prefix = 'si'
	tmp_dir = '$TMP_DIR/'
	iverbosity = 1
        q_gipaw = 0.01
        spline_ps = .true.
	use_nmr_macroscopic_shape = .true.
/
EOF
$ECHO "  running the magnetic response calculation for Si...\c"
$GIPAW_COMMAND < si.nmr.in > si.nmr.out
check_failure $?
$ECHO " done"



########################################################################
# diamond
########################################################################
# self-consistent calculation
cat > c.scf.in << EOF
 &control
    calculation = 'scf'
    restart_mode = 'from_scratch'
    prefix = 'c'
    tstress = .true.
    tprnfor = .true.
    pseudo_dir = '$PSEUDO_DIR/'
    outdir = '$TMP_DIR/'
    wf_collect = .true.
 /
 &system
    ibrav = 2
    celldm(1) = 6.6100
    nat = 2 
    ntyp = 1
    ecutwfc = 60.0
    spline_ps = .true.
 /
 &electrons
    diagonalization = 'david'
    mixing_mode = 'plain'
    mixing_beta = 0.7
    conv_thr =  1.0d-14
 /
ATOMIC_SPECIES
C  12.000  C.pz-tm-gipaw.upf

ATOMIC_POSITIONS crystal
C   0.00   0.00   0.00
C   0.25   0.25   0.25

K_POINTS automatic
6 6 6  0 0 0
EOF
$ECHO "  running the scf calculation for C...\c"
$PW_COMMAND < c.scf.in > c.scf.out
check_failure $?
$ECHO " done"

# NMR
cat > c.nmr.in << EOF
&inputgipaw
	job = 'nmr'
	prefix = 'c'
	tmp_dir = '$TMP_DIR/'
        isolve = 0
	iverbosity = 1
        q_gipaw = 0.01
        spline_ps = .true.
	use_nmr_macroscopic_shape = .true.
/
EOF
$ECHO "  running the magnetic response calculation for C...\c"
$GIPAW_COMMAND < c.nmr.in > c.nmr.out
check_failure $?
$ECHO " done"



########################################################################
# CH4
########################################################################
# self-consistent calculation
cat > ch4.scf.in << EOF
 &control
    calculation = 'scf'
    restart_mode = 'from_scratch'
    prefix = 'ch4'
    tstress = .false.
    tprnfor = .true.
    pseudo_dir = '$PSEUDO_DIR/'
    outdir = '$TMP_DIR/'
    wf_collect = .true.
 /
 &system
    ibrav = 1
    celldm(1) = 10.39349
    nat = 5 
    ntyp = 2
    ecutwfc = 40.0
    spline_ps = .true.
 /
 &electrons
    diagonalization = 'david'
    mixing_mode = 'plain'
    mixing_beta = 0.7
    conv_thr =  1.0d-14
 /
 &ions
    ion_dynamics = 'none'
 /
ATOMIC_SPECIES
C  12.000  C.pz-tm-gipaw.upf
H   2.000  H.pz-tm-gipaw.upf

ATOMIC_POSITIONS
C        0.000000000   0.000000000   0.000000000
H        0.115675895   0.115675895   0.115675895
H        0.115675895  -0.115675895  -0.115675895
H       -0.115675895  -0.115675895   0.115675895
H       -0.115675895   0.115675895  -0.115675895

K_POINTS automatic
2 2 2   1 1 1
EOF
$ECHO "  running the scf calculation for CH4...\c"
$PW_COMMAND < ch4.scf.in > ch4.scf.out
check_failure $?
$ECHO " done"

# NMR
cat > ch4.nmr.in << EOF
&inputgipaw
	job = 'nmr'
	prefix = 'ch4'
	tmp_dir = '$TMP_DIR/'
        isolve = 0
	iverbosity = 1
        q_gipaw = 0.01
        spline_ps = .true.
	use_nmr_macroscopic_shape = .true.
/
EOF
$ECHO "  running the magnetic response calculation for CH4...\c"
$GIPAW_COMMAND < ch4.nmr.in > ch4.nmr.out
check_failure $?
$ECHO " done"



########################################################################
# C2H4
########################################################################
# self-consistent calculation
cat > c2h4.scf.in << EOF
 &control
    calculation = 'scf'
    restart_mode = 'from_scratch'
    prefix = 'c2h4'
    tstress = .false.
    tprnfor = .true.
    pseudo_dir = '$PSEUDO_DIR/'
    outdir = '$TMP_DIR/'
    wf_collect = .true.
 /
 &system
    ibrav = 1
    celldm(1) = 10.39349
    nat = 6 
    ntyp = 2
    ecutwfc = 40.0
    spline_ps = .true.
 /
 &electrons
    diagonalization = 'david'
    mixing_mode = 'plain'
    mixing_beta = 0.7
    conv_thr =  1.0d-14
 /
 &ions
    ion_dynamics = 'bfgs'
 /
ATOMIC_SPECIES
C  12.000  C.pz-tm-gipaw.upf
H   2.000  H.pz-tm-gipaw.upf

ATOMIC_POSITIONS
C        1.378952955   0.000000000   0.000000000
C       -1.378952955   0.000000000   0.000000000
H        2.273848630   1.829891830   0.000000000
H        2.273848630  -1.829891830   0.000000000
H       -2.273848630   1.829891830   0.000000000
H       -2.273848630  -1.829891830   0.000000000

K_POINTS automatic
2 2 2   1 1 1
EOF
$ECHO "  running the scf calculation for C2H4...\c"
$PW_COMMAND < c2h4.scf.in > c2h4.scf.out
check_failure $?
$ECHO " done"

# NMR
cat > c2h4.nmr.in << EOF
&inputgipaw
	job = 'nmr'
	prefix = 'c2h4'
	tmp_dir = '$TMP_DIR/'
        isolve = 0
	iverbosity = 1
        q_gipaw = 0.01
        spline_ps = .true.
	use_nmr_macroscopic_shape = .true.
/
EOF
$ECHO "  running the magnetic response calculation for C2H4...\c"
$GIPAW_COMMAND < c2h4.nmr.in > c2h4.nmr.out
check_failure $?
$ECHO " done"


########################################################################
$ECHO
$ECHO "$EXAMPLE_DIR : done"
