#!/bin/bash

NCONF=11
CALCLIST="NC1 NC2 US1 US2 PAW1 PAW2 PAW3 PAW4"

# collect data in files named "ps_$calc.dat"
for calc in $CALCLIST; do
$ECHO "# `date`" > ps_$calc.dat
$ECHO "2S: AE PS AE-PS   2P: AE PS AE-PS" > ps_$calc.dat
$ECHO "    pseudo: $calc,\toccupancy:\c"
for ((i=0;((i<NCONF));i++)); do
    occ=$(dc -e "2k 2 $((NCONF-1))/ $i* _1 * 2+ p")

    $ECHO "\t$occ\c"
    LINE="`grep '     [12] [01]     2[SP]   1' ld1.$calc.tst_$occ.out |tail -n 2`"
    $ECHO $occ $LINE|awk '{print $1,$7,"\t",$8,"\t",$9,"\t",$15,"\t",$16,"\t",$17}' >> ps_$calc.dat

done
$ECHO
done

for calc in $CALCLIST; do
PLOTFILE="gnuplot.ps_$calc.in"
DATA="ps_$calc.dat"
$ECHO "set terminal postscript eps" >  $PLOTFILE
$ECHO "set output 'ps_$calc.eps'"   >> $PLOTFILE
$ECHO "set style data lp"           >> $PLOTFILE
$ECHO "set yrange [-10:2]"          >> $PLOTFILE
$ECHO "set xlabel 'occupancy of 2S'">> $PLOTFILE
$ECHO "set ylabel 'PS and AE energy (Ry) and Delta[PS-AE] (mRy)'">> $PLOTFILE
$ECHO "set multiplot"               >> $PLOTFILE
$ECHO "set title '$calc: 2S'"       >> $PLOTFILE
$ECHO "set origin 0,0"              >> $PLOTFILE
$ECHO "set size .5,1.0"             >> $PLOTFILE
$ECHO "p '$DATA' u 1:2 t 'AE', '$DATA' u 1:3 t 'PS', '$DATA' u 1:(-1000*\$4) t 'Delta', 0 t ''">>$PLOTFILE
$ECHO "set title '$calc: 2P'"       >> $PLOTFILE
$ECHO "set origin .5,0"             >> $PLOTFILE
$ECHO "set size .5,1.0"             >> $PLOTFILE
$ECHO "p '$DATA' u 1:5 t 'AE', '$DATA' u 1:6 t 'PS', '$DATA' u 1:(-1000*\$7) t 'Delta', 0 t ''">>$PLOTFILE
gnuplot "$PLOTFILE"
done