#!/bin/sh

###############################################################################
##
##  HIGH VERBOSITY EXAMPLE
##
###############################################################################

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example calculates the phonon modes of relativistic Au" 
$ECHO "at the gamma and X points with PAW in the noncollinear and "
$ECHO "spin-orbit case."
$ECHO

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x ph.x"
PSEUDO_LIST="Au.rel-pz-kjpaw.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
PH_COMMAND="$PARA_PREFIX $BIN_DIR/ph.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x     as: $PW_COMMAND"
$ECHO "  running ph.x     as: $PH_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/gold*
rm -rf $TMP_DIR/_ph0/gold*
$ECHO " done"

# self-consistent calculation for Au with PAW-PP
cat > Au.scf_pz.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    prefix='gold',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
 /
 &system
    ibrav = 2, celldm(1) =7.666, nat=  1, ntyp= 1,
    noncolin=.true.,
    lspinorb=.true.,
    occupations='smearing',
    smearing='mv',
    degauss=0.04,
    ecutwfc = 35.0
    ecutrho = 300.0
 /
 &electrons
    mixing_beta = 0.7
    conv_thr =  1.0d-9
 /
ATOMIC_SPECIES
Au   0.0  Au.rel-pz-kjpaw.UPF
ATOMIC_POSITIONS (alat)
 Au  0.00 0.00 0.00
K_POINTS AUTOMATIC
4 4 4 1 1 1
EOF
$ECHO "  running the scf calculation for Au with PAW and spin-orbit...\c"
$PW_COMMAND < Au.scf_pz.in > Au.scf_pz.out
check_failure $?
$ECHO " done"

# phonon calculation at G
cat > Au.phG_pz.in << EOF
phonons of Au at Gamma
 &inputph
  tr2_ph=1.0d-14,
  prefix='gold',
  fildyn='Aug.dyn',
  outdir='$TMP_DIR/'
 /
0.0 0.0 0.0
EOF
$ECHO "  running ph.x for Au at Gamma with PAW and spin-orbit...\c"
$PH_COMMAND < Au.phG_pz.in > Au.phG_pz.out
check_failure $?
$ECHO " done"

# phonon calculation at X
cat > Au.phX_pz.in << EOF
phonons of Au at X
 &inputph
  tr2_ph=1.0d-14,
  prefix='gold',
  fildyn='AuX.dyn',
  outdir='$TMP_DIR/'
 /
1.0 0.0 0.0
EOF
$ECHO "  running ph.x for Au at X with PAW and spin-orbit...\c"
$PH_COMMAND < Au.phX_pz.in > Au.phX_pz.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR: done"
