!
! Copyright (C) 2003-2019 Quantum ESPRESSO group
! This file is distributed under the terms of the
! GNU General Public License. See the file `License'
! in the root directory of the present distribution,
! or http://www.gnu.org/copyleft/gpl.txt .
!

   INTEGER LAX_DESC_SIZE
   PARAMETER (LAX_DESC_SIZE=32)
   INTEGER LAX_DESC_IR
   PARAMETER (LAX_DESC_IR=1)
   INTEGER LAX_DESC_NR
   PARAMETER (LAX_DESC_NR=2)
   INTEGER LAX_DESC_IC
   PARAMETER (LAX_DESC_IC=3)
   INTEGER LAX_DESC_NC
   PARAMETER (LAX_DESC_NC=4)
   INTEGER LAX_DESC_NRCX
   PARAMETER (LAX_DESC_NRCX=5)
   INTEGER LAX_DESC_ACTIVE_NODE
   PARAMETER (LAX_DESC_ACTIVE_NODE=6)
   INTEGER LAX_DESC_N
   PARAMETER (LAX_DESC_N=7)
   INTEGER LAX_DESC_NX
   PARAMETER (LAX_DESC_NX=8)
   INTEGER LAX_DESC_NPR
   PARAMETER (LAX_DESC_NPR=9)
   INTEGER LAX_DESC_NPC
   PARAMETER (LAX_DESC_NPC=10)
   INTEGER LAX_DESC_MYR
   PARAMETER (LAX_DESC_MYR=11)
   INTEGER LAX_DESC_MYC
   PARAMETER (LAX_DESC_MYC=12)
   INTEGER LAX_DESC_COMM
   PARAMETER (LAX_DESC_COMM=13)
   INTEGER LAX_DESC_CNTX
   PARAMETER (LAX_DESC_CNTX=14)
   INTEGER LAX_DESC_MYPE
   PARAMETER (LAX_DESC_MYPE=15)
   INTEGER LAX_DESC_NRL
   PARAMETER (LAX_DESC_NRL=16)
   INTEGER LAX_DESC_NRLX
   PARAMETER (LAX_DESC_NRLX=17)
   !
   INTEGER LAX_STATUS_SIZE
   PARAMETER (LAX_STATUS_SIZE=32)
   INTEGER LAX_STATUS_NPROC        ! nproc_ortho
   PARAMETER (LAX_STATUS_NPROC=1)
   INTEGER LAX_STATUS_LEG          ! leg_ortho
   PARAMETER (LAX_STATUS_LEG=2)
   INTEGER LAX_STATUS_NP1          ! np_ortho(1)
   PARAMETER (LAX_STATUS_NP1=3)
   INTEGER LAX_STATUS_NP2          ! np_ortho(2)
   PARAMETER (LAX_STATUS_NP2=4)
   INTEGER LAX_STATUS_ME1          ! me_ortho(1)
   PARAMETER (LAX_STATUS_ME1=5)
   INTEGER LAX_STATUS_ME2          ! me_ortho(2)
   PARAMETER (LAX_STATUS_ME2=6)
   INTEGER LAX_STATUS_COMM         ! ortho_comm
   PARAMETER (LAX_STATUS_COMM=7)
   INTEGER LAX_STATUS_ROWCOMM      ! ortho_row_comm
   PARAMETER (LAX_STATUS_ROWCOMM=8)
   INTEGER LAX_STATUS_COLCOMM      ! ortho_col_comm
   PARAMETER (LAX_STATUS_COLCOMM=9)
   INTEGER LAX_STATUS_COMMID       ! ortho_comm_id
   PARAMETER (LAX_STATUS_COMMID=10)
   INTEGER LAX_STATUS_PARENTCOMM   ! ortho_parent_comm
   PARAMETER (LAX_STATUS_PARENTCOMM=11)
   INTEGER LAX_STATUS_ORTHOCNTX    ! ortho_cntx
   PARAMETER (LAX_STATUS_ORTHOCNTX=12)
   INTEGER LAX_STATUS_DISTDIAG     ! do_distr_diag_inside_bgrp
   PARAMETER (LAX_STATUS_DISTDIAG=13)
