#!/bin/bash

if [ ! -d bin ]; then
mkdir bin
fi

cd ./Phonon_DOS

make

rm -f *.o

cd ../Debye

make 

rm -f *.o

cd ../SRC

make 

rm -f *.o

cd ../bin

ln -s  ../Phonon_DOS/tetra.x       tetra.x 
ln -s  ../Phonon_DOS/phonon_dos.x  phonon_dos.x 
ln -s  ../Debye/Debye.x            Debye.x 

ln -s  ../SRC/Atom_projected_properties.x Atom_projected_properties.x
ln -s  ../SRC/F_QHA.x F_QHA.x
ln -s  ../SRC/Ghost_DOS.x Ghost_DOS.x 
ln -s  ../SRC/Partial_phonon_DOS.x Partial_phonon_DOS.x
ln -s  ../SRC/Mean_square_displacement.x Mean_square_displacement.x
ln -s  ../SRC/atom_info.x  atom_info.x

cd ..



