#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use pioud.x to calculate an NVT"
$ECHO "graphene Path Integral Molecular Dynamics simulation"
$ECHO
$ECHO "!!! Beware: pioud.x DOES NOT READ FROM STANDARD INPUT"
$ECHO "!!! run as 'pioud.x -inp input_file_name > output_file_name'"
$ECHO
# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pioud.x"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# how to run executables
PIOUD_COMMAND="$PARA_PREFIX $BIN_DIR/pioud.x $PARA_POSTFIX"
$ECHO
$ECHO "  running Born-Oppenheimer PIOUD as: $PIOUD_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/pwscf*
$ECHO " done"

nbeadMD=4

# NEB calculation. Automatic choice of the climbing image.
cat > diamond.in << EOF
BEGIN
BEGIN_PIMD_INPUT
&dynamics
  restart_pimd=.false.
  nbeadMD=$nbeadMD
  nunitcells=1
  nblocks=4
  nstep_block=4
  iprint=1
  irun=4
  delt=0.2d0  !! for pioud, 41.32231 which is 1 fs in a.u., must be divided for sqrt(m_1)
  tempMD=300.d0
  gammaMD=0.21d0
  sigmacov=0.0d0
  delta_force=1.d-4
  delta_harm=5.d-3
  delta0=0.0d0
  delta0k=1.0d0
  delta0q=0.0d0
  yessecond=.true.
  yesturboq=.true.
/
END_PIMD_INPUT
BEGIN_PATH_INPUT
&PATH
  restart_mode      = 'from_scratch'
  string_method     = 'neb',
  nstep_path        = 20,
  ds                = 2.D0,
  opt_scheme        = "broyden",
  num_of_images     = $nbeadMD,
  k_max             = 0.3D0,
  k_min             = 0.2D0,
  CI_scheme         = "auto",
  path_thr          = 0.1D0,
/
END_PATH_INPUT
BEGIN_ENGINE_INPUT
&CONTROL
  prefix         = "diamond"
  outdir         = "$TMP_DIR",
  pseudo_dir     = "$PSEUDO_DIR",
/
&SYSTEM
    ibrav = 2 ,
    nosym_evc= .true.
    a=3.56,
    nat = 2,
    ntyp = 1,
    nspin=1,
    ecutwfc = 25.0,
    ecutrho = 120.0,
    nbnd = 15,
    occupations='smearing',
    smearing='fd'
    degauss=0.001,
/
&ELECTRONS
  conv_thr    = 1.D-8,
  mixing_beta = 0.3D0,
/
&IONS
/
ATOMIC_SPECIES
C    12.0107  C.pbe-van_bm.UPF
BEGIN_POSITIONS
FIRST_IMAGE
ATOMIC_POSITIONS crystal
C        0.0   0.0  0.000000000
C        0.25  0.25  0.25
LAST_IMAGE
ATOMIC_POSITIONS crystal
C        0.0   0.0  0.000000000
C        0.255   0.255  0.2550000000
END_POSITIONS
K_POINTS automatic
4 4 4 0 0 0
END_ENGINE_INPUT
END
EOF

$ECHO "  running Born-Oppenheimer pioud calculation... "
$PIOUD_COMMAND -inp diamond.in  > diamond.out
check_failure $?
$ECHO " done"

# clean TMP_DIR
#$ECHO "  cleaning $TMP_DIR...\c"
#rm -rf $TMP_DIR/pwscf*
#$ECHO " done"
