# Makefile for XSpectra
sinclude ../make.inc

# see comments in file tldeps for explanations
TLDEPS=pwlibs
include ../install/tldeps

all:
	( cd src ; $(MAKE) all || exit 1 )

clean :
	( cd src ; $(MAKE) clean )

doc:
	:

doc_clean:
	:

distclean: clean



