#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO
# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pioud.x"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# how to run executables
PIOUD_COMMAND="$PARA_PREFIX $BIN_DIR/pioud.x $PARA_POSTFIX"
$ECHO
$ECHO "  running Born-Oppenheimer PIOUD as: $PIOUD_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/pwscf*
$ECHO " done"

nbeadMD=50

# NEB calculation. Automatic choice of the climbing image.
cat > hy2.in << EOF
BEGIN
BEGIN_PIMD_INPUT
&dynamics
  restart_pimd=.false.
  nbeadMD=$nbeadMD
  nunitcells=1
  nblocks=25
  nstep_block=500
  iprint=2
  irun=4
  delt=0.9605819  !! for pioud, 41.32231 which is 1 fs in a.u., must be divided for sqrt(m_1)
  tempMD=80.d0
  gammaMD=0.0628062d0
  sigmacov=0.0d0
  delta_force=1.d-4
  delta_harm=5.d-3
  delta0=0.0d0
  delta0k=1.0d0
  delta0q=0.0d0
  yessecond=.true.
  yesturboq=.true.
/
END_PIMD_INPUT
BEGIN_PATH_INPUT
&PATH
  restart_mode      = 'from_scratch'
  string_method     = 'neb',
  nstep_path        = 20,
  ds                = 2.D0,
  opt_scheme        = "broyden",
  num_of_images     = $nbeadMD,
  k_max             = 0.3D0,
  k_min             = 0.2D0,
  CI_scheme         = "auto",
  path_thr          = 0.1D0,
/
END_PATH_INPUT
BEGIN_ENGINE_INPUT
&CONTROL
  prefix         = "hydro2"
  outdir         = "$TMP_DIR",
  pseudo_dir     = "$PSEUDO_DIR",
/
&SYSTEM
    ibrav = 7 ,
    nosym_evc = .true.
    a = 1.21,
    c = 3.08,
    nat = 2,
    ntyp = 1,
    nspin=1,
    ecutwfc = 50.0,
    ecutrho = 300.0,
    smearing='gaussian',
    occupations='smearing',
    degauss=0.01,
    nbnd=6
/
&ELECTRONS
    diagonalization='david',
    conv_thr = 1.d-8,
    mixing_mode = 'plain',
    mixing_beta = 0.3,
    electron_maxstep = 200
/
&IONS
/
ATOMIC_SPECIES
H    1.00784  H.pbe-rrkjus_psl.1.0.0.UPF
BEGIN_POSITIONS
FIRST_IMAGE
ATOMIC_POSITIONS angstrom
H 0.0 0.0 0.0
H 0.605  0.0 0.77
LAST_IMAGE
ATOMIC_POSITIONS angstrom
H 0.0 0.0 0.0
H 0.605  0.0 0.77
END_POSITIONS
K_POINTS automatic
27 27 27 0 0 0
END_ENGINE_INPUT
END
EOF

$ECHO "  running Born-Oppenheimer pioud calculation... "
$PIOUD_COMMAND -inp hy2.in  > hy2.out
check_failure $?
$ECHO " done"

# clean TMP_DIR
#$ECHO "  cleaning $TMP_DIR...\c"
#rm -rf $TMP_DIR/pwscf*
#$ECHO " done"
