#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether ECHO has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use pw.x to compute the equilibrium geometry"
$ECHO "of a simple molecule, CO, and of an Al (001) slab."
$ECHO "In the latter case the relaxation is performed in two ways:"
$ECHO "1) using the quasi-Newton BFGS algorithm"
$ECHO "2) using a damped dynamics algorithm."

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x"
PSEUDO_LIST=" O.pz-rrkjus.UPF C.pz-rrkjus.UPF Al.pz-vbc.UPF "


$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x as: $PW_COMMAND"
$ECHO

# self-consistent calculation
cat > co.rx.in << EOF
&CONTROL
  calculation  = "relax",
  prefix       = "CO",
  pseudo_dir   = "$PSEUDO_DIR",
  outdir       = "$TMP_DIR",
/
&SYSTEM
  ibrav     = 0,
  nat       = 2,
  ntyp      = 2,
  ecutwfc   = 24.D0,
  ecutrho   = 144.D0,
/
&ELECTRONS
  conv_thr    = 1.D-7,
  mixing_beta = 0.7D0,
/
&IONS
/
CELL_PARAMETERS bohr
12.0  0.0  0.0
 0.0 12.0  0.0
 0.0  0.0 12.0
ATOMIC_SPECIES
O  1.00  O.pz-rrkjus.UPF
C  1.00  C.pz-rrkjus.UPF
ATOMIC_POSITIONS {bohr}
C  2.256  0.0  0.0
O  0.000  0.0  0.0  0 0 0
K_POINTS {Gamma}
EOF
$ECHO "  running the geometry relaxation for CO...\c"
$PW_COMMAND < co.rx.in > co.rx.out
check_failure $?
$ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/CO*
$ECHO " done"

# self-consistent calculation
cat > al001.rx.in << EOF
&CONTROL
  calculation = "relax",
  pseudo_dir  = "$PSEUDO_DIR",
  prefix      = "Al"
  outdir      = "$TMP_DIR",
/
&SYSTEM
  ibrav       = 6,
  celldm(1)   = 5.3033D0,
  celldm(3)   = 8.D0,
  nat         = 7,
  ntyp        = 1,
  ecutwfc     = 12.D0,
  occupations = "smearing",
  smearing    = "marzari-vanderbilt",
  degauss     = 0.05D0,
/
&ELECTRONS
  conv_thr    = 1.D-6,
  mixing_beta = 0.3D0,
/
&IONS
  bfgs_ndim         = 3,
/
ATOMIC_SPECIES
Al  1.0  Al.pz-vbc.UPF
ATOMIC_POSITIONS
Al   0.5000000      0.5000000     -2.121320
Al   0.0000000      0.0000000     -1.414213
Al   0.5000000      0.5000000     -0.707107
Al   0.0000000      0.0000000      0.000000
Al   0.5000000      0.5000000      0.707107
Al   0.0000000      0.0000000      1.414213
Al   0.5000000      0.5000000      2.121320
K_POINTS
 3
 0.125  0.125  0.0  1.0
 0.125  0.375  0.0  2.0
 0.375  0.375  0.0  1.0
EOF
$ECHO "  running the geometry relaxation for Al (001) using BFGS...\c"
$PW_COMMAND < al001.rx.in > al001.rx.out
check_failure $?
$ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/Al*
$ECHO " done"

# self-consistent calculation
rm -f e eal ave p avec tv
cat > al001.mm.in << EOF
&CONTROL
  calculation = "relax",
  dt          = 30.D0,
  pseudo_dir  = "$PSEUDO_DIR",
  outdir      = "$TMP_DIR",
  prefix      = "Al"
/
&SYSTEM
  ibrav       = 6,
  celldm(1)   = 5.3033D0,
  celldm(3)   = 8.D0,
  nat         = 7,
  ntyp        = 1,
  ecutwfc     = 12.D0,
  occupations = "smearing",
  smearing    = "marzari-vanderbilt",
  degauss     = 0.05D0,
/
&ELECTRONS
  conv_thr    = 1.D-7,
  mixing_beta = 0.3D0,
/
&IONS
  ion_dynamics      = "damp",
  pot_extrapolation = "second_order",
  wfc_extrapolation = "second_order",
/
ATOMIC_SPECIES
Al  1.D0  Al.pz-vbc.UPF
ATOMIC_POSITIONS
Al   0.5000000      0.5000000     -2.121320
Al   0.0000000      0.0000000     -1.414213
Al   0.5000000      0.5000000     -0.707107
Al   0.0000000      0.0000000      0.000000
Al   0.5000000      0.5000000      0.707107
Al   0.0000000      0.0000000      1.414213
Al   0.5000000      0.5000000      2.121320
K_POINTS
 3
 0.125  0.125  0.0  1.0
 0.125  0.375  0.0  2.0
 0.375  0.375  0.0  1.0
EOF
$ECHO "  running the geometry relaxation for Al (001) using damped MD...\c"
$PW_COMMAND < al001.mm.in > al001.mm.out
check_failure $?
$ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/Al*
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR: done"
