#!/bin/sh

# function to test the exit status of a job
function check_failure() {
    # usage: check_failure $?
    if test $1 != 0; then
        $ECHO "Error condition encountered during test: exit status = $1"
        $ECHO "Aborting"
        exit 1
    fi
}

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "  This example shows how to run a meta-dynamics simulation (with both"
$ECHO "  pw.x and cp.x) to explore different conformations of a Si6H6 molecule."
$ECHO "  The first two simulations are performed at T=0 (pure conformational"
$ECHO "  search) while the third is performed at finite temperature (T=300 K)."

# set the needed environment variables
. ../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x cp.x"
PSEUDO_LIST="H.vbc.UPF Si.vbc.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
CP_COMMAND="$PARA_PREFIX $BIN_DIR/cp.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x as: $PW_COMMAND"
$ECHO "  running cp.x as: $CP_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"

cat > metadyn-pw.in << EOF
&CONTROL
  dt             = 15.D0,
  calculation    = "metadyn",
  prefix         = "metadyn-pw",
  outdir         = "$TMP_DIR",
  pseudo_dir     = "$PSEUDO_DIR",
  nstep          = 10,
  etot_conv_thr  = 2.D-4,
  forc_conv_thr  = 2.D-3,
/
&SYSTEM
  nosym          = .T.,
  ibrav          = 1,
  celldm(1)      = 14.D0,
  nat            = 10,
  ntyp           = 2,
  ecutwfc        = 12.D0,
/
&ELECTRONS
  conv_thr    = 1.D-7,
  mixing_beta = 0.4D0,
/
&IONS
  fe_step(1)        = 0.3D0,
  fe_step(2)        = 0.3D0,
  fe_step(3)        = 0.3D0,
  g_amplitude       = 0.01D0,
  fe_nstep          = 80,
  sw_nstep          = 5,
  ion_dynamics      = "damp",
  pot_extrapolation = "second_order",
  wfc_extrapolation = "second_order",
/
COLLECTIVE_VARS
3
"distance"  7   9
"distance"  8  10
"distance"  9  10
ATOMIC_SPECIES
H   1.0   H.vbc.UPF
Si  1.0  Si.vbc.UPF
ATOMIC_POSITIONS { angstrom }
H       -2.142881868   2.313383337   0.000000936
H        2.142881503   2.313381079  -0.000000356
H       -1.824140891  -1.744121628   1.250555964
H        1.824142509  -1.744123885   1.250554014
H       -1.824146745  -1.744124685  -1.250553179
H        1.824146636  -1.744127405  -1.250552673
Si      -1.081854060   1.199601786  -0.000000959
Si       1.081854851   1.199604160  -0.000001556
Si      -1.192213258  -1.124761111  -0.000001090
Si       1.192211325  -1.124755647  -0.000001100
K_POINTS gamma
EOF
$ECHO "  running meta-dynamics calculation ( T = 0 K ) with pw.x ...\c"
$PW_COMMAND < metadyn-pw.in > metadyn-pw.out
check_failure $?
$ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"

cat > metadyn-cp.in << EOF
&CONTROL
  dt             = 20.D0,
  calculation    = "metadyn",
  prefix         = "metadyn-cp",
  outdir         = "$TMP_DIR/",
  pseudo_dir     = "$PSEUDO_DIR/",
  nstep          = 10,
  iprint         = 50,
  etot_conv_thr  = 4.D-4,
  forc_conv_thr  = 4.D-3,
  restart_mode   = "from_scratch",
/
&SYSTEM
  ibrav     = 1,
  celldm(1) = 14.D0,
  nat       = 10,
  ntyp      = 2,
  ecutwfc   = 12.D0,
/
&ELECTRONS
  electron_dynamics = "damp",
  electron_damping  = 0.2D0,
  emass             = 1500.D0,
  ortho_max         = 250,
/
&IONS
  fe_step(1)   = 0.3D0,
  fe_step(2)   = 0.3D0,
  fe_step(3)   = 0.3D0,
  g_amplitude  = 0.01D0,
  fe_nstep     = 80,
  sw_nstep     = 5,
  ion_dynamics = "damp",
  ion_damping  = 0.005D0,
/
COLLECTIVE_VARS
3
"distance"  7   9
"distance"  8  10
"distance"  9  10
ATOMIC_SPECIES
H   1.0   H.vbc.UPF
Si  1.0  Si.vbc.UPF
ATOMIC_POSITIONS { angstrom }
H       -2.142881868   2.313383337   0.000000936
H        2.142881503   2.313381079  -0.000000356
H       -1.824140891  -1.744121628   1.250555964
H        1.824142509  -1.744123885   1.250554014
H       -1.824146745  -1.744124685  -1.250553179
H        1.824146636  -1.744127405  -1.250552673
Si      -1.081854060   1.199601786  -0.000000959
Si       1.081854851   1.199604160  -0.000001556
Si      -1.192213258  -1.124761111  -0.000001090
Si       1.192211325  -1.124755647  -0.000001100
EOF
$ECHO "  running meta-dynamics calculation ( T = 0 K ) with cp.x ...\c"
$CP_COMMAND < metadyn-cp.in > metadyn-cp.out
check_failure $?
$ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"

cat > metadyn-cp-T=300K.in << EOF
&CONTROL
  dt             = 10.D0,
  calculation    = "metadyn",
  prefix         = "metadyn-cp-T=300K",
  outdir         = "$TMP_DIR/",
  pseudo_dir     = "$PSEUDO_DIR/",
  nstep          = 10,
  iprint         = 50,
  restart_mode   = "from_scratch",
/
&SYSTEM
  ibrav     = 1,
  celldm(1) = 14.D0,
  nat       = 10,
  ntyp      = 2,
  ecutwfc   = 12.D0,
/
&ELECTRONS
  electron_dynamics = "damp",
  electron_damping  = 0.1D0,
  emass             = 250.D0,
  ortho_max         = 250,
/
&IONS
  fe_step(1)       = 0.3D0,
  fe_step(2)       = 0.3D0,
  fe_step(3)       = 0.3D0,
  g_amplitude      = 0.01D0,
  fe_nstep         = 150,
  sw_nstep         = 20,
  ion_dynamics     = "verlet",
  ion_temperature  = "nose",
  tempw            = 300.D0,
  fnosep           = 15.D0 30.D0 60.D0 90.D0,
  nhpcl            = 4,
  nhptyp           = 2,
  ndega            = -3,
/
COLLECTIVE_VARS
3
"distance"  7   9
"distance"  8  10
"distance"  9  10
ATOMIC_SPECIES
H   1.0   H.vbc.UPF
Si  1.0  Si.vbc.UPF
ATOMIC_POSITIONS { angstrom }
H      -2.0191043824      2.6351289099     -0.2633113733
H       2.2797056665      2.0772184560     -0.1691382538
H      -1.9413452936     -1.7079914789      1.3180731488
H       1.7561072281     -1.4806542743      1.4332125312
H      -1.9548316562     -2.0063417838     -0.9590467354
H       1.7780372781     -1.8826067153     -1.0609068540
Si     -0.9178665234      1.5237834357     -0.0941531972
Si      1.2089832543      1.0704132877     -0.3115309601
Si     -1.2781468640     -1.2087708390      0.0928809177
Si      1.0884612946     -1.2202229970      0.1139207771
EOF
$ECHO "  running meta-dynamics calculation ( T = 300 K ) with cp.x ...\c"
$CP_COMMAND < metadyn-cp-T=300K.in > metadyn-cp-T=300K.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR: done"
