#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to calculate electron-phonon interaction"
$ECHO "coefficients at X for fcc Al."

# set the needed environment variables
. ../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x ph.x"
PSEUDO_LIST="Al.vbc.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done
 
# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
PH_COMMAND="$PARA_PREFIX $BIN_DIR/ph.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x as: $PW_COMMAND"
$ECHO "  running ph.x as: $PH_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"

# self-consistent calculation
cat > al.scf.in << EOF
 &control
    calculation='scf'
    restart_mode='from_scratch',
    prefix='al',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
 /
 &system    
    ibrav=  2, celldm(1) =7.50, nat=  1, ntyp= 1,
    ecutwfc =16.0,
    occupations='smearing', smearing='methfessel-paxton', degauss=0.022
 /
 &electrons
    conv_thr =  1.0d-8
    mixing_beta= 0.7
 /
ATOMIC_SPECIES
 Al  26.98 Al.vbc.UPF
ATOMIC_POSITIONS
 Al 0.00 0.00 0.00 
K_POINTS {automatic}
 8 8 8    0 0 0
EOF
$ECHO "  running the scf calculation...\c"
$PW_COMMAND < al.scf.in > al.scf.out
$ECHO " done"

# non self-consistent calculation 
cat > al.nscf.in << EOF
 &control
    calculation='phonon'
    restart_mode='from_scratch',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    prefix='al'
 /
 &system    
    ibrav=  2, celldm(1) =7.50, nat=  1, ntyp= 1,
    ecutwfc =16.0, 
    occupations='smearing', smearing='methfessel-paxton', degauss=0.022
 /
 &electrons
 /
 &phonon
    xqq(1)=0.0, xqq(2)=0.0, xqq(3)=1.0
 /
ATOMIC_SPECIES
 Al  26.98 Al.vbc.UPF
ATOMIC_POSITIONS
 Al 0.00 0.00 0.00 
K_POINTS {automatic}
 8 8 8    0 0 0 
EOF

$ECHO "  running the nscf calculation at X...\c"
$PW_COMMAND < al.nscf.in > al.nscf.out
$ECHO " done"

# phonon calculation at X
cat > al.ph.in << EOF
phonons of Al at X
 &inputph
  tr2_ph=1.0d-12,
  prefix='al',
  amass(1)=26.98,
  outdir='$TMP_DIR/',
  fildyn='al.dyn'
  fildvscf='aldv'
 /
 0.0 0.0 1.0
EOF
$ECHO "  running the phonon calculation at X...\c"
$PH_COMMAND < al.ph.in > al.ph.out
$ECHO " done"

# denser grid
cat > al.nscf2.in << EOF
 &control
    calculation='phonon'
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    prefix='al'
 /
 &system    
    ibrav=  2, celldm(1) =7.50, nat=  1, ntyp= 1,
    ecutwfc =16.0,
    occupations='smearing', smearing='methfessel-paxton', degauss=0.022
 /
 &electrons
 /
 &phonon
    xqq(1)=0.0, xqq(2)=0.0, xqq(3)=1.0
 /
ATOMIC_SPECIES
 Al  26.98 Al.vbc.UPF
ATOMIC_POSITIONS
 Al 0.00 0.00 0.00 
K_POINTS {automatic}
 16 16 16 0 0 0
EOF
$ECHO "  running a non-scf calculation with denser grid at X...\c"
$PW_COMMAND < al.nscf2.in > al.nscf2.out
$ECHO " done"

# el-phonon
cat > al.elph.in << EOF
Al el-phonon at X
 &inputph
  tr2_ph=1.0d-14,
  prefix='al',
  fildvscf='aldv',
  amass(1)=26.98,
  outdir='$TMP_DIR/',
  fildyn='al.dyn',
  elph=.true.,
  trans=.false.,
 /
 0.0 0.0 1.0
EOF

$ECHO "  running the electron-phonon calculation on a denser grid at X...\c"
$PH_COMMAND < al.elph.in > al.elph.out
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR: done"
