#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use cp.x and to perform SCF"
$ECHO "simulation of C4H6 with TPSS metaGGA Exc."

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="cp.x "
PSEUDO_LIST="C.tpss-mt.UPF H.tpss-mt.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null         
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
CP_COMMAND="$PARA_PREFIX $BIN_DIR/cp.x $PARA_POSTFIX"
$ECHO
$ECHO "  running cp.x as: $CP_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/cp*
$ECHO " done"

# molecular dynamics calculation
cat > c4h6.cp.metaGGA.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    nstep=500, iprint=100, isave=500,
    dt=4.0,
    pseudo_dir='$PSEUDO_DIR/',
    outdir='$TMP_DIR/',
    tprnfor=.true.
    tstress=.true.
 /
 &system
    ibrav=1, celldm(1)=8.00,
    nat=10, ntyp=2, nbnd=11, 
    ecutwfc=30.0,
    nr1b=10, nr2b=10, nr3b=10,
 /
 &electrons
    electron_dynamics='damp', electron_damping=0.15D0,
    emass=350.D0, emass_cutoff=2.5D0,
 /
ATOMIC_SPECIES
 H 1.007825035 H.tpss-mt.UPF
 C 12.00       C.tpss-mt.UPF
ATOMIC_POSITIONS  bohr
 H  -0.271695E+01  -0.245822E+01   0.236174E+01
 H  -0.291292E+01   0.249129E+01   0.952936E+00
 H  0.203629E+01  -0.270414E+01  -0.104887E+01
 H  0.310911E+01  -0.162987E+01   0.189331E+01
 H  0.244815E+01   0.263846E+01   0.332670E+00
 H  0.940835E+00   0.160187E+01  -0.258377E+01
 C -0.121505E+01  -0.130902E+01   0.131661E+01
 C -0.136126E+01   0.116614E+01   0.825189E+00
 C  0.154872E+01  -0.143358E+01   0.510627E+00
 C  0.109484E+01   0.137081E+01  -0.496954E+00
EOF
$ECHO "  running the cp.x SCF calculation...\c"
$CP_COMMAND < c4h6.cp.metaGGA.in > c4h6.cp.metaGGA.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR : done"
