#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to calculate the polarization via Berry Phase"
$ECHO "in PbTiO3 (contributed by the Vanderbilt Group in Rutgers University)."

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x"
PSEUDO_LIST="Pb.pz-d-van.UPF Ti.pz-sp-van_ak.UPF O.pz-van_ak.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE \
                http://www.quantum-espresso.org/pseudo/1.3/UPF/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x as: $PW_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"

# self-consistent calculation
cat > chg.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>

<input calculation="scf">

	<cell type="qecell">
		<qecell ibrav="1" alat="7.3699">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="3">
		<specie name="Pb">
			<property name="mass">
				<real>207.2</real>
			</property>
			<property name="pseudofile">
				<string>Pb.pz-d-van.UPF</string>
			</property>
		</specie>
		<specie name="Ti">
			<property name="mass">
				<real>47.867</real>
			</property>
			<property name="pseudofile">
				<string>Ti.pz-sp-van_ak.UPF</string>
			</property>
		</specie>
		<specie name="O">
			<property name="mass">
				<real>15.9994</real>
			</property>
			<property name="pseudofile">
				<string>O.pz-van_ak.UPF</string>
			</property>
		</specie>
	</atomic_species>

	<atomic_list units="alat" nat="5" >
		<atom name="Pb">
			<position>
				<real rank="1" n1="3">
					0.000    0.000    0.010
				</real>
			</position>
		</atom>	
		<atom name="Ti">
			<position>
				<real rank="1" n1="3">
					0.500    0.500    0.500
				</real>
			</position>
		</atom>			
		<atom name="O">
			<position>
				<real rank="1" n1="3">
					0.000    0.500    0.500
				</real>
			</position>
		</atom>	
		<atom name="O">
			<position>
				<real rank="1" n1="3">
					0.500    0.500    0.000
				</real>
			</position>
		</atom>		
		<atom name="O">
			<position>
				<real rank="1" n1="3">
					0.500    0.000    0.500
				</real>
			</position>
		</atom>							
	</atomic_list>		
	
	
	<field name="InputOutput">

		<parameter name="restart_mode">
			<string>
				from_scratch
			</string>
		</parameter>
		
		<parameter name="pseudo_dir">
			<string>
				$PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
				$TMP_DIR/
			</string>
		</parameter>
		
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				30.0
			</real>
		</parameter>
		
		<parameter name="mixing_beta">
			<real>
				0.3
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.0e-12
			</real>
		</parameter>
		
	</field>	
	
	<field name="Options">

		<parameter name="occupations">
			<string>
				fixed
			</string>
		</parameter>
		
		<parameter name="degauss">
			<real>
				0.00
			</real>
		</parameter>
		
		<parameter name="nbnd">
			<integer>
				25
			</integer>
		</parameter>
		
	</field>	
	
	<k_points type="automatic">
		<mesh>
			<integer rank="1" n1="6">
				 4 4 4 1 1 1
			</integer>
		</mesh> 
	</k_points>
</input>
EOF
$ECHO "  running self-consistent calculation in PbTiO3...\c"
$PW_COMMAND < chg.xml > chg.out
check_failure $?
$ECHO " done"

# Berry Phase calculation
cat > BP.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>

<input calculation="nscf">

	<cell type="qecell">
		<qecell ibrav="1" alat="7.3699">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="3">
		<specie name="Pb">
			<property name="mass">
				<real>207.2</real>
			</property>
			<property name="pseudofile">
				<string>Pb.pz-d-van.UPF</string>
			</property>
		</specie>
		<specie name="Ti">
			<property name="mass">
				<real>47.867</real>
			</property>
			<property name="pseudofile">
				<string>Ti.pz-sp-van_ak.UPF</string>
			</property>
		</specie>
		<specie name="O">
			<property name="mass">
				<real>15.9994</real>
			</property>
			<property name="pseudofile">
				<string>O.pz-van_ak.UPF</string>
			</property>
		</specie>
	</atomic_species>

	<atomic_list units="alat" nat="5" >
		<atom name="Pb">
			<position>
				<real rank="1" n1="3">
					0.000    0.000    0.010
				</real>
			</position>
		</atom>	
		<atom name="Ti">
			<position>
				<real rank="1" n1="3">
					0.500    0.500    0.500
				</real>
			</position>
		</atom>			
		<atom name="O">
			<position>
				<real rank="1" n1="3">
					0.000    0.500    0.500
				</real>
			</position>
		</atom>	
		<atom name="O">
			<position>
				<real rank="1" n1="3">
					0.500    0.500    0.000
				</real>
			</position>
		</atom>		
		<atom name="O">
			<position>
				<real rank="1" n1="3">
					0.500    0.000    0.500
				</real>
			</position>
		</atom>							
	</atomic_list>		
	
	
	<field name="InputOutput">

		<parameter name="pseudo_dir">
			<string>
				$PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
				$TMP_DIR/
			</string>
		</parameter>
		
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				30.0
			</real>
		</parameter>
		
		<parameter name="mixing_beta">
			<real>
				0.3
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.0e-5
			</real>
		</parameter>
		
	</field>	
	
	<field name="Options">

		<parameter name="occupations">
			<string>
				fixed
			</string>
		</parameter>
		
		<parameter name="degauss">
			<real>
				0.00
			</real>
		</parameter>
		
		<parameter name="nbnd">
			<integer>
				22
			</integer>
		</parameter>
		
	</field>
	
	<field name="Fields">

		<parameter name="lberry">
			<logical>
				true
			</logical>
		</parameter>
		
		<parameter name="gdir">
			<integer>
				3
			</integer>
		</parameter>
		
		<parameter name="nppstr">
			<integer>
				7
			</integer>
		</parameter>
		
	</field>		
	
	<k_points type="automatic">
		<mesh>
			<integer rank="1" n1="6">
				  4 4 7 1 1 1
			</integer>
		</mesh> 
	</k_points>
</input>
EOF
$ECHO "  running Berry Phase calculation for PbTiO3...\c"
$PW_COMMAND < BP.xml > BP.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR: done"
