#!/bin/sh

###############################################################################
##
##  HIGH VERBOSITY EXAMPLE
##
###############################################################################

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example tests ph.x with PAW"
$ECHO "It calculates the phonon modes of C at the gamma and X points"
$ECHO "and the vibrational modes of a molecule (CH4) at Gamma."
$ECHO

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x ph.x"
PSEUDO_LIST="H.pz-kjpaw.UPF C.pz-kjpaw.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE \
                http://www.quantum-espresso.org/pseudo/1.3/UPF/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
PH_COMMAND="$PARA_PREFIX $BIN_DIR/ph.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x     as: $PW_COMMAND"
$ECHO "  running ph.x     as: $PH_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/*
$ECHO " done"

# self-consistent calculation for C with PAW-PP
cat > c.scf.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>


<input calculation="scf" prefix="C">

	<cell type="qecell">
		<qecell ibrav="2" alat="6.68">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="1">
		<specie name="C">
			<property name="mass">
				<real>0.0</real>
			</property>
			<property name="pseudofile">
				<string>C.pz-kjpaw.UPF</string>
			</property>
		</specie>
	</atomic_species>

	<atomic_list units="alat" nat="2" >
		<atom name="C">
			<position>
				<real rank="1" n1="3">
					0.00 0.00 0.00
				</real>
			</position>
		</atom>	
		<atom name="C">
			<position>
				<real rank="1" n1="3">
					0.25 0.25 0.25
				</real>
			</position>
		</atom>		
	</atomic_list>		
	
	
	<field name="InputOutput">

		<parameter name="restart_mode">
			<string>
				from_scratch
			</string>
		</parameter>

		<parameter name="pseudo_dir">
			<string>
				$PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
				$TMP_DIR/
			</string>
		</parameter>
		
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				27.0
			</real>
		</parameter>
		
		<parameter name="ecutrho">
			<real>
				300.0
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.0d-9
			</real>
		</parameter>
		
		<parameter name="nr1">
			<integer>
				32
			</integer>
		</parameter>
		
		<parameter name="nr2">
			<integer>
				32
			</integer>
		</parameter>
		
		<parameter name="nr3">
			<integer>
				32
			</integer>
		</parameter>
		
		<parameter name="mixing_beta">
			<real>
				0.7
			</real>
		</parameter>
	
	</field>
	
	<k_points type="automatic">
		<mesh>
			<integer rank="1" n1="6">
				4 4 4 1 1 1
			</integer>
		</mesh>
	</k_points>
</input>
EOF
$ECHO "  running the scf calculation for C...\c"
$PW_COMMAND < c.scf.xml > c.scf.out
check_failure $?
$ECHO " done"

# phonon calculation at G
cat > c.phG.in << EOF
phonons of C at Gamma
 &inputph
  tr2_ph=1.0d-14,
  epsil=.true.,
  zue=.true.
  prefix='C',
  fildyn='Cg.dyn',
  outdir='$TMP_DIR/'
 /
0.0 0.0 0.0
EOF
$ECHO "  running the phonon calculation for C at Gamma...\c"
$PH_COMMAND < c.phG.in > c.phG.out
check_failure $?
$ECHO " done"

# phonon calculation at X
cat > c.phX.in << EOF
phonons of C at X
 &inputph
  tr2_ph=1.0d-14,
  prefix='C',
  fildyn='CX.dyn',
  outdir='$TMP_DIR/'
 /
1.0 0.0 0.0
EOF
$ECHO "  running the phonon calculation for C at X...\c"
$PH_COMMAND < c.phX.in > c.phX.out
check_failure $?
$ECHO " done"

# self-consistent calculation for Cu PBE with PAW-PP
cat > Cu.scf_pbe.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>


<input calculation="scf" prefix="Cu">

	<cell type="qecell">
		<qecell ibrav="2" alat="6.90">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="1">
		<specie name="Cu">
			<property name="mass">
				<real>0.0</real>
			</property>
			<property name="pseudofile">
				<string>Cu.pbe-kjpaw.UPF</string>
			</property>
		</specie>
	</atomic_species>

	<atomic_list units="alat" nat="1" >
		<atom name="Cu">
			<position>
				<real rank="1" n1="3">
					0.00 0.00 0.00
				</real>
			</position>
		</atom>		
	</atomic_list>		
	
	
	<field name="InputOutput">

		<parameter name="restart_mode">
			<string>
				from_scratch
			</string>
		</parameter>

		<parameter name="pseudo_dir">
			<string>
				$PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
				$TMP_DIR/
			</string>
		</parameter>
		
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				30.0
			</real>
		</parameter>
		
		<parameter name="ecutrho">
			<real>
				700.0
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.0d-9
			</real>
		</parameter>
		
		<parameter name="mixing_beta">
			<real>
				0.7
			</real>
		</parameter>
	
	</field>
	
	<field name="Options">

		<parameter name="occupations">
			<string>
				smearing
			</string>
		</parameter>
		
		<parameter name="smearing">
			<string>
				mp
			</string>
		</parameter>
		
		<parameter name="degauss">
			<real>
				0.01
			</real>
		</parameter>		
	
	</field>		

	
	<k_points type="automatic">
		<mesh>
			<integer rank="1" n1="6">
				 4 4 4 1 1 1
			</integer>
		</mesh>
	</k_points>
</input>
EOF
$ECHO "  running the scf calculation for Cu with GGA-PBE...\c"
$PW_COMMAND < Cu.scf_pbe.xml > Cu.scf_pbe.out
check_failure $?
$ECHO " done"

# phonon calculation at G
cat > Cu.phG_pbe.in << EOF
phonons of Cu at Gamma
 &inputph
  tr2_ph=1.0d-14,
  prefix='Cu',
  fildyn='Cug.dyn',
  outdir='$TMP_DIR/'
 /
0.0 0.0 0.0
EOF
$ECHO "  running the phonon calculation for Cu at Gamma with GGA-PBE...\c"
$PH_COMMAND < Cu.phG_pbe.in > Cu.phG_pbe.out
check_failure $?
$ECHO " done"


# Self consistent calculation for CH4
cat > ch4.scf.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>

<!-- ch4
ch4 molecule in a cubic box -->

<input calculation="scf" prefix="ch4">

	<cell type="qecell">
		<qecell ibrav="1" alat="15.0">
			<real rank="1" n1="5">
				0.0 0.0 0.0 0.0 0.0
			</real>
		</qecell>
	</cell>

	<atomic_species ntyp="2">
		<specie name="H">
			<property name="mass">
				<real>1.0</real>
			</property>
			<property name="pseudofile">
				<string>H.pz-kjpaw.UPF</string>
			</property>
		</specie>
		<specie name="C">
			<property name="mass">
				<real>12.0</real>
			</property>
			<property name="pseudofile">
				<string>C.pz-kjpaw.UPF</string>
			</property>
		</specie>
	</atomic_species>

	<atomic_list units="alat" nat="5" >
		<atom name="H">
			<position>
				<real rank="1" n1="3">
					0.080728893   0.080728893   0.080728893
				</real>
			</position>
		</atom>	
		<atom name="H">
			<position>
				<real rank="1" n1="3">
					-0.080728893  -0.080728893   0.080728893
				</real>
			</position>
		</atom>	
		<atom name="H">
			<position>
				<real rank="1" n1="3">
					0.080728893  -0.080728893  -0.080728893
				</real>
			</position>
		</atom>	
		<atom name="H">
			<position>
				<real rank="1" n1="3">
					-0.080728893   0.080728893  -0.080728893
				</real>
			</position>
		</atom>	
		<atom name="C">
			<position>
				<real rank="1" n1="3">
					0.000000000   0.000000000   0.0000000000
				</real>
			</position>
		</atom>						
	</atomic_list>	
	
	
	<field name="InputOutput">

		<parameter name="restart_mode">
			<string>
				from_scratch
			</string>
		</parameter>
		
		<parameter name="pseudo_dir">
			<string>
				$PSEUDO_DIR/
			</string>
		</parameter>
		
		<parameter name="outdir">
			<string>
				$TMP_DIR/
			</string>
		</parameter>
		
		<parameter name="tprnfor">
			<logical>
				true
			</logical>
		</parameter>			
					
	</field>
	
	<field name="Numerics">

		<parameter name="ecutwfc">
			<real>
				25.0
			</real>
		</parameter>
		
		<parameter name="ecutrho">
			<real>
				300.0
			</real>
		</parameter>
		
		<parameter name="mixing_beta">
			<real>
				0.5
			</real>
		</parameter>
		
		<parameter name="conv_thr">
			<real>
				1.0d-10
			</real>
		</parameter>
		
	</field>
	
	<k_points type="tpiba">
		<mesh npoints="1">
			<real rank="2" n1="4" n2="1">
				  	0.0 0.0 0.0 1.0
			</real>
		</mesh>
	</k_points>
</input>
EOF
$ECHO "  running the scf calculation for CH4...\c"
$PW_COMMAND < ch4.scf.xml > ch4.scf.out
check_failure $?
$ECHO " done"

# normal mode calculation for CH4
cat > ch4.nm.in << EOF
vibrations of ch4
 &inputph
  tr2_ph=4.0d-17,
  prefix='ch4',
  outdir='$TMP_DIR',
  amass(1)=1.d0,
  amass(2)=12.d0,
  asr=.true.,
  zue=.true.,
  epsil=.true.,
  trans=.true.,
  fildyn='ch4.dyn',
 /
0.0 0.0 0.0
EOF
$ECHO "  running normal mode calculation for CH4...\c"
$PH_COMMAND < ch4.nm.in > ch4.nm.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR: done"
