#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname

echo
echo "run_all_examples: starting"

# run all examples
for dir in example* Partial_example Recover_example Image_example ;
do
    if test -f $dir/run_example
    then
        sh $dir/run_example
    fi
done

if test -f GRID_example/run_example
then
   sh GRID_example/run_example
   sh GRID_example/run_example_1
   sh GRID_example/run_example_2
fi


echo
echo "run_all_examples: done"
