#!/bin/bash

work=./results
reference=./reference
. ../../../examples/environment_variables
BIN_DIR=../../../bin

mkdir $work
rm -f $work/*

ld1_command="$PARA_PREFIX $BIN_DIR/ld1.x $PARA_POSTFIX"

echo "ld1_command =" $ld1_command

if test -e difference ; then /bin/rm difference > /dev/null ; fi
touch difference

for atom in Cu Si; do
    $ld1_command < $atom.in > $work/$atom.out
    echo "diff -wib ./results/$atom.out ./reference/$atom.out" >> difference
    diff -wib $work/$atom.out $reference/ >> difference
    $ld1_command < $atom.test > $work/$atom.test.out
    echo "diff -wib ./results/$atom.test.out ./reference/$atom.test.out" >> difference
    diff -wib $work/$atom.test.out $reference/ >> difference
done

/bin/rm ld1.wfc out_*  >& /dev/null
