#!/bin/sh

DIR=install

cd ../Modules
rm -f .dependencies
touch .dependencies
for file in `ls *.f90`
do
  ../$DIR/moduledep.x $file *.f90 >> .dependencies
done

cd ../PW
rm -f .dependencies
touch .dependencies
for file in `ls *.f90`
do
  ../$DIR/moduledep.x $file *.f90 ../Modules/*.f90 >> .dependencies
done

cd ../PP
rm -f .dependencies
touch .dependencies
for file in `ls *.f90`
do
  ../$DIR/moduledep.x $file *.f90 ../PW/*.f90 ../Modules/*.f90 >> .dependencies
done

cd ../Gamma
rm -f .dependencies
touch .dependencies
for file in `ls *.f90`
do
  ../$DIR/moduledep.x $file *.f90 ../PW/*.f90 ../Modules/*.f90 >> .dependencies
done

cd ../PH
rm -f .dependencies
touch .dependencies
for file in `ls *.f90`
do
  ../$DIR/moduledep.x $file *.f90 ../PW/*.f90 ../Modules/*.f90 >> .dependencies
done

cd ../D3
rm -f .dependencies
touch .dependencies
for file in `ls *.f90`
do
  ../$DIR/moduledep.x $file *.f90 ../PW/*.f90 ../PH/*.f90 ../Modules/*.f90 >> .dependencies
done

cd ../FPMD
rm -f .dependencies
touch .dependencies
for file in `ls *.f90`
do
  ../$DIR/moduledep.x $file *.f90 ../Modules/*.f90 >> .dependencies
done

cd ../flib
rm -f .dependencies
touch .dependencies
for file in `ls *.f90`
do
  ../$DIR/moduledep.x $file *.f90 ../FPMD/*.f90 ../Modules/*.f90 >> .dependencies
done

cd ../CPV
rm -f .dependencies
touch .dependencies
for file in `ls *.f90`
do
  ../$DIR/moduledep.x $file *.f90 ../Modules/*.f90 >> .dependencies
done
