scatter_grid – FFTXlib
scatter_grid Interface
Source File
Module Procedures
scatter_real_grid scatter_complex_grid
All Procedures
allowed bw_tg_cft3_scatter bw_tg_cft3_xy bw_tg_cft3_z cfft3d cfft3d cfft3d cfft3d cfft3d cfft3ds cfft3ds cfft3ds cfft3ds cfft3ds cft_1z cft_1z cft_1z cft_1z cft_1z cft_2xy cft_2xy cft_2xy cft_2xy cft_2xy cft_b cft_b_omp cft_b_omp_init cgather_sym cgather_sym_many cscatter_sym_many fft_box_allocate fft_box_deallocate fft_box_set fft_dlay_allocate fft_dlay_deallocate fft_dlay_scalar fft_dlay_set fft_scatter fftx_error__ fw_tg_cft3_scatter fw_tg_cft3_xy fw_tg_cft3_z fwfft fwfft_x gather_complex_grid gather_grid gather_real_grid good_fft_dimension good_fft_order invfft invfft_b invfft_x pack_group_sticks pstickset pstickset_custom scatter_complex_grid scatter_grid scatter_real_grid sticks_countg sticks_deallocate sticks_dist sticks_maps sticks_maps_scalar sticks_ordered_dist sticks_pairup sticks_sort task_groups_init task_groups_init_first tg_cft3s tg_cgather tg_gather unpack_group_sticks
public interface scatter_grid
Calls
Module Procedures
private subroutine scatter_real_grid(dfft, f_in, f_out)
Arguments
Type Intent Optional Attributes Name
type(fft_dlay_descriptor), intent(in) :: dfft
real(kind=DP), intent(in) :: f_in(:)
real(kind=DP), intent(inout) :: f_out(:)
private subroutine scatter_complex_grid(dfft, f_in, f_out)
Arguments
Type Intent Optional Attributes Name
type(fft_dlay_descriptor), intent(in) :: dfft
complex(kind=DP), intent(in) :: f_in(:)
complex(kind=DP), intent(inout) :: f_out(:)
Call graph
scatter_grid calls scatter_real_grid, scatter_complex_grid
scatter_real_grid calls fftx_error__, mpi_scatterv, stop_clock, start_clock
scatter_complex_grid calls fftx_error__, mpi_scatterv, stop_clock, start_clock