#!/bin/sh

###############################################################################
##
##  HIGH VERBOSITY EXAMPLE
##
###############################################################################

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use pw.x to calculate the total energy of FeO"
$ECHO "using LDA+U approximation. Read file README for more details"

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x"
PSEUDO_LIST="O.pz-rrkjus.UPF Fe.pz-nd-rrkjus.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x as: $PW_COMMAND"
$ECHO

# self-consistent calculation with standard LDA
cat > feo_LDA.in << EOF
FeO
FeO Wustite in LDA
 &control
    calculation = 'scf'
    restart_mode='from_scratch',
    prefix='feo_af',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
    tprnfor = .true., tstress=.true.
 /
 &system
    ibrav=  0, celldm(1)=8.19, nat=  4, ntyp= 3,
    ecutwfc = 30.0, ecutrho = 240.0, nbnd=20,
    starting_magnetization(1)= 0.0,
    starting_magnetization(2)= 0.5,
    starting_magnetization(3)=-0.5,
    occupations='smearing', smearing='mv', degauss=0.01,
    nspin=2,
    lda_plus_u=.true.  Hubbard_U(2)=1.d-8, Hubbard_U(3)=1.d-8,
 /
 &electrons
    mixing_mode = 'plain'
    mixing_beta = 0.3
    conv_thr =  1.0d-6
    mixing_fixed_ns = 0
 /
CELL_PARAMETERS
0.50 0.50 1.00
0.50 1.00 0.50
1.00 0.50 0.50
ATOMIC_SPECIES
 O1   1.  O.pz-rrkjus.UPF
 Fe1  1.  Fe.pz-nd-rrkjus.UPF
 Fe2  1.  Fe.pz-nd-rrkjus.UPF
ATOMIC_POSITIONS {crystal}
 O1  0.25 0.25 0.25
 O1  0.75 0.75 0.75
 Fe1 0.0  0.0  0.0
 Fe2 0.5  0.5  0.5
K_POINTS {automatic}
2 2 2 0 0 0
EOF
$ECHO "  running scf for FeO in LDA ...\c"
$PW_COMMAND < feo_LDA.in > feo_LDA.out
check_failure $?
$ECHO " done"


# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/feo_af*
$ECHO " done"

# self-consistent calculation with standard ns initial value
cat > feo_standard.in << EOF
FeO
FeO Wustite whithin LDA+U using standard initial ns matrices
 &control
    calculation = 'scf'
    restart_mode='from_scratch',
    prefix='feo_af',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
    tprnfor = .true., tstress=.true.
 /
 &system
    ibrav=  0, celldm(1)=8.19, nat=  4, ntyp= 3,
    ecutwfc = 30.0, ecutrho = 240.0, nbnd=20,
    starting_magnetization(1)= 0.0,
    starting_magnetization(2)= 0.5,
    starting_magnetization(3)=-0.5,
    occupations='smearing', smearing='mv', degauss=0.01,
    nspin=2,
    lda_plus_u=.true.  Hubbard_U(2)=4.3, Hubbard_U(3)=4.3,
 /
 &electrons
    mixing_mode = 'plain'
    mixing_beta = 0.3
    conv_thr =  1.0d-6
    mixing_fixed_ns = 0
 /
CELL_PARAMETERS
0.50 0.50 1.00
0.50 1.00 0.50
1.00 0.50 0.50
ATOMIC_SPECIES
 O1   1.  O.pz-rrkjus.UPF
 Fe1  1.  Fe.pz-nd-rrkjus.UPF
 Fe2  1.  Fe.pz-nd-rrkjus.UPF
ATOMIC_POSITIONS {crystal}
 O1  0.25 0.25 0.25
 O1  0.75 0.75 0.75
 Fe1 0.0  0.0  0.0
 Fe2 0.5  0.5  0.5
K_POINTS {automatic}
2 2 2 0 0 0
EOF
$ECHO "  running scf for FeO in LDA+U using standard ns initial matrices...\c"
$PW_COMMAND < feo_standard.in > feo_standard.out
check_failure $?
$ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/feo_af*
$ECHO " done"

# self-consistent calculation with user-defined ns initial value
cat > feo_user_ns.in << EOF
FeO
FeO Wustite whithin LDA+U with user-defined ns initial matrices
 &control
    calculation = 'scf'
    restart_mode='from_scratch',
    prefix='feo_af',
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
    tprnfor = .true., tstress=.true.
 /
 &system
    ibrav=  0, celldm(1)=8.19, nat=  4, ntyp= 3,
    ecutwfc = 30.0, ecutrho = 240.0, nbnd=20,
    starting_magnetization(1)= 0.0,
    starting_magnetization(2)= 0.5,
    starting_magnetization(3)=-0.5,
    occupations='smearing', smearing='mv', degauss=0.01,
    nspin=2,
    lda_plus_u=.true., Hubbard_U(2)=4.3, Hubbard_U(3)=4.3,
    starting_ns_eigenvalue(3,2,2) = 1.d0
    starting_ns_eigenvalue(3,1,3) = 1.d0
 /
 &electrons
    mixing_mode = 'plain'
    mixing_beta = 0.3
    conv_thr =  1.0d-6
    mixing_fixed_ns = 0
 /
CELL_PARAMETERS
0.50 0.50 1.00
0.50 1.00 0.50
1.00 0.50 0.50
ATOMIC_SPECIES
 O1   1.  O.pz-rrkjus.UPF
 Fe1  1.  Fe.pz-nd-rrkjus.UPF
 Fe2  1.  Fe.pz-nd-rrkjus.UPF
ATOMIC_POSITIONS {crystal}
 O1  0.25 0.25 0.25
 O1  0.75 0.75 0.75
 Fe1 0.0  0.0  0.0
 Fe2 0.5  0.5  0.5
K_POINTS {automatic}
2 2 2 0 0 0
EOF
$ECHO "  running scf for FeO in LDA+U using user-defined ns initial matrices...\c"
$PW_COMMAND < feo_user_ns.in > feo_user_ns.out
check_failure $?
$ECHO " done"
# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/feo_af*
$ECHO " done"


$ECHO
$ECHO "$EXAMPLE_DIR : done"
