#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use cp.x to perform"
$ECHO "Born-Oppenheimer molecular dynamics using the"
$ECHO "conjugate gradient minimization of the electronic"
$ECHO "states. It shows also the use of ensemble-DFT"
$ECHO "for metallic systems."
$ECHO "The example shows a Si dimer"

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="cp.x"
PSEUDO_LIST="Si.pbe-rrkj.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null         
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
CP_COMMAND="$PARA_PREFIX $BIN_DIR/cp.x $PARA_POSTFIX"
$ECHO
$ECHO "  running cp.x as: $CP_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/cp*
$ECHO " done"

# molecular dynamics calculation
cat > si2.ensemble-dyn.in << EOF
&CONTROL
  calculation = 'cp',
  restart_mode = 'from_scratch',
  nstep  = 5,
  iprint = 10,
  isave  = 10,
  tstress = .TRUE.,
  tprnfor = .TRUE.,
  dt    = 10.0d0,
  prefix = 'Si_dimer',
  pseudo_dir = '$PSEUDO_DIR/',
  outdir='$TMP_DIR/'

/

&SYSTEM
  ibrav = 8,
  celldm(1) = 10.,
  celldm(2) = 1.0,
  celldm(3) = 1.5,
  celldm(4) = 0.0,
  celldm(5) = 0.0,
  celldm(6) = 0.0,
  nbnd=8,
  nat  =2,
  ntyp =1,
  ecutwfc = 15,
  ecutrho = 60,
  nr1b=20,nr2b=20,nr3b=20
  occupations = 'ensemble',
  smearing='fd',
  degauss=0.025,
  nspin=1,
/

&ELECTRONS
  emass = 1000.d0,
  emass_cutoff = 4.d0,
  orthogonalization = 'Gram-Schmidt',
  startingwfc = 'random',
  ampre = 0.02,
  n_inner = 8,
  tcg = .true.,
  passop=0.3,
  maxiter = 250,
  conv_thr=1.d-6
/

&IONS
  ion_dynamics = 'damp',
  ion_damping = 0.,
  ion_positions = 'from_input',
  greasp=1.0,
  ion_radius(1) = 0.8d0,
  ion_temperature = 'not_controlled',
/

ATOMIC_SPECIES
 Si 28.086 Si.pbe-rrkj.UPF
ATOMIC_POSITIONS (bohr)
Si 0. 0. 0.  1 1 1
Si 0. 0. 5.5 1 1 1
EOF
$ECHO "  running the calculation BO-MD for Si-dimer...\c"
$CP_COMMAND < si2.ensemble-dyn.in > si2.ensemble-dyn.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR : done"
