# Makefile for VdW

default: all

all: vdw

vdw:	
	@echo "VdW no longer maintained"
#	if test -d src ; then \
#	( cd src ; if test "$(MAKE)" = "" ; then make $(MFLAGS) $@; \
#	else $(MAKE) $(MFLAGS) ; fi ) ; fi ; \

clean :
	( cd src ; if test "$(MAKE)" = "" ; then make clean ; \
	else $(MAKE) clean ; fi )

distclean: clean
