#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use ph.x to calculate the phonons at X and Gamma"
$ECHO "of fcc-Pt using fully relativistic pseudo-potential and including spin-orbit coupling."

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x ph.x"
PSEUDO_LIST="Pt.rel-pz-n-rrkjus.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
PH_COMMAND="$PARA_PREFIX $BIN_DIR/ph.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x as: $PW_COMMAND"
$ECHO "  running ph.x as: $PH_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/platinum*
rm -rf $TMP_DIR/_ph0/platinum*
$ECHO " done"

# self-consistent calculation
cat > pt.scf_ph.in << EOF
Pt
Pt
 &control
    calculation = 'scf'
    restart_mode='from_scratch',
    prefix='platinum',
    tprnfor = .true.,
    tstress =.true.,
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='$TMP_DIR/'
 /
 &system
    ibrav=  2, celldm(1) =7.42, nat=  1, ntyp= 1,
    lspinorb=.true.,
    noncolin=.true.,
    starting_magnetization=0.0,
    occupations='smearing',
    degauss=0.02,
    smearing='mv',
    ecutwfc =30.0,
    ecutrho =250.0,
 /
 &electrons
    mixing_beta = 0.7,
    conv_thr =  1.0d-8
 /
ATOMIC_SPECIES
Pt  0.0    Pt.rel-pz-n-rrkjus.UPF
ATOMIC_POSITIONS (alat)
Pt  0.0000000   0.00000000   0.0
K_POINTS AUTOMATIC
2 2 2 1 1 1
EOF
$ECHO "  running the scf calculation for Pt with spin-orbit coupling...\c"
$PW_COMMAND < pt.scf_ph.in > pt.scf_ph.out
check_failure $?
$ECHO " done"

cat > pt.ph.in << EOF
phonons of Pt at Gamma
 &inputph

  amass(1)=195.078,

  prefix='platinum',
  outdir='$TMP_DIR'
  fildyn='ptdyn',
  tr2_ph=1.0d-16,
 /
0.0 0.0 0.0
EOF
$ECHO "  running the phonon calculation for Pt with spin-orbit coupling...\c"
$PH_COMMAND < pt.ph.in > pt.ph.out
check_failure $?
$ECHO " done"

cat > pt.phX.in << EOF
phonons of Pt at X
 &inputph
  amass(1)=195.078,
  prefix='platinum',
  outdir='$TMP_DIR'
  fildyn='ptdyn',
  tr2_ph=1.0d-16,
 /
1.0 0.0 0.0
EOF
$ECHO "  running the phonon calculation at X for Pt with spin-orbit coupling...\c"
$PH_COMMAND < pt.phX.in > pt.phX.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR: done"
