#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

# function to test the exit status of a job
. ../check_failure.sh

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use efg.x to calculate "
$ECHO "the electric field gradient tensor and the quadrupolar parameters"
$ECHO "of a NMR experiment "

# set the needed environment variables
. ../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x efg.x"
PSEUDO_LIST="OPBE_nc.UPF SiPBE_nc.UPF O.recon Si.recon"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x as: $PW_COMMAND"
$ECHO

    # clean TMP_DIR
    $ECHO "  cleaning $TMP_DIR...\c"
    rm -rf $TMP_DIR/*
    $ECHO " done"

    # self-consistent calculation
    cat > quartz.scf.in << EOF
&control
        calculation='scf'
        restart_mode='from_scratch',
        prefix='quartz',
        pseudo_dir='$PSEUDO_DIR/',
        outdir='$TMP_DIR/'
 /
 &system
        ibrav=0,
        celldm(1)=1.,
        nat=9, ntyp=2,
        ecutwfc = 80, ecutrho = 320.0
        nspin=1,
 /
 &electrons
        conv_thr = 1.0d-8
        mixing_beta=0.1
 /
ATOMIC_SPECIES
Si 28.1  SiPBE_nc.UPF
O 16.  OPBE_nc.UPF
ATOMIC_POSITIONS {crystal}
Si 0.4701          0.00            0.3333333333
Si 0.00            0.4701          0.6666666667
Si -0.4701         -0.4701         0.0
O  0.4139          0.2674          0.2144
O   -0.2674         .1465           .5477333333
O   -.1465          -0.4139         .8810666667
O   0.2674          0.4139          -0.2144
O   .1465           -0.2674         .4522666667
O   -0.4139         -.1465          .1189333333
CELL_PARAMETERS {hexagonal}
4.6415377       -8.0393791      0.0
4.6415377       8.0393791       0.0
0.0             0.0             10.211800
K_POINTS {automatic}
2 2 2   1 1 1
EOF

    $ECHO "  running the scf calculation for quartz...\c"
    $PW_COMMAND < quartz.scf.in > quartz.scf.out
    check_failure $?
    $ECHO " done"

    # electic field gradient calculation
    cat > quartz.efg.in << EOF
&inputpp
  filerec(1)='$PSEUDO_DIR/Si.recon'
  filerec(2)='$PSEUDO_DIR/O.recon'
  prefix='quartz'
  outdir='$TMP_DIR/'
  Q(1)=0.0
  Q(2)=2.55
/
EOF


# how to run executables
EFG_COMMAND="$PARA_PREFIX $BIN_DIR/efg.x $PARA_POSTFIX"

    $ECHO "  running efg calculation for quartz...\c"
    $EFG_COMMAND < quartz.efg.in > quartz.efg.out
    check_failure $?
    $ECHO " done"

    # clean TMP_DIR
    $ECHO "  cleaning $TMP_DIR...\c"
    rm -rf $TMP_DIR/*
    $ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR : done"

