if(QE_ENABLE_OFFLOAD)
    if(CMAKE_Fortran_COMPILER_ID MATCHES "IntelLLVM")
        if(OFFLOAD_ARCH OR QE_GPU_ARCHS)
            # for ahead-of-time compilation and linking
            # if OFFLOAD_ARCH not defined, overwrite it with QE_GPU_ARCHS
            if(NOT OFFLOAD_ARCH AND QE_GPU_ARCHS)
                set(OFFLOAD_ARCH ${QE_GPU_ARCHS})
            endif()
            if(OFFLOAD_ARCH MATCHES "^intel_gpu_")
                target_compile_options(qe_openmp_fortran INTERFACE "$<$<COMPILE_LANGUAGE:Fortran>:-fopenmp-targets=spir64_gen>")
                string(REGEX REPLACE "^intel_gpu_" "" INTEL_GPU_ARCH "${OFFLOAD_ARCH}")
                target_link_options(qe_openmp_fortran INTERFACE "$<$<LINK_LANGUAGE:Fortran>:-fopenmp-targets=spir64_gen;-Xs;-device ${INTEL_GPU_ARCH}>")
            else()
                message(FATAL_ERROR "Invalid Intel GPU architecture \"${OFFLOAD_ARCH}\"! Did you miss \"intel_gpu_\" prefix?")
            endif()
        else()
            target_compile_options(qe_openmp_fortran INTERFACE "$<$<COMPILE_LANGUAGE:Fortran>:-fopenmp-targets=spir64>")
            target_link_options(qe_openmp_fortran INTERFACE "$<$<LINK_LANGUAGE:Fortran>:-fopenmp-targets=spir64>")
        endif()
    else()
        message(FATAL_ERROR "Classic Intel compilers detected. OpenMP offlaod requires Intel OneAPI compilers.")
    endif()
endif()

