#!/bin/bash

work=./results
reference=./reference
ld1dir=../../atomic/

mkdir $work
rm -f $work/*

$ld1dir/ld1.x < o.in > $work/o.out
$ld1dir/ld1.x < al.in > $work/al.out
$ld1dir/ld1.x < as.in > $work/as.out
$ld1dir/ld1.x < pt.in > $work/pt.out
$ld1dir/ld1.x < si_nc.in > $work/si_nc.out
$ld1dir/ld1.x < si_nc_paw.in > $work/si_nc_paw.out

if test -e difference ; then /bin/rm difference > /dev/null ; fi
touch difference

for file in o.out al.out as.out pt.out si_nc.out si_nc_paw.out ; do
    echo "diff -wib ./results/$file ./reference/$file" >> difference
    diff -wib $work/$file $reference/ >> difference
done

for file in OPBE.RRKJ3 Al.rrkj3 Asrel.RRKJ3.UPF Ptrel.RRKJ3.UPF SiPBE_nc Si.recon ; do
    echo "-------------------------------------------------" >> difference
    echo "diff -wib ./results/$file ./reference/$file" >> difference
    echo "Note that results and reference data may differ for numerical reasons" >> difference
    mv $file $work 
    diff $work/$file $reference/ >> difference
done

rm SiPBE_nc.bad
