#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname

echo
echo "run_all_examples: starting"

# run all examples
for dir in example* CLS_FS_example CLS_IS_example dipole_example WorkFct_example WannierHam_example MolDos_example ForceTheorem_example  WAN90_example ;
do
    if test -f $dir/run_example
    then
        sh $dir/run_example
    fi
done


echo
echo "run_all_examples: done"
