#!/bin/sh

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use pw.x to calculate the total energy"
$ECHO "of fcc-Pt with a fully relativistic "
$ECHO "pseudo-potential including spin-orbit coupling."
$ECHO "pwcond.x is used to calculate the complex bands"
$ECHO "including spin-orbit coupling."

# set the needed environment variables
. ../../../environment_variables

# required executables and pseudopotentials
BIN_LIST="pw.x pwcond.x "
PSEUDO_LIST="Pt.rel-pz-n-rrkjus.UPF"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
PWCOND_COMMAND="$PARA_PREFIX $BIN_DIR/pwcond.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x as: $PW_COMMAND"
$ECHO "  running pwcond.x as: $PWCOND_COMMAND"
$ECHO

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/pwscf*
$ECHO " done"

# a self-consistent calculation of Pt in a tetragonal cell
cat > pt.tet.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    pseudo_dir = '$PSEUDO_DIR/',
    tstress=.true.,
    outdir='$TMP_DIR/',
    prefix='ptt',
 /
 &system
    ibrav = 6,
    celldm(1) =5.23,
    celldm(3) =1.4142,
    nat= 2,
    ntyp= 1,
    noncolin=.true.,
    lspinorb=.true.,
    starting_magnetization(1)=0.0,
    ecutwfc = 30.0,
    ecutrho = 250.0,
    occupations='smearing',
    smearing='mv',
    degauss=0.02
 /
 &electrons
    conv_thr = 1.0e-8
    mixing_beta = 0.7
 /
ATOMIC_SPECIES
 Pt 0.0  Pt.rel-pz-n-rrkjus.UPF
ATOMIC_POSITIONS
 Pt 0.  0.  0.
 Pt 0.5 0.5 0.7071
K_POINTS (automatic)
 4 4 3 1 1 1
EOF
$ECHO "  running the scf calculation for Pt with tetragonal cell...\c"
$PW_COMMAND < pt.tet.in > pt.tet.out
check_failure $?
$ECHO " done"

# Calculation of the complex bands of Pt
cat > pt.cond.in << EOF
 &inputcond
    outdir='$TMP_DIR/'
    prefixl='ptt'
    band_file = 'bands.pt'
    ikind=0
    energy0=0.0d0
    denergy=-0.2d0
    ewind=4.d0
    epsproj=1.d-7
 /
    1
    0.0 0.0 1.0
    1
EOF
$ECHO "  running the calculation of the complex bands of Pt...\c"
$PWCOND_COMMAND < pt.cond.in > pt.cond.out
check_failure $?
$ECHO " done"

cat > pt4.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    pseudo_dir = '$PSEUDO_DIR',
    outdir='$TMP_DIR',
    prefix='pt4',
 /
 &system
    ibrav = 6,
    celldm(1) =5.23,
    celldm(3) =2.8284,
    nat= 4,
    ntyp= 1,
    noncolin=.true.,
    lspinorb=.true.,
    ecutwfc = 25.0,
    ecutrho = 150.0,
    occupations='smearing',
    smearing='mv',
    degauss=0.02
 /
 &electrons
    conv_thr = 1.0e-8
    mixing_beta = 0.7
 /
ATOMIC_SPECIES
 Pt 0.0   Pt.rel-pz-n-rrkjus.UPF
ATOMIC_POSITIONS
 Pt 0.  0.  0.
 Pt 0.5 0.5 0.7071
 Pt 0.  0.  1.4142
 Pt 0.5 0.5 2.1213
K_POINTS (automatic)
 2 2 1 1 1 1
EOF
$ECHO "  running the self-consistent calculation of fcc-Pt with 4 atoms...\c"
$PW_COMMAND < pt4.in > pt4.out
check_failure $?
$ECHO " done"

# Calculation of the transmission of Pt
cat > pt.cond_t.in << EOF
 &inputcond
    outdir='$TMP_DIR/'
    prefixt='pt4'
    bdl=1.4142,
    ikind=1
    energy0=0.0d0
    denergy=-0.2d0
    ewind=4.d0
    epsproj=1.d-7
 /
    1
    0.0 0.0 1.0
    1
EOF
$ECHO "  running the calculation of the transmission of fcc Pt...\c"
$PWCOND_COMMAND < pt.cond_t.in > pt.cond_t.out
check_failure $?
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR: done"
